### ISSUE TITLE
Sample database

### ISSUE THREAD

**Issue by vegarringdal** [Wakanda/wakanda-issues#100]
Is there any new sample database with person, company tables, where the tables have most normal attributes/picture so its easy to test with ?

**Comment by bea2701** [comment]
good question tkx

**Comment by vegarringdal** [comment]
anything new here ?

**Comment by fredGandelot** [comment]
We had in the past some samples . We candidature think of providing one.
Nice input !
With the New solution template it could be easy to scaffold a solution with Models and data in it. 
I use it for personal demo so i can definitely see the interst of such a feature

**Comment by hamzahik** [comment]
@vegarringdal 
the code is not clean but it works
https://github.com/hamzahik/wakanda-db-test
to generate the db run the file generate.js on the backend folder
