### ISSUE TITLE
Bad Server Location on macOS Sierra

### ISSUE THREAD

**Issue by cedricss** [Wakanda/wakanda-issues#102]
The default server location is wrong on macOS Sierra.

This is probably due to macOS Sierra introducing _"Gatekeeper Path Randomization"_ (aka _"AppTranslocation"_).

**Workaround**: after confirming the alert dialog, just browse back to `Applications`(or any custom installation folder) and select `wakanda-server`.

<img width="539" alt="screenshot" src="https://cloud.githubusercontent.com/assets/802010/18915022/c8eff766-858f-11e6-8178-cd2a51367d3d.png">

**Comment by hamzahik** [comment]
fixed in the 2.0
