### ISSUE TITLE
Broken Wakanda Studio "Keep In Dock" on macOS Sierra

### ISSUE THREAD

**Issue by cedricss** [Wakanda/wakanda-issues#103]
On macOS Sierra:
- Start Wakanda Studio, right click on the app icon and select _"keep in dock"_
- Close Wakanda Studio. Wait a moment or restart your computer.
- Try opening the Studio from the dock. 

The app can't be found:

<img width="133" alt="wakanda-studio-dock" src="https://cloud.githubusercontent.com/assets/802010/18943765/f56576bc-8621-11e6-88d4-838e5dafdc81.png">

This may be related to #102

**Comment by FrancoisMarchal** [comment]
unable to reproduce. Do you run the app from a DMG ?

**Comment by hamzahik** [comment]
fixed in the 2.0
