### ISSUE TITLE
[4D Mobile] Can't remove an entity with 4D v15 R5

### ISSUE THREAD

**Issue by JUX84** [Wakanda/wakanda-issues#104]
Hello,

I have noticed a problem with the removal of my entities.

I have updated to `4D v15 R5 build 15R5.203500 64 bits`

I tested the exact _same code_ with `4D v15 R4 build 15R4.199889 32 bits (beta 1)` and it worked.

Here's the error code that 4D sends when trying to remove:

> String value: Error code: 1828
> REST method: "delete" cannot be used on a HTTP GET
> component: 'dbmg'
> task 75599, name: 'HTTP connection handler'

**Comment by hamzahik** [comment]
Hi @JUX84,

Can you give us more details  : 
- what are you using to access your DB ? ( RAW REST, angular-wakanda, Wakanda javascript client)
- if using a connector what is the version of angular-wakanda/javascript client your app is using ?
- what version of Wakanda are you using ?

**Comment by JUX84** [comment]
Hi,

This issue happened when using Angular-Wakanda to call a Wakanda method which was just doing: `var a = ds.Table.find(filter); a.remove();`

I'm indeed working with 4D Mobile as a connector.
I'm using Wakanda Enterprise Studio 1.1.0, and angular-wakanda 1.2.0.

If you need any other information, don't hesitate.

Regards.

**Comment by fredGandelot** [comment]
Hi @JUX84  ,

 I think that the 4D Team might have added some security permissions to Get method. 
On the Wakadna side we have implemented the same code but we do not have already delivered it.

I ask the dedicated team and get back to you asap.
Fred

**Comment by fredGandelot** [comment]
AS pointed out in my previous comment some new security permissions has been added in 4D to prevent GET calls to remove entities.

A fix has already been developed in Wakanda and will be delivered in the next version. FOr now unfortunately I would suggest u to stay your current working version.

**Comment by fredGandelot** [comment]
@JUX84  it's fixed and integrated in WAKANDA V2
