### ISSUE TITLE
Not a bug but how to avoid browser cache on image upload ?

### ISSUE THREAD

**Issue by yboukhata** [Wakanda/wakanda-issues#11]
<a href="https://github.com/paulsouche"><img src="https://avatars.githubusercontent.com/u/5860504?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [paulsouche](https://github.com/paulsouche)**
_Tuesday Mar 24, 2015 at 08:40 GMT_
_Originally opened as https://github.com/Wakanda/angular-wakanda/issues/11_

----

I recently create an upload API via httpHandlers for my entities.

When I upload an image file, the file is front-converted in data uri and the user see the new image. On save, I upload the real file on the server and the update is OK.

But when I access again the entity, the old image returns... This is because the image's URL is cached by the browser and not server-fetched again. Everything works fine if I reload the page clearing the cache.

So my question is 

"Could we find a way to tell the entity your image attribute is no longer fresh ?"

Thanks

**Comment by jonathanargentiero** [comment]
A solution has been implemented in the latest version of Wakanda Server. The REST API will now return an updated version of the URL with a changing get attribute called *version*:

```` 
{ "uri" : "/rest/Entity(1)/imageAttribute?$imageformat=best&$version=5&$expand=image", "image":true }
````

This parameter is now provided by default and it will change on new image uploads. 

*Note: It doesn't provide access to the previous versions of the image*
