### ISSUE TITLE
Query null values in database rest api. Is this possible ?

### ISSUE THREAD

**Issue by vegarringdal** [Wakanda/wakanda-issues#111]
query null values in database rest api
Is this possible ?

If not will it be added, or a way to map null to blank values or something ?

tried "attribute=null" in $filter and with NULL and Null, but really not possible to do from the rest api

**Comment by fredGandelot** [comment]
Hi @vegarringdal  ,

Strangly it appears after just a quick test that it's possible to query a `not null`value but not `null` values

In facts :
`http://127.0.0.1:8081/rest/DataClass1/?$filter="Attribute1!=:1"&$params='["null"]' ` do work

But 

` http://127.0.0.1:8081/rest/DataClass1/?$filter="Attribute1=:1"&$params='["null"]' `do not work

i dig into this a keep u posted asap Vegar.

**Comment by fredGandelot** [comment]
Of course I'll create an Issue to  provide a fix asap if after all querying null values is not possible

**Comment by vegarringdal** [comment]
thx for looking into this.

**Comment by fredGandelot** [comment]
Euhh finally I've performed an easier test, and I got the correct result.
@vegarringdal  did u simply try ?

``http://127.0.0.1:8081/rest/DataClass1/?$filter="Attribute1=null"  ``

it worked for me.
Can u get back to me ? :)

**Comment by vegarringdal** [comment]
Ill do a new test, Ill do a simple one too :-)

**Comment by vegarringdal** [comment]
ok, did a new test, looks like it work on storage attributes/ related attributes, but not alias attributes

**Comment by vegarringdal** [comment]
I would expect that to work too, because server is returning null for alias attribute for another class when not linked.

**Comment by fredGandelot** [comment]
U're right it should work on aliases too.
I ll create a bug entry tomorrow :)

**Comment by vegarringdal** [comment]
Great.

**Comment by vegarringdal** [comment]
@fredGandelot should this post be tagged as bug since alias attributes when not linked can be used with null?

**Comment by hamzahik** [comment]
@vegarringdal an internal bug was created to fix the issue
