### ISSUE TITLE
Convert from Data Model Editor to API

### ISSUE THREAD

**Issue by chriscurnow** [Wakanda/wakanda-issues#112]
I generally create all my data model classes through the API. I remember reading that was the better way to do it for advanced users.

Is it possible to convert a class created with the Data Model Editor to the API?

Just creating a new class and remembering how much typing (i.e. typing through the keyboard) to create it. It would be nice to use the Datas Model Editor and then convert to the API.

**Comment by fredGandelot** [comment]
Hi @chriscurnow  

FOr now there is no way to transform a dataclass created via the Model Designer to the equivalent JS model API. However, it's quite easy to do, and maybe using the `source` button (JSON view) might help you coding the javascript Model API ( http://livedoc.wakanda.org/Model/Working-with-the-Model-API.200-995188.en.html )

THanks anyway it 's nice idea and I may submit it to the Model team :)

**Comment by chriscurnow** [comment]
Hi @fredGandelot ,

Thanks for your response.
Yes, I am quite familiar with the Model API.

It's just sometimes when I have a class with a lot of attributes, it would be nice just to be able to choose from a drop down list.

For instance just having to type ` = new Attribute(''storage", "string")` a hundred times gets a bit tedious:)

Anyway, maybe one for a future release.

**Comment by hamzahik** [comment]
@chriscurnow I taggued the issue as a feature-request so we can take it into account in futur releases
