### ISSUE TITLE
export/import datasource to/from a text file

### ISSUE THREAD

**Issue by magonzacha** [Wakanda/wakanda-issues#113]
Hi,

I need to create a text file with the data stored on wakanda datasource of my solution. In the opposite way I need to read from a text file and store the data on my wakanda datasource solution.
Is there any example about this in wakanda?

I'm new to wakanda so what I've tried don't work within wakanda.

Many thanks for your help in advance
Miguel

**Comment by hamzahik** [comment]
Hi @magonzacha,

See the section `Creating new entities` of this page http://wakanda.github.io/wakanda-server-doc/#/doc/data/server-side
The example `002` is the following : 
```javascript
var strHeroes       = File('/PROJECT/backend/heroes/list.json').toString('utf-8');
var heroes          = JSON.parse(strHeroes);
var photosFolder    = Folder('/PROJECT/backend/heroes/images/');
//Get the company with ID = 1
var heroAssociation = ds.Company(1);

heroes.forEach(function(hero){
	var h = new ds.Employee();
	h.firstName = hero.fName;
	h.lastName  = hero.lName;
	h.dob       = new Date(hero.dob);
	h.photo     = loadImage(File(photosFolder, hero.photo));
	h.company   = heroAssociation;
	h.save();
});
```
the JSON files contains the following : 
```json
[
	{
		"fName" : "Atomic",
		"lName" : "Samurai",
		"dob"   : "01/01/1979",
		"photo" : "atomic_samurai.png"
	},
	{
		"fName" : "Superalloy",
		"lName" : "Darkshine",
		"dob"   : "01/01/1989",
		"photo" : "superalloy.png"
	},
	{
		"fName" : "Child",
		"lName" : "Emperor",
		"dob"   : "01/01/2006",
		"photo" : "child_emperor.png"
	},
	{
		"fName" : "Metal",
		"lName" : "Bat",
		"dob"   : "01/01/1999",
		"photo" : "metal_bat.png"
	},
	{
		"fName" : "Flashy",
		"lName" : "Flash",
		"dob"   : "01/01/1991",
		"photo" : "flashy.png"
	}
]
```

If you just want to import/export data manually, there is an explanation on the top of the same page on how to run code examples.
If you want to do it from an HTTP request just confirm and I'll give you more details.

**Comment by magonzacha** [comment]
Hi @hamzahik 

Thank you very much for this info.

Regards
Miguel

**Comment by magonzacha** [comment]
Hi @hamzahik 

I'm doing the example but the words File and JSON don't change to blue.
Does this mean that wakanda doesn't recognize those words as commands.

Sorry for my vocabulary but I use to work with 4D and now the naming is different.

Mny thanks
Miguel

**Comment by hamzahik** [comment]
@magonzacha don't worry about the vocabulary ;)

Make sure your file has the extension `.js` and that it is found in the `backend` folder of your project.

This video shows the whole process https://www.youtube.com/watch?v=z4TSaxs2AaM

**Comment by magonzacha** [comment]
Hi @hamzahik 

Thank you very much.

Miguel

**Comment by magonzacha** [comment]
Hi @hamzahik 

Sorry to bother you.
What is wrong with this path. Keep saying that is invalid.
var lines = File('D:\AcuBaseDev\Wakanda\Transfer3\Transfer3\backend\ImportGenData.json').toString('utf-8')
	var patients = JSON.parse(lines);

I've changed to this and it says that the system cannot find the path.

	debugger;
	var lines = File('Transfer3/Transfer3/backend/ImportGenData.json').toString('utf-8')
	var patients = JSON.parse(lines);


Many thanks

**Comment by hamzahik** [comment]
@magonzacha  I'm here to help don't hesitate to ask questions :)

In JavaScript you need to escape \ inside strings by replacing it with \\ 

```javascript
var lines = File('D:\\AcuBaseDev\\Wakanda\\Transfer3\\Transfer3\\backend\\ImportGenData.json').toString('utf-8')
var patients = JSON.parse(lines);
```

I advise you to use this path instead : 

```javascript
var lines = File('/PROJECT/backend/ImportGenData.json').toString('utf-8');
var patients = JSON.parse(lines);
```

the server will automatically replace PROJECT with your project's path.

**Comment by magonzacha** [comment]
Hi @hamzahik 

Thanks changing to PROJECT works.
Now Is complaining about sintax error, unexpected string on the second line.
Could be that the var creating here has the same name as the datasource table?

Another question.
When this seond line runs what do I get in the variable associated. Do I have the full content of the file?

Many thanks

**Comment by magonzacha** [comment]
Hi @hamzahik 

This is the code that I trying to get it work.
Patient is a datasource
Does this code have another problem in your view?


var lines = File('PROJECT/backend/ImportGenData.json').toString('utf-8')
var pats = JSON.parse(lines);
	
	/*  columns [0]  First Name
	    columns [1]  Surname
	    columns [2]  Admission Date
	    columns [3]  eMail address
	*/
	var columns = [];
	lines.forEach( function(oneLine){
		columns = oneLine.split("\t");
		var thePat = ds.Patient.find("First_Name = :1 and Surname = :2",columns[0], columns[1]);
		if(thePat == null)
		{
			thePat = new ds.Patient({
				First_Name	: columns[0],
				Surname		: columns[1],
				AdmissionDate : columns[2],
				eMail		: columns[3]
			});	
			thePat.save();
		}
	});

Many thanks 
Miguel

**Comment by hamzahik** [comment]
@magonzacha maybe you wanted to use `pats.forEach` instead of `lines.forEach` ?

**Comment by magonzacha** [comment]
@hamzahik  I've realize that and I've changed but still sending that error message.

Thanks
Miguel

**Comment by hamzahik** [comment]
@magonzacha can you send me the content of the file you are importing of just the 10 first lines.

**Comment by magonzacha** [comment]
Hi @hamzahik 

I've change the code for reading from a text file that suit me better than json.
The lines that I'm trying to import into the Patient datasource is at the end of this message.
Still giving me an error.

var lines = File('PROJECT/backend/ImportGenData.txt').toString('utf-8')

/*  columns [0]  First Name
    columns [1]  Surname
    columns [2]  Admission Date
    columns [3]  eMail address
*/
var columns = [];
lines.forEach( function(oneLine){
    columns = oneLine.split("\t");
    var thePat = ds.Patient.find("First_Name = :1 and Surname = :2",columns[0], columns[1]);
    if(thePat == null)
    {
        thePat = new ds.Patient({
            First_Name  : columns[0],
            Surname     : columns[1],
            AdmissionDate : columns[2],
            eMail       : columns[3]
        }); 
        thePat.save();
    }
});




Jane	Austin	19/04/2016	jane.austin@nonsense.com
Will	Smith	15/05/2016	will.smith@irobot.com
Dan	Brown	19/06/2016	dan.brown@inferno.com


Thank you
Miguel

**Comment by magonzacha** [comment]
Hi @hamzahik 

I've manage to make it work the method for uploading a file to a datastore.
Now I need to do the oposite. From the datastore to a tab delimited text file.

Can you give me an advice please?
I guess I have to create the line myself with the tabs for separating fields and carriage return for ending the line.
How do I write the line to a text file after that?

Thank you very much for your help and understanding.

Miguel

**Comment by hamzahik** [comment]
Hi @magonzacha,

Did you manage to solve your problem ?

Hamza

**Comment by magonzacha** [comment]
Hi Hamza,

Yes, thank you.

Can I take the opportunity to ask you if Wakanda can create and call web services?

Kind regards
Miguel 

-----Original Message-----

**Comment by magonzacha** [comment]
Sorry I've replied to this without looking at the other messages.

I'll check what you have sent me about web services.

Many thanks
Miguel 

-----Original Message-----
