### ISSUE TITLE
Can't find Wakanda-Angular2 beta 

### ISSUE THREAD

**Issue by stevendice** [Wakanda/wakanda-issues#114]
Recently Wakanda offered a Wakanda-Angular2 beta app and an example exists on github. [https://github.com/StephaneGarnier/WakManager-angular2]. The beta set up a working environment for Angular2 with the correct folders and files. The github example demonstrated basic query request ect. 

Can not locate the Angular2 version at this time. What is the status of Wakanda-Angular2?

**Comment by hamzahik** [comment]
@stevendice Angular2 and Ionic2 are integrated in Wakanda since the 1.1.0 release.
When creating your app you can select Angular2 as front framework and Ionic2 as mobile framework.
http://wakanda.github.io/wakanda-studio/choose-templates.html
