### ISSUE TITLE
Wakanda Error when Running when running Android device

### ISSUE THREAD

**Issue by FherPie** [Wakanda/wakanda-issues#117]
I have installed Wakanda Studio and Server Community Edition on Windows 10 and I create a project with angular and ionic. When I clic in button Run, with Run Android Devices checked, I get this:

[Environment] $ C:/Users/panao/OneDrive/Documentos/Wakanda/solutions/conocimientoefectivo/conocimientoefectivo/mobile ionic platform list [Environment] WARN: ionic.project has been renamed to ionic.config.json, please rename it. [Environment] Installed platforms: android 5.2.2 Available platforms: amazon-fireos ~3.6.3 (deprecated) blackberry10 ~3.8.0 browser ~4.1.0 firefoxos ~3.6.3 webos ~3.7.0 windows ~4.4.0 wp8 ~3.8.2 (deprecated)

[Environment] $ C:/Users/panao/OneDrive/Documentos/Wakanda/solutions/conocimientoefectivo/conocimientoefectivo/mobile ionic plugin list [Environment] WARN: ionic.project has been renamed to ionic.config.json, please rename it. [Environment] cordova-plugin-whitelist 1.3.1-dev "Whitelist"

[Environment] $ adb devices [Environment] List of devices attached e390ead8 device

[Environment] $ C:/Users/panao/OneDrive/Documentos/Wakanda/solutions/conocimientoefectivo/conocimientoefectivo/mobile ionic run -slc -device android --target=e390ead8 [Environment] WARN: ionic.project has been renamed to ionic.config.json, please rename it. [Environment] âœ— You cannot run iOS unless you are on Mac OSX.

Error when Running when running Android device e390ead8 

I have my android phone connected to computer and enabled to debugin USB, I would like to know what happends. I am trying Wakanda.

**Comment by hamzahik** [comment]
Hello @FherPie, it seems the studio is trying to run your app on iOS even it it is Android.
We will check this out and get back to you asap.

Thanks for the feedback.

**Comment by hamzahik** [comment]
Fixed in the [1.1.2](https://github.com/Wakanda/wakanda-digital-app-factory/releases/tag/v1.1.2) release
