### ISSUE TITLE
Web Services in Wakanda?

### ISSUE THREAD

**Issue by magonzacha** [Wakanda/wakanda-issues#118]
Hi There,

In 4D you can use web services but I don't know if in Wakanda you can do the same.
I've looked to documentation but they don't mention web services. Could be that in Wakanda they called differently or they implement them in a different way.

Has anyone implemented a web service in Wakanda. I'm interesting in calling a web service within Wakanda and offering a web service within Wakanda.

Many thanks for your help.

Miguel

**Comment by hamzahik** [comment]
Hi @magonzacha,

The equivalent is this http://livedoc.wakanda.org/XMLHttpRequest/XMLHttpRequest-Constructor/XMLHttpRequest.301-867272.en.html

Let me know if this solves your problem :)

**Comment by magonzacha** [comment]
Thank you very much for the help.
I've ended up using sockets. It is working quite well and was easy to implement.
I've got a listener that I've made sometime ago written in 4D.
With Wakanda I can get the information back from the listener. The data received I put it in an array.
My problem now is that for some reason saving on the datastore is behaving in a weird way.

I've done this when I'm importing data from 4D through a text file and that worked well. However in there I'm creating records in the datastore.
In this case the records exists and I need to modify or add information to the fileds.
This is the code that I'm using. rxFields array is where my values are coming from the listener and the var inBase is true.
If I change the find() for a query() it send me an error when I Pat.save() the record

	var thePat = ds.Patient.find("Number = :1 and Still_InBase = :2",rxFields[0],inBase);
	if(thePat != null)
	{
		thePat.Number		= rxFields[0];
		thePat.AdmDate	        = new Date(rxFields[1]);
		thePat.Department		= rxFields[3];
		thePat.save();

		var dateAssess = new Date();
		var timeAssess = "";
		var theBase = ds.BaseAssessment.query("AssessDate = :1 and AssessTime = :2", dateAssess, timeAssess);
		if(theBase == null && thePat != null)
		{
			theBase = new ds.BaseAssessment({
				BasePatId:thePat  // creating the relation
			});
			theBase.save();
		}
}

**Comment by magonzacha** [comment]
To clarify my problem is that using the code above I can see that is saved on the datastore if I show it in the console but when I go to run the web page the information doesn't appears there.
I don't know what could be wrong that is making the information just added disappears. If I go to the server 127.0.0.1:8080/index.html on my computer and look at the data there it doesn't appears there either.

Miguel

**Comment by magonzacha** [comment]
An update of my problem is that is working now. For some reason when I was adding a record on the grid in the webpage was adding an extra one all blank. When I've deleted the blank one and then bring the information to the listener start working.

My problem now is with the dates I've tried many things.
The date is comming as "25/09/2016" but when I assign that value to the datastore attribute it shows null.
I've used the date function, I've converted to an american string then apply the date function but nothing it seems to be working.

Can someone please tell what will be the best way to load a string date value in a date attribute?

Miguel

**Comment by hamzahik** [comment]
@magonzacha can you please reproduce the problem on a small solution so we can check it out and help you.

Hamza

**Comment by magonzacha** [comment]
Hi @hamzahik.

The problem has been solved.
When I was adding a record with the widget grid actually was adding two. I don't know why.
After deleting the second blank record the updating information appears on the grid.

Don't know why this behavior of the grid but I've ade some changes in the datastore as well. It could be that something on the datastore was creating the problem.

Many thanks anyway.
Miguel
