### ISSUE TITLE
Wakanda Angular 2 webpack installs but not working

### ISSUE THREAD

**Issue by darrellhpl** [Wakanda/wakanda-issues#119]
Hi,

I running the Wakanda Enterprise Studio version 1.1.0 the install was successful but when I create a  new Angular 2 style solution and attempt to run and view the angular web page I receive a 404 - Not Found error. As you can see from the screen shot there are not environment issues how can I fix. I
![screenshot 2016-11-02 10 04 37](https://cloud.githubusercontent.com/assets/20045761/19924752/36c4faa0-a0e5-11e6-8030-4b80f3978571.png)

Thanks

Darrell

**Comment by darrellhpl** [comment]
If I click on another .ts file to preview structure the screen freezes. Is this because Wakanda install has not installed the node modules folder with the relevant npm files. if this is the case how do I fix. I have attached a screenshot of issue.
![screenshot 2016-11-02 10 22 47](https://cloud.githubusercontent.com/assets/20045761/19925274/2b8a7398-a0e7-11e6-8a48-4804e00b2709.png)

**Comment by SebCourvoisier4D** [comment]
Can't reproduce the issues (Wakanda 1.1.0 and 1.1.1, Node.js 6.9.1, MacOS Sierra)

**Comment by darrellhpl** [comment]
Hi 
Eventually found this solution link which worked for me: 
https://github.com/Wakanda/wakanda-issues/issues/74https://github.com/Wakanda/wakanda-issues/issues/74

Go virtually to the bottom of the post to view solution.

It appears to be due to some folders causing the issue ~/Documents/Wakanda/Extensions folder, and then, restart the Studio. See link above to remove extensions and fix
