### ISSUE TITLE
Wakanda/wakanda-10-min-quickstart does not work

### ISSUE THREAD

**Issue by rocklob** [Wakanda/wakanda-issues#121]
I'm using the latest Wakanda (Enterprise Studio 1.1.0) and tried to follow the angular-wakanda quickstart found at https://wakanda.github.io/angular-wakanda/#/doc/quickstart

It does not work. The quickstart seems like it might be written for an older version of Wakanda as the instructions do not fully match the interface.  After following the instructions as best as I can, using both Angular 1 and Angular 2 solutions, I only see this when running the page:

```
Number of tasks : {{tasks.length}}
```

I also tried cloning the solution from https://github.com/Wakanda/wakanda-10-min-quickstart.git and opening it in Wakanda.  Unfortunately, that won't even run and gives me these errors in the console:

```
[Environment] npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/Cellar/node/6.8.1/bin/node" "/usr/local/bin/npm" "start" "--" "--" "--serverUrl" "http://127.0.0.1:8081" "--port" "8000" "--livereloadPort" "35729"
npm ERR! node v6.8.1
npm ERR! npm v3.10.8

npm ERR! missing script: start
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR! <https://github.com/npm/npm/issues>
```

**Comment by intissarMez** [comment]
Hello @rocklob 
Do you have a `start` script defined in package.json ? If not, please update your `package.json` with the following
```
"scripts": {
 "test": "echo \"Error: no test specified\" && exit 1",
    "serve": "gulp serve",
    "start": "npm run serve",
    "build": "gulp build",
    "prebundle": "npm run build",
    "bundle": "node bundle.js"
}
```

**Comment by rocklob** [comment]
No, the package.json in the repository does not contain the start script.  However, after making your changes, it works now.
