### ISSUE TITLE
wakanda 1.1.1 community setup error

### ISSUE THREAD

**Issue by contactez23** [Wakanda/wakanda-issues#122]
hi when i try to setup wakanda community 1.1.1 x86 i get this error in french:ce package d'installation n'est pas pris en charge par ce type de processeur.
my OS : Windows 7 SP1 32 bits.

**Comment by hamzahik** [comment]
Hi @contactez23 ,

This is a known issue a fix will be released asap (1.1.2)

Thanks for the report

Hamza

**Comment by hamzahik** [comment]
@contactez23 fixed in 1.1.2.
Please re-open the issue if you still have the problem.
