### ISSUE TITLE
Socket problem

### ISSUE THREAD

**Issue by magonzacha** [Wakanda/wakanda-issues#125]
Hi there,

I've took this code from an example in the manual and actually is not working. 

var net = require('net');
var server = net.createServer(function(socket) { //'connection' listener
    console.log('server connected');
    socket.on('end', function() {
        console.log('server disconnected');
    });
    socket.write('hello\r\n');
});
server.listen(8082, "127.0.0.1", function() { //'listening' event listener
    console.log('server bound');
});

It says that "Cannot read property 'listen' of undefined".
When I check with the debugger the var server that is creating at the top it says undefined.

What I need to do is to create a listener and for that I need to create a socket that keep listening for incoming messages.

I'll appreciate any input about this.

For another method I've used the code  below but this connects to a server that is already listening.
var socket = new net.Socket();
// Connect the socket
socket.connect(8082, '127.0.0.1', function () {

Thank you very much in advance.
Miguel

**Comment by JegoYann** [comment]
Hello @magonzacha,
We will take a look and get back to you as soon as possible.
Yann

**Comment by JegoYann** [comment]
Hello @magonzacha,
Looks like `server` is a unmodified reserved variable. The above example is working if you change `var server` by something else like `var myServer` and do a `myServer.listen`.
We are providing a fix for the next major release.

Yann

**Comment by magonzacha** [comment]
Many thanks Yann
