### ISSUE TITLE
Does not load RPC module at start

### ISSUE THREAD

**Issue by magonzacha** [Wakanda/wakanda-issues#127]
Hi There,

I've got a problem at the moment where Wakanda is unable to load the RPC module.

When I try to use the functions created in the RPC module send a message that it reads "Failed to load resource: the server responded with a status of 404 (Not Found)"

I've got the myModuleRPC.js file in the module folder and is declared as an RPC module.
On the client I've added the module reference as well.

I don't understand why is not recognizing the module.

What could be wrong?

Many thanks in advance.

Miguel

**Comment by JegoYann** [comment]
Hello @magonzacha,
Can you give me more details ?

- Did you follow the RPC documentation ? http://doc.wakanda.org/home2.en.html#/Using-JSON-RPC-Services/RPC-Example.200-954748.en.html
- Can you show the code of RPC JS file ?
- How do you trigger the RPC method from frontend ?

Regards,
Yann

**Comment by magonzacha** [comment]
Hi Yann,

This was working without problem 2 days ago. Yes I have follow the documentation that you mentioned.

This is how I call the RPC method from the client.

	GetListener.click = function GetListener_click (event)
	{
		debugger;
		msg = MyRPC.GetListenerDataAsync({
			'onSuccess' : function(result){
				console.log(result);
			},
			'onError' : function(error){
				console.log('An error ocurred: '+error);
			},
			'params' : ''
		});	
	};


This is what I do in the server side.

exports.GetListenerData = function GetListenerData (){
	// Here I create a socket to connect to a server
      //   Then when I receive the information I save it in the datasource tables.
	return ('');
};

I just added extra fields in the listener data on the server side and after that I went to test and Wakanda cannot load the RPC module.

I've checked against the documentation and the basic steps to make it work are all right.
Not sure what else could be gone wrong.
On the code side I just increase the number of fields that I have to read from the server only no major changes.


Regards
Miguel

**Comment by JegoYann** [comment]
Hello @magonzacha,
If it was working before, this means the error is raised by the small changes you add. It could be a syntax error in your RPC module that invalidates it. Try a `diff` on your updates files.
If no luck, I'm afraid, I will need your solution to help you more.

Regards,
Yann

**Comment by magonzacha** [comment]
Hello @JegoYann ,

You were right it was a missing comma after doing the changes.
When Wakanda is loaded into the browser it does some sort of compilation?

Sometimes I see a little red underline when you have something wrong or an exclamation mark. This time I get nothing that's why I didn't understand what was going on.

Thank you very much for your help.

Regards
Miguel

**Comment by JegoYann** [comment]
The code editor parses your line of codes to provide autocompletion and syntax errors. But sometimes, it may miss some. We are working to get it more fast & efficient for the next major release.

Regards,
Yann

**Comment by magonzacha** [comment]
That's excellent.
Thank you very much for your hard  work I'm starting to like a lot Wakanda.
I've been developing in 4D for many years and now we have the chance to have a go to Wakanda.

Regards
Miguel
