### ISSUE TITLE
TreeView content disappear in wakanda documentation web site

### ISSUE THREAD

**Issue by alcada** [Wakanda/wakanda-issues#131]
Hi
The content of the treeView from the left part of the page in http://doc.wakanda.org is missing. Same thing in the wakanda studio if we click to open a Documentation Tab. Now we can't navigate through the help docs

**Comment by JegoYann** [comment]
Hello @alcada,
It has been fixed Tuesday. Could you refresh your browser cache and retry ?

Regards,
Yann

**Comment by alcada** [comment]
Hello Yann..
No way....
I try to reload the page, reset safari, with firefox the same, in MacOS El capitan, in OS Sierra, and  treeview content did not appears. I have tried also in windows 10 with Microsoft Edge and the problem is the same. Inside wakanda studio, link Documetation, the tab that came out have the same missing tree view content
Regards 
Luís Alçada

**Comment by JegoYann** [comment]
Thank you @alcada. We are working on it.

**Comment by Ganbin** [comment]
I have seen this issue too but now it works for me...

**Comment by alcada** [comment]
OK. Today it works for me too, either in the wakanda studio documentation tab, as in doc.wakanda.org. Even the "Search in contents" link that follows a "Search in Doc Center" query, works perfecly (many times in the past the "Serch in contents" dont work - dont return any results or the link dont appear).
For me it is ok to close this issue.
Regards
alcada

**Comment by JegoYann** [comment]
Great @alcada @Ganbin ! Thanks for your feedback !
