### ISSUE TITLE
[Enteprise] 403 Forbidden from external POST request

### ISSUE THREAD

**Issue by Ganbin** [Wakanda/wakanda-issues#134]
Wakanda Enteprise Server 11 Build 197492

Hello,

I have a client which cannot release is application because of a strange bug.

He have this setup : a Wakanda Enteprise Server on a client machine. On this client machine, he have a SSL certificate for securing connection. On the local machine, he can make the application work nicely with a `localhost` connection. He have set up the external hostname and he can access and get all the page load. The only problem is that when he have some `POST` request, he get that response(1). So we can see that it is a problem on the Wakanda side that refuse the connection from extern. The exactly same request with a `GET` works fine. He have set up the CORS settings to accept any connection from this external ressource. So we stack to know how to solve this issue.

Is there any bug known about this `403 Forbidden` problem or anyone have any clue why this happens?

Thanks

(1)
````
<!--
* This file is part of Wakanda software, licensed by 4D under
*  (i) the GNU General Public License version 3 (GNU GPL v3), or
*  (ii) the Affero General Public License version 3 (AGPL v3) or
*  (iii) a commercial license.
* This file remains the exclusive property of 4D and/or its licensors
* and is protected by national and international legislations.
* In any event, Licensee's compliance with the terms and conditions
* of the applicable license constitutes a prerequisite to any use of this file.
* Except as otherwise expressly stated in the applicable license,
* such license does not include any other license or rights on this file,
* 4D's and/or its licensors' trademarks and/or other proprietary rights.
* Consequently, no title, copyright or other proprietary rights
* other than those specified in the applicable license is granted.
-->
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>403 - Forbidden</title>
<style>
	body { margin: 0px; padding: 0px; font: 90% "Lucida Grande", Lucida, Verdana, sans-serif; }
	div#title { background-color: #2c4b79; padding: 15px 15px 15px 20px; margin: 0px; }
	div#message { padding: 20px; }
	div#details { padding: 10px; }
	h2 { color: #fff; font-size: 1.3em; margin: 0; padding: 0; }
	p { padding: 0px; margin: 0px; }
</style>
</head>
<body>
<div id="title">
<h2>403 - Forbidden</h2>
</div>
<div id="message">
<p></p>
</div>
<div id="details">
<code></code>
</div>
</body>
</html>
````

**Comment by JegoYann** [comment]
Hello @Ganbin,
We have no knowledge of such issue. The easy way, would be to take a look at the solution. Is it possible ? Or at least, could you give us the Request details, CORS settings and SSL settings ?

The issue may be fixed in the last version. Is it a possibility to migrate the solution to Wakanda v1.1.2 ?

Regards,
Yann

**Comment by Ganbin** [comment]
I will look to give you the settings. But the solution is an Enterprise version and I can only find the v11 Build 197492 on the 4D website download section. Where I can found new version of the enterprise?

**Comment by Ganbin** [comment]
Ok I have found under `https://console.wakanda.io` that I can donwload a new version but it is tagged at `1.1.0`

**Comment by JegoYann** [comment]
`v1.1.2` will be available soon on `https://console.wakanda.io`. It's ok to begin the migration with `v1.1.0`.

**Comment by hamzahik** [comment]
This was a CORS configuration issue, it is now fixed after direct communication with @Ganbin
