### ISSUE TITLE
[Enterprise]Wakanda delete row ?

### ISSUE THREAD

**Issue by DomTkt** [Wakanda/wakanda-issues#135]
In Wakanda Studio Enterprise, I can't delete one row of data, I have a network error

401 (Unauthorized) or 500 (Internal Server Error)
I enabled CORS and allow all and all request methods.

I would like to know if someone can delete on row of data in their 4D Server.

Thanks.

**Comment by JUX84** [comment]
Hi DomTkt,

Depending on the 4D version you're using, this issue might be related to: #104

**Comment by DomTkt** [comment]
Hi JUX84, 

Thanks for you answer, i'm using 4D v15 R5, so there aren't issues for this version ?

**Comment by JUX84** [comment]
I guess either rolling back to v15 R4, _OR_ waiting for a dev's response 😄

**Comment by fredGandelot** [comment]
Hi @DomTkt  

Thanks for reaching us. As mentioned correctly by @JUX84 an issue occured in v15 r5.
I copy/paste you the message I wrote in the other thread.

```
AS pointed out in my previous comment some new security permissions has been added in 4D to prevent GET calls to remove entities.

A fix has already been developed in Wakanda and will be delivered in the next version. FOr now unfortunately I would suggest u to stay with your current 4D working version.
When the fix will be available in Wakanda then u'll be able to upgrade yr 4D version.
Unfortunately I cannot give u yet any ETA for the shipment of the next minor version of Wakanda, but we our best to make it asap.
Sorry for the inconvenience.
```

**Comment by DomTkt** [comment]
Ok, thanks for your answer !

**Comment by fredGandelot** [comment]
@DomTkt   it's fixed and integrated in WAKANDA V2
