### ISSUE TITLE
Solution must be reloaded to serve updated JS files (Enterprise 1.1.0)

### ISSUE THREAD

**Issue by NAMSGithub** [Wakanda/wakanda-issues#138]
When I update a JS file using Wakanda Studio, I have to reload the solution for the client browser to get the updated file. Clearing the cache on the browser does not cause it to load the updated javascript. I have page caching disabled in my project settings. This is undesirable because reloading the solution causes client sessions to drop.

**Comment by hamzahik** [comment]
Hello @NAMSGithub,

How did you start the server ? did you click on `Start Server` or `Run Page` or did you use a different method ?

As a side note : if you have an enterprise subscription, you can receive faster feedback by declaring issues on https://support.wakanda.io/

**Comment by NAMSGithub** [comment]
I click `Start Server` to do it. And yes I do have an enterprise subscription, I could post the issue there if that makes more sense.

**Comment by issameljohri** [comment]
Hello @NAMSGithub,

This is not reproducible for me on Windows.
Can you provide me with steps to reproduce this issue? 
Are you using Mac or Windows OS ?

**Comment by NAMSGithub** [comment]
Hi, I cannot reproduce this after all. I am using Mac OS. I will be sure to post an example solution next time I have an issue.
