### ISSUE TITLE
IOS BUILD FAILED with fatal error: 'Cordova/CDVViewController.h' file not found

### ISSUE THREAD

**Issue by kaseriya** [Wakanda/wakanda-issues#140]
I am just trying the Wakanda Studio community edition and getting the following error while building the ios app. Any help or suggestion appreciated 

```
[Environment] In file included from /Wakanda/solutions/HelloWakanda/HelloWakanda/mobile/platforms/ios/HelloWakanda/Classes/MainViewController.m:28:
/Wakanda/solutions/HelloWakanda/HelloWakanda/mobile/platforms/ios/HelloWakanda/Classes/MainViewController.h:28:9: fatal error: 'Cordova/CDVViewController.h' file not found
#import <Cordova/CDVViewController.h>
^
1 error generated.
```

> The following build commands failed:
> CompileC /Library/Developer/Xcode/DerivedData/HelloWakanda-bmpivbmivptdyjalaxfbnixdxsay/Build/Intermediates/HelloWakanda.build/Release-iphonesimulator/HelloWakanda.build/Objects-normal/i386/MainViewController.o HelloWakanda/Classes/MainViewController.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler

-- env details --
Wakanda Studio: 1.1.3
OS: MacOS Capitan
xCode: Version 8.2 (8C38)

**Comment by kaseriya** [comment]
For some reasons the xcode project was corrupted. Generally, to solve this kind of problems, you can try removing and re-adding the platform ios:

fixed it by running following commands
```
ionic platform rm ios
ionic platform add ios
ionic build ios
```

**Comment by sahajarora1286** [comment]
I had the same problem but only when Archiving. I researched a lot but none of the solutions worked. The only thing that worked for me is this:

1. Clean you project
2. **Build** your project
3. Archive your project. The Archive should now be successful.
