### ISSUE TITLE
Wakanda - Angular Push element in variable "Object" in 4D

### ISSUE THREAD

**Issue by DomTkt** [Wakanda/wakanda-issues#141]
Hello, i try to push element in Object in 4D but it's already undefined when i try to push, someone can help me please ?

My code : 

var entity = ds.MyTableIn4D.$create();
                entity.MyObjectVariableIn4D= {"name": "test"};

entity.$save().$promise.then(function() {
                    $scope.MyScope.push(entity);           
                });

**Comment by yboukhata** [comment]
Hi @DomTkt,

Object type are supported in `angular-wakanda`.

Is the property `MyObjectVariableIn4D` of **object** type ? If yes, are you using the last version of the connector ?

**Comment by DomTkt** [comment]
Hi, thanks for your answer !!

yes MyObjectVariableIn4D is Object Type, i try to install 4D v16 in my server, what do you mean by "the connector" ? angular-wakanda-min ??

**Comment by yboukhata** [comment]
@DomTkt,

> what do you mean by "the connector" ?

I mean by the connector the module `angular-wakanda`.

 Just to confirm and isolate the issue, can you try to save an entity with an `object` attribute type in a local Wakanda DataBase ? If it works, this means that the objects are not saved in the remote 4D database.

**Comment by DomTkt** [comment]
Thanks for your fast answer again yboukhata.
I can save an entity with an Object attribute in a local Database,
I can save an entity with string, number attribute in 4D Database,
but i can't save an entity with an object attribute, i think it's the angular-wakanda because i'm using 1.04

I use this version because i have some problems with save entity in 4D Database if i don't use 1.04 :/

**Comment by yboukhata** [comment]
@DomTkt 

You're welcome.

Which kinds of issues do you have when you use the latest version of `angular-wakanda` (v1.3.0) ?

Since you can save object attributes in local Wakanda Database, the issue is on the save to the remote Database.

We will try to reproduce it.

**Comment by yboukhata** [comment]
@DomTkt,

I have checked on my computer and it works. The object value are saved in 4D database.

I suggest you to check if there is no issue on your schema or something else.

**Comment by DomTkt** [comment]
@yboukhata Hello !

Could you tell me the version of angular-wakanda do you use ? and what are your version of Wakanda, and your version 4D Server please ?

**Comment by yboukhata** [comment]
Hi @DomTkt,

I'm using these versions :
* `Wakanda Enterprise` **V1.3.0**
* `angular-wakanda` **V1.2.0**
* `4D Server`**V16 R2**

**Comment by DomTkt** [comment]
@yboukhata Hello yboukhata !!

I have installed 4D server V16 and save object value work !!
Thanks for all !
