### ISSUE TITLE
WAK Server not releasing files in a Folder() when running in production mode

### ISSUE THREAD

**Issue by dellsmash** [Wakanda/wakanda-issues#143]
Hello,
When creating a folder() then iterating through it to gain access to the files on disk and converting these files to a BinaryStream for manipulation it seems the wakanda server will not release these files after the function finishes and returns.  If the wakanda server is started in design mode using the studio the files are released after the server function returns and everything is seemingly fine but in production mode the files are inaccessible until the wakanda server has been shutdown (process ended).

**Comment by JegoYann** [comment]
Hello,
I find it strange that you have a difference between `debug` and `production` runs. There are basically the same. The studio start the server the same way you start it from the command line.

Do you have any code samples you can provide of folder iteration and BinaryStream convertion ?
Is the `debugger` active on server?
Thanks

**Comment by dellsmash** [comment]
Hi JegoYann,
I do have some code if you want me to upload I will, however I found a workaround.  I was first converting the file to a "BinaryStream" and then immediately converting it to a buffer from that string,  I skipped the BinaryStream step and went straight to a buffer using the myfile.toBuffer() function.  All is well in production and design now

**Comment by JegoYann** [comment]
Great. Can I check with your use case if there is an issue with the `BinaryStream` ? Just in case.
No need to upload the full solution. Just copy here the step where you iterator over a folder and convert all files into `BinaryStream`.
Thanks

**Comment by JegoYann** [comment]
Did you `close()` the `BinaryStream` after each read/write action to release the reference on the `File`?

**Comment by dellsmash** [comment]
I did not!  I did however set the BinaryStream to null along with every other variable in the script.

**Comment by JegoYann** [comment]
Settings the `BinaryStream` to `null` won't delete it; just delete its reference.
I suggest you to try using the `BinaryStream.close()` to release your file handler before.

**Comment by hamzahik** [comment]
@dellsmash after using @JegoYann proposition do you still have the issue ?

**Comment by dellsmash** [comment]
I have not tried it.  I do not use the binary stream but instead convert directly.
