### ISSUE TITLE
Error when changing computer

### ISSUE THREAD

**Issue by magonzacha** [Wakanda/wakanda-issues#147]
Hello there,

I've been running wakanda in a computer without problems. Now I've copied the solution to another computer and stop working.
For example I've got this error message when I try to start a listener in the server (which was working fine in the other computer)

![wakkyerror](https://cloud.githubusercontent.com/assets/23026900/22503550/3085df20-e86a-11e6-865c-11980889a29e.png)

Many thanks in advance
Miguel

**Comment by hamzahik** [comment]
Hi @magonzacha,

Can you share the code of your file `OutreachListener.js` as well as the content of your project's settings file.

This will help narrow down the issue.

**Comment by vegarringdal** [comment]
Could it be something as simple as something else is using the port you are trying to listen to ?

**Comment by magonzacha** [comment]
Thank you very much.

An old application was using the port.
