### ISSUE TITLE
Wakanda Studio deployment 

### ISSUE THREAD

**Issue by idrissisimo** [Wakanda/wakanda-issues#15]
While using the studio deployment panel, when we click on the "deploy" button there's nowhere an indication that a deployment is running and the button is still available so that we can can run the deployment endlessly.

**Comment by cedricss** [comment]
Thanks for the feedback. I totally agree. We plan to improve progress and status info on git and deploy in our next sprint.

**Comment by hamzahik** [comment]
@idrissisimo the 1.1.0 community version was released with multiple UX enhancements for the Git and Deploy parts.

**Comment by hamzahik** [comment]
@idrissisimo check out the new release it should fix that UX problem ;)

**Comment by idrissisimo** [comment]
@hamzahik thank you, i just tested it and it's perfect ;)
