### ISSUE TITLE
wak 2.0 beta, promise serverside

### ISSUE THREAD

**Issue by vegarringdal** [Wakanda/wakanda-issues#151]
@JegoYann 
@hamzahik 

```javascript
var x = () => {
	return new Promise((resolve, reject) => {
		console.log("inside promise")
		setTimeout(()=>{
			console.log("timeout")
			resolve("done");
			
		},3000)
	})
}


x().then((result)=>{
	console.log(result);
	exitWait()
}).catch((err)=>{
	console.log(result);
	exitWait()
});
console.log("waiting")
wait();
console.log("done")

```

This results in:
* [Backend] inside promise
* [Backend] waiting
* [Backend] timeout

promise is never resolved

will async and await work in beta 2?
Tried to do that byt failed when it saw ```async``` function...

```
var dummyFunction = () => {
	return new Promise((resolve, reject) => {
		console.log("inside promise")
		setTimeout(()=>{
			console.log("timeout")
			resolve("done");
			
		},3000)
	})
}


var testAsync = async ()=>{
	let result = await dummyFunction();
	console.log(result);
	exitWait();
}


console.log("waiting")
wait();
console.log("done")

```

message:
"Unexpected token (, line #18, file:///C:/Users/vegar/Documents/Wakanda/solutions/BugTest/BugTest/backend/query.js."
componentSignature:
"jvsc"
errCode:
4055
message:
"Error evaluating javascript file:///C:/Users/vegar/Documents/Wakanda/solutions/BugTest/BugTest/backend/query.js"
componentSignature:
"JS4D"
errCode:
2

**Comment by hamzahik** [comment]
@vegarringdal Promises are only supported inside NodeWorkers. Wakanda HTTP Threads have a synchronous behavior.

To have NodeJS 6.9 LTS equivalent APIs you'll need to wait for the release (maybe the next beta will have it too).

**Comment by vegarringdal** [comment]
Ok, I though it might work since I used wait.

Would be great if you guys created a list of what will work on server thread etc in the docs when you release 2.0
