### ISSUE TITLE
Wakanda-Enterprise-Server Linux

### ISSUE THREAD

**Issue by northernfrontier** [Wakanda/wakanda-issues#152]
I am looking for the latest installation instructions or notes for wakanda-enterprise-server_1.1.3_amd64.deb.   It appears this version has some new or improved support for systemd for launching the server and solutions.  Xiang Liu suggested I post here for the Engineering team..

**Comment by hamzahik** [comment]
Hi @northernfrontier,

This is a draft of the new documentation (not validated yet) but it gives more info about configuring the Wakanda Service on Ubuntu Server : https://jegoyann.github.io/wakanda-server-doc/#/doc/administration

If you have questions or feature requests we would love to have your feedback !

**Comment by JegoYann** [comment]
Wakanda `v2.6.0` now integrates `systemd`.
Do not hesitate to reopen if something's wrong.
