### ISSUE TITLE
Studio git panel

### ISSUE THREAD

**Issue by idrissisimo** [Wakanda/wakanda-issues#16]
The git panel design on the Studio needs some review 

![git](https://cloud.githubusercontent.com/assets/16193194/11683153/6365b56a-9e69-11e5-873f-7c45d013c0ae.png)

OS : Windows 10

**Comment by hamzahik** [comment]
Fixed in https://github.com/Wakanda/wakanda-digital-app-factory/releases/tag/1.0.2
