### ISSUE TITLE
Beta 2.0.0.b :webviews redraw issues on Microsoft Surface Book, also vmware and win10

### ISSUE THREAD

**Issue by vegarringdal** [Wakanda/wakanda-issues#160]
@hamzahik
This is also a issue on my vmware and windows 10
Really frustrating bug

![image](https://cloud.githubusercontent.com/assets/2901416/23962757/6a7f1622-09af-11e7-8b38-ec19d7f2a0f3.png)

**Comment by vegarringdal** [comment]
This is imporved a lot on beta 24.03.2017:

Its very laggy, but now it will atleast manage to clean up by it self
But I would try and improve on this

Video:
https://drive.google.com/open?id=0B_wM5SJf8IXodllWNGtHOEhmejg

**Comment by hamzahik** [comment]
@vegarringdal yes indeed it improved a lot but we still need to make it better. We will try to fix this before the official release, worst case scenario : we release the 2.0 by the end of last week and work on a fix for this problem for a 2.0.1 release.
