### ISSUE TITLE
wakanda 2.0.0beta and page prototypes

### ISSUE THREAD

**Issue by alcada** [Wakanda/wakanda-issues#161]
Hi
I try Wakanda Studio 2.0.0beta b (17Mar2017) and I can't open page prototypes from my Wakanda v11 1.1.4 solutions.
Did Wakanda v11 2.0.0 definitively kill the prototyper (studio web page designer window and custom, v1 and v2 widgets) ?????

Regards
alcada

**Comment by hamzahik** [comment]
Hi,

Yes the 2.0 removes the prototyper from the studio.

Regards,
Hamza
