### ISSUE TITLE
ISO data format in model

### ISSUE THREAD

**Issue by chriscurnow** [Wakanda/wakanda-issues#162]
Maybe this is just me and something I have done in my setup somewhere.

However, I have long had a problem with the date format in the data model.

By default I thought Wakanda would return dates from the datastore in ISO format. I am getting dates returned in simple format. It's not a big deal as it is easy to fix. I just have to add `{simpleDate:false}` to the attribute definition.

But it is annoying as I have to keep doing it when the docs say ISO format is the default.

As I say, it might just be me 😄

**Comment by fredGandelot** [comment]
Hello @chriscurnow ,

By default , date attributes are stored like ` YYYY-MM-DDTHH:MM:SSZ` (which corresponds to simpleDate = false )
If you want to only store 'YYYY-MM-DD' then you must check the box Date only (right property panel - this is  equivalent to simpleDate = true 
By doing this the value HH:MM:SS  will be set to 0

**Comment by chriscurnow** [comment]
@fredGandelot this is the problem.

Date attributes are indeed stored in ISO format – as I want them to be.

The problem is when I go to access the data – in my case using REST.

By default, Wakanda returns a simple date.

I never use the model designer, rather I always use the Model API.

In this case I have to add {simpleDate:false} to every date definition. Otherwise it returns a simple date. Wakanda should return date in ISO format by default.

**Comment by fredGandelot** [comment]
@chriscurnow ,

Thanks for details. I found the issue. 
The problem does not occur using the Model Designer (by adding a Date attribute, it automatically add in the Json file a dataSimple = false . So the issue do not appear either on the backend and via the REST api which deliver the correct format)

But indeed when declaring  your model via the Model API by default the simpleDate value is set as True which is a problem.
Thanks for reporting it 👍

**Comment by chriscurnow** [comment]
@fredGandelot, you're welcome and thanks for getting back to me. 

I am surprised it hasn't been reported earlier. That's why I thought it must be something I was doing. As I said, it's not a huge problem. Just something you have to remember to do whenever you define a date attribute. 😄 

As an aside, does anyone still use the Model Designer? 😄

**Comment by fredGandelot** [comment]
@chriscurnow  It's fixed  and integrated V2
