### ISSUE TITLE
Support for MonogDB in future versions?

### ISSUE THREAD

**Issue by amandeepmittal** [Wakanda/wakanda-issues#166]
Can we expect to see a database explorer and other features for MongoDB in future release(s)?

**Comment by hamzahik** [comment]
@amandeepmittal the next major release brings support of NodeJS code through the NodeWorker API, it is possible to connect to MongoDB by a NodeJS driver.

You can find an example at : https://github.com/JegoYann/wakex-node-worker
And you can download the pre-release of the 2.0 version at : https://github.com/Wakanda/wakanda-digital-app-factory/releases/tag/v2.0.0.b

**Comment by amandeepmittal** [comment]
@hamzahik Thank you. I'm very exited to use Wakanda with my development stack and will be checking v2.0.0

**Comment by hamzahik** [comment]
V2.0 available for download.
You can read about how to use the NodeWorker API at https://wakanda.github.io/doc/#/guide?section=main-workers-node
At the bottom of the page, there is a link to a github repository with a complete example of usage of mongodb in wakanda.

**Comment by amandeepmittal** [comment]
@hamzahikThanks!
