### ISSUE TITLE
Beta 2.0(beta from 24.03.2016), weird bootstrap bug

### ISSUE THREAD

**Issue by vegarringdal** [Wakanda/wakanda-issues#167]
@hamzahik @fredGandelot 

Samle solution (beta from 24.03.2016)
https://github.com/vegarringdal/aurelia-v-grid-and-wak--fuse-setup/tree/master/Sample-Solution

The solution fails to be started from studio if this line: 

https://github.com/vegarringdal/aurelia-v-grid-and-wak--fuse-setup/blob/master/Sample-Solution/backend/bootstrap.js#L6

Is not moved down here: (before the foreach)

https://github.com/vegarringdal/aurelia-v-grid-and-wak--fuse-setup/blob/master/Sample-Solution/backend/bootstrap.js#L13

What is the reason for this?

Error if I click debug when server fails...

![image](https://cloud.githubusercontent.com/assets/2901416/24309251/65518e5a-10cb-11e7-9707-453d9dea22e3.png)

Unhandled exception at 0x00007FFDF63CB81E (node.dll) in wakanda-server.exe: 0xC0000005: Access violation reading location 0x0000000A00000027. occurred

**Comment by vegarringdal** [comment]
Ive been testing 10 times moving that line between top and line 13, every time it gets moved server starts like expected without quiting

**Comment by hamzahik** [comment]
thanks @vegarringdal for reporting this. It is nice to see that someone else reproduces this issue.

We recently discovered an issue when you use the combination : NodeWorker, bootstrap and debugger. We will keep you in the loop about this problem.

**Comment by JegoYann** [comment]
Hello @vegarringdal We are one your issue. It's a weird V8 garbage collector issue. We keep you informed.

**Comment by vegarringdal** [comment]
@JegoYann 
Great, hope you get all weird bugs away before the release 👍

**Comment by JegoYann** [comment]
Hello @vegarringdal , After some really deep search, it was an issue with the NodeJS 6 garbage collector. It's fixed with NodeJS 8 included in Wakanda v2.2.0.
Please send us your feedback.
