### ISSUE TITLE
getUserSessions() - expiration iso time wrong

### ISSUE THREAD

**Issue by InfoAdgrade** [Wakanda/wakanda-issues#168]
Since the change of the DayLight saving time (summer time), the 'expiration' of the sessions is wrong (getUserSessions()).
It happens when wakanda server is running on linux.
The problem persist also after a reboot.

I don't know that the problem is bigget than that (datetime in general, server side).

Thank you.

**Comment by JegoYann** [comment]
Hello @InfoAdgrade,
Does getUserSessions() returns a GMT time or your server local time ?
What time do you expect ?

Regards,
Yann

**Comment by InfoAdgrade** [comment]
Below the value of the "expiration" attibute of the UserSessions object.
Please, note:

- that the linux time is one hour ahead nevertheless I run getUserSessions() only 3 minutes before...
- the two machine (linux and mac) are setted with network time enabled
- all works fine until the Daylight saving time is coming into effect (26 march)

In my case, I use the expiration date/time into the admin page of my application, where I list the connections, the expiration date and so on...

linux;
  "expiration": "2017-03-27T**14**:18:18.028Z"
  
  macos:
  "expiration": "2017-03-27T**13**:21:30.542Z",

**Comment by JegoYann** [comment]
Hum, is using the OS local time and does not provide its own time counter.

So what is your OS local time (not through wakanda) ?
In your Mac and Linux shell, do a `$ date`.

**Comment by InfoAdgrade** [comment]
All seems to be right:
linux:
Lun 27 Mar 2017 15:07:17 CEST
macos:
Lun 27 Mar 2017 15:06:47 CEST

I can tell you that the linux is a virtual machine (hosted by a macos machine).
But also the host macos machine has the network time enabled and the "date" return the corret time.

I think you have to investigate the difference between the linux and the macos version of the getUserSessions() function or, in general, the way wakanda server retreives the time from the operating system.

Thank you.

**Comment by JegoYann** [comment]
Alright ! Thanks for your feedback. I will take a look on my ubuntu VM.

**Comment by InfoAdgrade** [comment]
For you information:

- it happens also in a pure linux machine
- the version of ubuntu I use is 16.04 LST

Best Regards.

**Comment by JegoYann** [comment]
We've done a fix and have now to QA and package it for a release.
Regards.

**Comment by AlessandroCasassa** [comment]
The problem still exists in wakanda v2.0.3.
Best regards.

**Comment by JegoYann** [comment]
Hello @AlessandroCasassa , release v2.2.0 fix this issue.
Please give us your feedback.
Regards
