### ISSUE TITLE
Windows x64 Installation Controller - Only shortcut is installed 

### ISSUE THREAD

**Issue by codexdev** [Wakanda/wakanda-issues#17]
I chose Custom Install to put on a different drive. I selected to install both Server & Studio and did get all three shortcuts, but Wakanda Controller shortcut doesn't link to an application and a search of the install folders came up with nothing.

![image](https://cloud.githubusercontent.com/assets/8992422/11693739/906494e0-9e74-11e5-8715-dda54d0195e2.png)

![image](https://cloud.githubusercontent.com/assets/8992422/11693763/af42f8f2-9e74-11e5-935b-4565651e575d.png)

**Comment by hamzahik** [comment]
Yes we reproduce the issue, we will fix it asap.
Thanks for the report

**Comment by hamzahik** [comment]
Fixed in https://github.com/Wakanda/wakanda-digital-app-factory/releases/tag/1.0.2
