### ISSUE TITLE
Wakanda Studio.exe error (0xc000007b)

### ISSUE THREAD

**Issue by steeu** [Wakanda/wakanda-issues#172]
Get the following error trying to start Wakanda Community Studio 2.0.0 on Windows 10 Enterprise. Server starts just fine.

![2017-04-05-error](https://cloud.githubusercontent.com/assets/3204827/24711414/2d0381f8-1a20-11e7-9952-539660a00875.png)

**Comment by issameljohri** [comment]
You just  need to install Microsoft Visual C++.

**Comment by hamzahik** [comment]
@issameljohri not really a solution but can be a work around, if the studio needs VC++ to run it means some dependencies needs to be added to the build.

**Comment by FrancoisMarchal** [comment]
Sorry we let the 32 bits MSVC dll in the studio folder (Wakanda studio is now 64 bits)
Here are the 64 bits dlls, just drop them in your Wakanda Studio folder to replace the 32 bits one. This will be fixed very soon on the download version!

[vccorlib120.zip](https://github.com/Wakanda/wakanda-issues/files/903173/vccorlib120.zip)

**Comment by hamzahik** [comment]
@steeu fixed in the 2.0.1 but since there is an issue with updating an already installed version, make sure to uninistall Wakanda 2.0.0 before installating the 2.0.1 we are working on a fix for this issue as well.

Thanks for the feedback 👍
