### ISSUE TITLE
How to migrate Model API v1 to v2

### ISSUE THREAD

**Issue by chriscurnow** [Wakanda/wakanda-issues#179]
I just tried converting a large v1 application to v2 following the migration guide. Everything seemed to work ok but I kept getting Error 404 - Not Found if I tried to do any REST calls to the application.

It worked fine if I created a new application from scratch.

It took me quite a while to work it out but the problem was the Model API.

Working with my freshly created application if I created a model.js file with one simple Class definition, REST would not recognise my new class. If I deleted the class I had created in the designer in Studio and tried rest I got the 404 error again.

So this is a bug somewhere.

As far as I can tell there is no documentation regarding the Model API in v2 or about converting the model API for use with v2.

I have more than 1000 lines of code in my model. I wouldn't want to have to go through it all and convert it manually – even if I could work out how to do that.

**Comment by JegoYann** [comment]
Hello @chriscurnow ,
Could you send us your application to check what is going on ?
Could you give us a small example that way we can reproduce your issue live ?

Regards

**Comment by chriscurnow** [comment]
OK, I've dome further research on this. It is not the model api per se that is causing the problem. I have been able to copy a small part of my model over with no problems so far.

There must be something in my model that is causing the problem. I will continue copying the model across until I find it.

I'll let you know what I find out.

**Comment by chriscurnow** [comment]
Well, this is one of those situations we all hate.

I just recreated my whole model in v2 by copying one model description file at a time into a brand new v2 solution. It is now working fine AFAICT??

I'll close this issue for now. If I find anything, I'll open it again.

**Comment by chriscurnow** [comment]
Just to let you know, I have found it virtually impossible to migrate from v1 to v2 using the migration instructions in the docs.

However I have found what seems to be a much easier and quite reliable method to migrate.

Simply create a new solution in v2 and copy all the relevant files from v1 solution to new solution.

It seems to work like a dream.
