### ISSUE TITLE
Theme does not work for new projects

### ISSUE THREAD

**Issue by swelshh** [Wakanda/wakanda-issues#18]
Build: 11.194922
OS: 10.10.4

Steps to reproduce:
1. Updated preferences to have Theme = Solarized light
2. Create a new solution/project
3. Create a js file and the theme is not applied

If you open prefs, the Solarized light theme will still be selected, but it just won't be in use for the solution/project.

**Comment by cedricss** [comment]
@swelshh Thanks for the report.

We tried the Build: 11.194922 on various situation and on different platforms (Windows, Yosemite, El Captain). And we do not reproduce this.

- Is it only with the Solarized light theme?
- Is it updating the theme _before_ loading a solution?
- Is it only switching from a opened from solution to a new created one?

Thanks for details!

**Comment by swelshh** [comment]
Hey @cedricss, thanks for checking it out.  I can't reproduce the problem now either.  I had a few different older dev versions of Wak11 installed where I had set the theme, I'm guessing it was a case of older pref files messing things up.
