### ISSUE TITLE
Can't restart server in v2.

### ISSUE THREAD

**Issue by chriscurnow** [Wakanda/wakanda-issues#180]
I think this has been discussed on gitter but as far as I can tell it's not reported here.

However once you start server in v2 Studio, you can't stop it.

You have to close and reopen the solution and then restart it.

**Comment by JegoYann** [comment]
Hello @chriscurnow ,
When you click `run` button in the toolbar, a `tasks` tab opens and displays all running process with Server inside. You can close the server using the cross `x` icon next to it.

**Comment by chriscurnow** [comment]
OK, thanks. Perhaps you need to make that a little clearer. Especially for those of us migrating from v1.
We are used to the 'Start Server' button changing to 'Stop Server'. I didn't notice the cross – partly because I have the Studio window displaying across the whole of one of my screens. That meant the cross was a long way from the 'Wakanda Server is running' label.
