### ISSUE TITLE
Can't use uuid as key

### ISSUE THREAD

**Issue by chriscurnow** [Wakanda/wakanda-issues#181]
When I generate a new class it defaults to type 'long'.

I want to use type 'uuid' for my keys. I can't find a way to change the default.

Also there seems to be no way to change the type of the key from the Design mode.

If I switch to Source I can change the type to UUID and delete the "auto sequence" property.

But I can't save a new entity to the class.

Here is my code:

`var newEntity = ds.newClass.createEntity`
`newEntity.id = generateUUID // id is generated correctly`
`newEntity.save()`

This fails on the last line with the message

`The new entity of the "newClass" datastore class cannot be saved`

If I change the id back to type long everything works fine.

**Comment by fredGandelot** [comment]
Hi @chriscurnow ,

Indeed you cannot change the type by just editing the type visually, however there is a lot of way to do it : 
-  First on your Model Designer, add a field called ID2, set it as a UUID, click on the "Key" icon .
(this way the key is moved from "ID, long" to " ID2, uuid" ) If you want , you can then remove the previous ID field
- Or you can use the model API to modify the ID type (on your model.js file write : ```model.DataClass6.ID.type = "uuid";```
- 3rd method => **Not advised** but you can simply edit the json source file and replace the "type": "long", with ""type": "uuid"

When done, just code :
````
var b = new ds.DataClass5();
b.ID = generateUUID();
b.save();
ds.DataClass5.all();
````

Be sure, not have any data in your dataclass before doing it , if not, u 'll need to update the missing values before switching the key type
(of course u must reload the server after each modification executed on the model)

**Comment by chriscurnow** [comment]
Thanks @fredGandelot. 

Yes I can use any of these methods but it would be nice to have a setting somewhere where I could set the default id to UUID. I am sure this was available in v1.

I use the model API almost exclusively so it is not really an issue for me. But I thought I would try out the Model Designer in v2.

There is a feature request from me somewhere in here requesting the ability to edit the model API with the Model Designer. This would make take away a lot of trivial and repetitive typing in the model API.

Again though, nowhere near the top of my priorities.

**Comment by fredGandelot** [comment]
Actually @chriscurnow  you can do it visually, (i tested it on WAK 2.1 ) but as long u change the type, you must update your data before being able to update a new entity. But it does work (double click on the field then tab on keyboard..etc) And u can edit it. 
U need to remove the autosequence option.

But be careful when swithcing your key type your ID might be loss (reset to 0 , etc) So update your data before swiching
