### ISSUE TITLE
Can't stop server

### ISSUE THREAD

**Issue by chriscurnow** [Wakanda/wakanda-issues#182]
I am not sure of the exact sequence of events sorry.

The best I can say is that I was making changes to the model.

I clicked "Reload" and the red mark on this button went away.

However the yellow writing at the bottom of the screen 

"Model files changed. The model needs to be reloaded on the server" remained.

I tried clicking the small cross to stop the server, but nothing happened. The server kept running – or at least said it was still running.

**Comment by hamzahik** [comment]
@chriscurnow are you using the latest version ? the 2.0.3 ? if you are still experiencing this problem we can look into it.

**Comment by chriscurnow** [comment]
Yes, I am using 2.0.3. It's not a big problem. It only happens sometimes. But it does still happen. I had it this morning. I wouldn't spend a lot of time on it your end. If I can find something common about what the circumstances in which it happens, I will let you know.

**Comment by hamzahik** [comment]
@chriscurnow We changed the way we handle server shutdown especially in the enterprise version for the 2.1.0 release. If you still experience the same problem please re-open the github issue.
