### ISSUE TITLE
Dialog locked up trying to create a new solution

### ISSUE THREAD

**Issue by chriscurnow** [Wakanda/wakanda-issues#184]
Just trying to create a new solution.

Not sure if it is relevant but just after the dialog for a new solution opened I switched to Safari briefly and then back again.

After this, the dialog would not respond to any clicks.

I had to force quit Wakanda.

**Comment by hamzahik** [comment]
@chriscurnow this was normally fixed but let me check if it was shipped in the 2.0.3 or will be available in the 2.1.0

**Comment by seeps001** [comment]
I have the same issue with 2.0.3

**Comment by seeps001** [comment]
@hamzahik  any update on this issue? Will it be fixed with 2.1.0? When will that be released. BTW I even downloaded 2.0.2 for Mac and had the same issue with the dialog locking up.

**Comment by hamzahik** [comment]
@seeps001 @chriscurnow the 2.1.0 was just released and adds more protection to avoid this kind of issues. I will close the issue for now and please open it if you encounter the problem once more.
