### ISSUE TITLE
/rest/$catalog/$all -  classes with restrictions missing

### ISSUE THREAD

**Issue by ronpfi** [Wakanda/wakanda-issues#185]
If I have a restriction in a class permission (like 'read') this class is no longer listed when I call http://localhost:8081/rest/$catalog/$all

**Comment by fredGandelot** [comment]
Hi @ronpfi  ,

A old bug on the description permission has been fixed for V2 
Now, In addition to your 'read' rights , you must add a `describe` permission  to have the DataClass available in the catalog description)

**Comment by hamzahik** [comment]
@ronpfi in the 2.1.0 all DataClasses have the describe permission granted to everyone even if you block the read operation. This should make life easier for everyone.
