### ISSUE TITLE
Minor feature request: option to change comments color in editor

### ISSUE THREAD

**Issue by chriscurnow** [Wakanda/wakanda-issues#187]
I have looked everywhere I can think of but I can't find this anywhere in any of the settings.

It would be nice to be able to change the colour of comments in the code editor.

For me, comments should be quite unobtrusive. The current green does not achieve that.

**Comment by fredGandelot** [comment]
Hi @chriscurnow  ,

You can switch your `themes` and find something that fits your taste
![capture d ecran 2017-05-10 a 15 52 15](https://cloud.githubusercontent.com/assets/4920957/25902099/dbffb878-3598-11e7-8d76-ce9a951aadb5.png)


(Menu Bar >Wakanda Studio > Preferences > Code Editor > Theme)

**Comment by chriscurnow** [comment]
I knew as soon as I posted that, someone would tell me I was missing something obvious:(

Thanks for letting me know @hamzahik.
