### ISSUE TITLE
Add XMLHttpRequest timeout and ontimeout on server-side

### ISSUE THREAD

**Issue by Dupont-Matthieu** [Wakanda/wakanda-issues#189]
Hello,

I think it will be great to add the timeout property from XMLHttpRequest described here :
https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/timeout

In my case, I have to connect with a Single Sign On (SAML 2.0) server and it's important for my client to redirect someone if i can't reach it. So I need to timeout my request (I can't modify the SSO server).

Wakanda version : 1.1.4
Thanks ;)

**Comment by JegoYann** [comment]
Hello @Dupont-Matthieu , this is a great idea. We will put this feature request in the backlog.
Thanks.

**Comment by chriscurnow** [comment]
+1

**Comment by JegoYann** [comment]
Hello @Dupont-Matthieu, @chriscurnow ,
Wakanda Server v2.4.0 now has a `xhr.timeout` attribute.

Yann
