### ISSUE TITLE
Ionic 2 found by the console but not by Troubleshooting

### ISSUE THREAD

**Issue by cedricss** [Wakanda/wakanda-issues#192]
- install ionic with `npm install -g ionic` as suggested by the Troubleshooting app
- ionic 3.1.2 is installed (not ionic 2)
- restart the Studio
- the console does find "ionic 2"
- the troubleshooting app displays "missing" for ionic 2

Same issue when the more recent ionic 3.2.0 is installed

![image](https://cloud.githubusercontent.com/assets/802010/26635718/f3076786-461a-11e7-9fed-8e5710c1ea3a.png)
![image](https://cloud.githubusercontent.com/assets/802010/26635725/fc9540fc-461a-11e7-83af-b726351b41ee.png)
![image](https://cloud.githubusercontent.com/assets/802010/26635845/4ea759b6-461b-11e7-978f-33b3a088c0a7.png)

- Wakanda Studio 2.0.3
- macOS 10.12.4

**Comment by hamzahik** [comment]
@cedricss this should be fixed in the 2.1.0 if you still encounter the problem please open the issue once more.
