### ISSUE TITLE
Ionic 2 template is interrupted by a y/n question the user can't answer

### ISSUE THREAD

**Issue by cedricss** [Wakanda/wakanda-issues#193]
- Choose "ionic 2" template
- Run
- Open the tasks console after a few seconds:

![image](https://cloud.githubusercontent.com/assets/802010/26636135/182bbf34-461c-11e7-9357-c461d12849a2.png)

- Wakanda Studio 2.0.3
- macOS 10.12.4
- ionic 3.1.2 and ionic 3.2.0

**Comment by Ibtissama** [comment]
Hello Cedric,
This issue is fixed in the next release.

**Comment by CodelessFuture** [comment]
Wakanda Studio 2.0.3
macOS 10.12.5
ionic 3.3.0

Bypassed the problem installing by shell the package.
I succesfull RUN the Hello World in the Getting Started with preview, but Emulator fail for a Ionic Error

**Comment by hamzahik** [comment]
@cedricss @CodelessFuture the 2.1.0 was just released, you can now interact with the running command as if you were in the terminal.
