### ISSUE TITLE
Ionic 2 template fatal error

### ISSUE THREAD

**Issue by cedricss** [Wakanda/wakanda-issues#194]
If you manually answer "y" on https://github.com/Wakanda/wakanda-issues/issues/193 then you get this error:

![image](https://cloud.githubusercontent.com/assets/802010/26636307/a068cb80-461c-11e7-8dd8-ed4177bd19c9.png)

- Wakanda Studio 2.0.3
- macOS 10.12.4
- ionic 3.1.2

**Comment by hamzahik** [comment]
@cedricss this should be fixed in the 2.1.0 if you still encounter the problem please update Ionic globally, remove the node_modules folder then run you app again.
