### ISSUE TITLE
Ubuntu Server not starting

### ISSUE THREAD

**Issue by mattooren** [Wakanda/wakanda-issues#197]
Hi all,

I'm having issues starting a Wakanda Server on Ubuntu. When I try to start my solution I'm getting the following errors: 

wakanda[4115]: [wakanda.wakandaapplicaties.organisatiemonitor.POSX] error 13 Permission denied, task #4113, task name is Wakanda Enterprise Server
wakanda[4115]: [wakanda.wakandaapplicaties.organisatiemonitor.srvr] error 31 Failed to create a listening socket, task #4113, task name is Wakanda Enterprise Server

Anyone familiar with these errors / has an idea on how to solve them? 

Thanks in advance!

Kind regards,
Matthijs

**Comment by hamzahik** [comment]
Hi,

What port (s) are your project(s) listenning on ? 8081, 80, 443.. ?

How did you start wakanda server ?

**Comment by mattooren** [comment]
They're running on 8810 and 8811. I already changed them. 
I started the server as I always do: using sudo service wakanda start. Up until today this always worked.

**Comment by hamzahik** [comment]
Try to set recursively the access rights for the solution/projects folders to something similar to 7xx and change the owner recursively to those folders, the owner should be the user "wakanda".

**Comment by mattooren** [comment]
Thanks for the quick replies.
I tried to, but didn't change anything unfortunately

**Comment by mattooren** [comment]
Completely reinstalling the server did the trick. Still don't know why, but I'll close the issue. 

Thanks for your help!
