### ISSUE TITLE
Directory not found (dirNFErr)

### ISSUE THREAD

**Issue by chriscurnow** [Wakanda/wakanda-issues#199]
Trying to start Wakanda Server (v2.0.3) today and got this error 

"Directory not found (dirNFErr)".

I've got no idea where to go from here.

**Comment by hamzahik** [comment]
@chriscurnow no changes at all to your solution before this happened ?
if none, please remove the files "directory.WakTDef" and "directory.cacheUAG"

**Comment by chriscurnow** [comment]
@hamzahik hmmm, as far as I can tell there have been no changes to the solution. I have been working on something else for about a week and just came back to this one.

I also got some errors where it would not recognise an SSJS module in my class definitions. I has previously recognised this module. It's a very simple module. It just returns a constant I want to use a lot in my class methods.

So I went through and replaced the module reference by adding the constant directly to the class methods – just for the moment so I could run the project.

Anyway, sorry to say, removing those two files did not fix the problem 😞 

Thanks for jumping in so quickly though. Any other ideas?

**Comment by chriscurnow** [comment]
@hamzahik any further thoughts on this issue? I still can't start my server.

**Comment by chriscurnow** [comment]
@hamzahik – what do you know? I just resolved the issue. It had to do with another instance of Wakanda Server running. I have a v1 project and a v2 project I'm working on at the moment. Even though I had completely shut down my v1 project, it appears it did not shut down the server as it usually does. I had to go into Activity Monitor (Mac OSX) and force quit the server. Once I did that, everything was good 😄 

That's one to keep in mind for the future!!

Thanks again for your help. And thanks for all the work you are doing on Wakanda. It is a great product and you are going ahead in leaps and bounds now.
