### ISSUE TITLE
Wakanda and 4D version compatibility - roadmap

### ISSUE THREAD

**Issue by NAMSGithub** [Wakanda/wakanda-issues#202]
Hi,

I am the 4DMobile developer under a 4D Silver Partner licensing (Including 4DMobile license). We have built our webapp using WAF/widgets on the frontend and I understand WAF is gone with version 2.0.b and up. I have a few questions about adapting to the changing Wakanda/4DMobile environment:

1) What is the expected lifespan of Wakanda 1.1.x as far as compatibility with 4D? For example, will Wakanda v1.1.x work with future versions of 4D like v16, v17?

2) Are we already licensed for Wakanda 2.0.x with our 4DMobile license? We use Enterprise features such as `model.mergeOutsideCatalog()` to connect to the 4D Database so we need to obtain a license for 2.0.x. How can we do that?

3) Since we have to rebuild the front end of our web-app, what frameworks/tools might you recommend for longevity? I see that Angular 1.x is a popular choice and offers UI-Grid support and other features similar to WAF Widgets. is Angular 1.x a good choice for longevity?

I am trying to get a handle on how I can keep current with the future of Wakanda/4DMobile and would appreciate any advice you might have for me.

Thank you,
Ryan

**Comment by hamzahik** [comment]
Hi Ryan,

I'll try to answer your requestions one by one:

> What is the expected lifespan of Wakanda 1.1.x as far as compatibility with 4D? For example, will Wakanda v1.1.x work with future versions of 4D like v16, v17?

We will continue fixing critical bugs on the 1.1.x Server release until January 2018 as long as the migration for the client on a 2.x.x release is not easier than fixing the bug on a 1.1.x

> Are we already licensed for Wakanda 2.0.x with our 4DMobile license? We use Enterprise features such as model.mergeOutsideCatalog() to connect to the 4D Database so we need to obtain a license for 2.0.x. How can we do that?

Yes, if you have a license for 4D Mobile you automatically get a license for Wakanda that enable the Wakanda/4D connector. If your project needs more features(Backend scalability, MySQL, ODBC, Oracle connectors..) you can discuss that with 4D sales.

> Since we have to rebuild the front end of our web-app, what frameworks/tools might you recommend for longevity? I see that Angular 1.x is a popular choice and offers UI-Grid support and other features similar to WAF Widgets. is Angular 1.x a good choice for longevity?

It really depends on your project. If you can contact me on hamza.hikmat@wakanda.io, give me more details about your project, maybe few screenshots and what would be your future needs, I'll be happy to help.

Hamza

**Comment by NAMSGithub** [comment]
Hi Hamza,

Thank you for getting back to me and making yourself available for help. I am going to meet with my boss and catch him up with this information and get a good understanding of the future plan for our webapp and then reach out to you for advice on how to proceed.

Ryan
