### ISSUE TITLE
Minor Issue: remove formatting for server error response.

### ISSUE THREAD

**Issue by chriscurnow** [Wakanda/wakanda-issues#203]
At the moment if we get an unhandled error on the server we get a response that looks something like this:

`<!--↵* This file is part of Wakanda software, licensed by 4D under↵*  (i) the GNU General Public License version 3 (GNU GPL v3), or↵*  (ii) the Affero General Public License version 3 (AGPL v3) or↵*  (iii) a commercial license.↵* This file remains the exclusive property of 4D and/or its licensors↵* and is protected by national and international legislations.↵* In any event, Licensee's compliance with the terms and conditions↵* of the applicable license constitutes a prerequisite to any use of this file.↵* Except as otherwise expressly stated in the applicable license,↵* such license does not include any other license or rights on this file,↵* 4D's and/or its licensors' trademarks and/or other proprietary rights.↵* Consequently, no title, copyright or other proprietary rights↵* other than those specified in the applicable license is granted.↵-->↵<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">↵<html xmlns="http://www.w3.org/1999/xhtml">↵<head>↵<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">↵<title>500 - Internal Server Error</title>↵<style>↵	body { margin: 0px; padding: 0px; font: 90% "Lucida Grande", Lucida, Verdana, sans-serif; }↵	div#title { background-color: #2c4b79; padding: 15px 15px 15px 20px; margin: 0px; }↵	div#message { padding: 20px; }↵	div#details { padding: 10px; }↵	h2 { color: #fff; font-size: 1.3em; margin: 0; padding: 0; }↵	p { padding: 0px; margin: 0px; }↵</style>↵</head>↵<body>↵<div id="title">↵<h2>500 - Internal Server Error</h2>↵</div>↵<div id="message">↵<p>Illegal return statement<br />login<br />Component 'iasv' throw an error: 1033<br /></p>↵</div>↵<div id="details">↵<code></code>↵</div>↵</body>↵</html>↵"`

Since we will almost always be using a framework to retrieve data from Wakanda Server, most of this is redundant. In this case, all we need is:

`500 - Internal Server Error
Illegal return statement
Component 'iasv' throw an error: 1033`

**Comment by JegoYann** [comment]
Hello @chriscurnow ,
Wakanda Server v2.4.0 now handles HTTP `Accept` headers for its error response format.

Yann
