### ISSUE TITLE
Unable to create backend project in the "Getting started" tutorial (v2.1)

### ISSUE THREAD

**Issue by hemure** [Wakanda/wakanda-issues#204]
Hi

Following the getting started tutorial on this page: 
https://wakanda.github.io/get-started/populate-database.html

and using v2.1 of the communtity IDE, I get this error when trying to add a backend project to the solution:

"Problem of evaluation of file "C:\ .... \wakanda-extension-templates\index.js.
The project file '' could not be opened on line 312."

Please let me know when I'm able to try out the db backend features of wakanda. Thanks.

Cordialement,
Henrik Molke Rediin

**Comment by hamzahik** [comment]
Hi @hemure ,

There was an issue in the 2.1.0 package, can you please do the following:
- Uninstall Wakanda 2.1.0 from your PC
- Download the Wakanda 2.1.0 installer once more from the website https://wakanda.github.io/
- Install it
- Make sure that your folder : documents/Wakanda/Extensions/ is empty

Let me know if this fixes your problem. 

Regards,

**Comment by hemure** [comment]
Hi Hamzahik

Thank you for the fast answer.

I've done as instructed (uninstall-restart-install), and ensured the
extensions folder was empty.
But I still get the same error, when trying to add the backend project to
the solution:
[image: Inline image 1]

This message displays very soon (<1 sec) after clicking 'Create' in the
'New project' dialog.
And my solution file structure looks like this after:

[image: Inline image 2]


Some more info on my setup:
Surface Book with Windows 10 including latest updates.

Just let me know when you want me to try again, or if you need some other
info or testing from me.
I'm eager to try out Wakanda, and in no hurry :-)


KR,
Henrik Molke Rediin

**Comment by hamzahik** [comment]
Hi @hemure ,

We find out the origin of the problem and fixed it. Please do the following : 
- Uninstall Wakanda from your PC
- Download the Wakanda installer once more from the website https://wakanda.github.io/
- Install it

This time the issue should be fixed for real :)

Regards,

**Comment by hemure** [comment]
Hi Hamzahik.

Yep, it's working.
Thanks :-)

Regards.
