### ISSUE TITLE
Can't connect 4D database in 2.1.0 enterprise

### ISSUE THREAD

**Issue by NAMSGithub** [Wakanda/wakanda-issues#205]
I added the below to models/main/model.js and get the below error. Any thoughts? The 4DMobile documentation is outdated. License key is installed at ~/Documents/license/license.key

` model.mergeOutsideCatalog('4DDB',{
	hostname: '192.168.168.105:8088',
	user: 'username',
	password: 'pass',
	jsFile: '4DDB.js',
	timeout: 1
});`

Error message:

`model.js : '' is not a function (evaluating 'model.mergeOutsideCatalog') - line 6`

**Comment by hamzahik** [comment]
Try following the doc on this page :
https://wakanda.github.io/doc/#/guide?section=main-data-external
You don't need to use code to add your 4d catalog.

Let me know if this solves the issue.

Hamza

**Comment by NAMSGithub** [comment]
Thank you Hamza that worked.

**Comment by hamzahik** [comment]
you're welcome
