### ISSUE TITLE
Admin app in Community Studio 2.1.0 not working

### ISSUE THREAD

**Issue by hemure** [Wakanda/wakanda-issues#207]
HI
The admin app in my newly downloaded Wakanda Studio 2.1.0  #Community is not working (I think).
Symptoms:
The index.html file in the projects web folder is empty.
With the server running and browsing to http://localhost:8080, a blank page is displayed.
(I know the server i responding because I get the wakanda favicon).

**Comment by hamzahik** [comment]
Hi,

The community version has no admin dashboard. You can get more details about this at https://gitter.im/wakandasoft/Lobby?at=5995579d210ac2692091088a

**Comment by hemure** [comment]
Hi
Thanks for clarifying.
