### ISSUE TITLE
Not enough detail in studio opening model error

### ISSUE THREAD

**Issue by chriscurnow** [Wakanda/wakanda-issues#209]
Just another one for the backlog. Not urgent but you might like to know about it if you don't already.
See this screenshot.
It shows there are errors but really gives no indication what is causing them.
![wakanda ss](https://user-images.githubusercontent.com/2943047/29596830-49ec798c-8802-11e7-8e6b-f5158907bc84.png)

v 2.0.3

**Comment by hamzahik** [comment]
@chriscurnow did you figure out what the problem was ? this will help us narrow down what types of errors are not correctly reported.

Thanks

**Comment by chriscurnow** [comment]
@hamzahik I didn't figure out the problem. I wish I could. It just went away for a while.
I'll keep working on it. 
I've seen this before and I'm pretty sure it has something to do with "relatedEntities" (ie the reverse relation to "relatedEntity".)
However, today I finally got to download 2.1. The problem is worse now. When this dialog comes up, I click OK, but it immediately re-appears. The only way out is to force quite 😞 .
I'll let you know here as soon as I have found out more.

**Comment by chriscurnow** [comment]
How can I send you something privately? My database structure is proprietary and I don't want to post it in a public place like here.

**Comment by hamzahik** [comment]
@chriscurnow you can contact me by email: hamza.hikmat@wakanda.io

**Comment by chriscurnow** [comment]
@hamzahik It's ok. I have found out what the issue was.
The dialog appears when there is something wrong with either a "relatedEntity" definition or a "relatedEntities" definition.
BTW, I am using the model API.
I have just been through all my model definition files very carefully and found where there were errors.
The strange thing was that my model has been working without any issues – even with the errors.
It was just when I added one more related entity definition, it suddenly showed up all the other errors.
That was why I couldn't work out what was going on.
The other hint was that although all my classes were available to me through REST, only some of them showed up in the model designer.
You can get the error dialog to show up pretty easily with a simple model. Just define a related entity to class that doesn't exist.
