### ISSUE TITLE
[2.1] Cannot stop server after start error.

### ISSUE THREAD

**Issue by chriscurnow** [Wakanda/wakanda-issues#210]
This has happened a couple of times today.
I get an error on attempting to start the server. 
However, in the Tasks tab, it shows server is still running while the status bar shows "Server is now disconnected".
<img width="826" alt="server status" src="https://user-images.githubusercontent.com/2943047/29695563-07180cda-8987-11e7-89ea-264dc5f79382.png">
None of this would be much of a problem except clicking the "x" on the "Running Wakanda Server" line has no affect and clicking "Run" doesn't do anything.
From this situation I have to quit both server and studio and restart them both.

Here is an example of the error message I'm getting at startup. 
<img width="590" alt="server start error" src="https://user-images.githubusercontent.com/2943047/29696055-ba0e22aa-8989-11e7-8c34-c70f3a58679e.png">
Once again, not much useful information in the error 😄 I'm not complaining about that, but it would be nice if you could have a look at these error messages at some stage.

**Comment by hamzahik** [comment]
I think this is the same as #212 
We will see why the variables in the template message were not replaced :)

Thanks for the feedback.
