### ISSUE TITLE
[2.1] Studio gets really confused when server crashes

### ISSUE THREAD

**Issue by chriscurnow** [Wakanda/wakanda-issues#212]
Not really a big issue as it only relates to studio. However, I have been testing some complex code recently and there are circumstances where an error in the code causes the server to crash.

Ok, that bit is my problem.

However, in this situation I have found that Studio reports "Server disconnected", but under the 'Tasks' tab is says the server is running.

I can't stop server from here and I can't start it again.

It seems I have to quit studio altogether (upon which it invariable says "Studio quit unexpectedly"), restart the server, restart studio, open my solution and then 'Run' it.

A bit of a hassle but not urgent.

**Comment by hamzahik** [comment]
@chriscurnow yes we can reproduce the issue. We are working on it. 
There will be a 2.2.0 release today or monday. So we will try to deliver this fix for the 2.2.1 by the end of the week if eveything goes fine.

**Comment by JegoYann** [comment]
@chriscurnow Release v2.2.1 that fixes your issue is out. Could you tell use if all is ok for you now ?
https://github.com/Wakanda/wakanda-digital-app-factory/releases/tag/v2.2.1

**Comment by chriscurnow** [comment]
@JegoYann sorry for not getting back to you on this earlier. I installed 2.2.1 yesterday. Now I have to remember how to do something that will make the server crash 😄

**Comment by chriscurnow** [comment]
Just to let you know this is still an issue. It may not be that the server has crashed. It is more likely when the server hangs. That is, it is still running but not responding. Or it can happen when I try to shut down the server from Studio but it doesn't shut it down. I go to Activity Monitor and force quit server but Studio doesn't recognise the server is no longer there.

**Comment by maximaexchen** [comment]
I also have this issue!
Wakanda 2.7.0 on Mac Mojave
