### ISSUE TITLE
[2.1] Hard to restart server service after crash

### ISSUE THREAD

**Issue by chriscurnow** [Wakanda/wakanda-issues#213]
I'm running 2.1 server on a Debian installation – which I believe is the recommended/supported Linux distribution.

The problem is similar to other problems I have reported recently after a server crash. All this only happens in development so it is not production critical.

However, after the server has crashed I'm finding I have to issue the following sequence of commands:

`sudo service wakanda stop
sudo service wakanda start
sudo service wakanda stop
sudo service wakanda start`

A little bit annoying but not critical for production.

**Comment by hamzahik** [comment]
@chriscurnow Thanks for reporting this.
I think I know what the origin of the issue is. I think the pid file is not removed when the server crashes.

I'll try to reproduce this problem and get back to you.
