### ISSUE TITLE
can't open the Wakanda Server Administration page

### ISSUE THREAD

**Issue by btoorenburg** [Wakanda/wakanda-issues#217]
After installing Wakanda Enterprise server version 2.2.1 on Ubuntu 16.04 LTS we can't open the Wakanda Server Administration page for starting a solution. Ports 4433 and 8080 have been enabled on the Ubuntu server. The page shows the Wakanda icon in the tab but the page stays blank.

**Comment by hamzahik** [comment]
@btoorenburg can you post the full URL you are using to access the administration page ?

**Comment by btoorenburg** [comment]
Dear Hamzahik, 


We would like an on premise license for a Wakanda Enterprise Server for Linux. 
Our application is pretty much ready for production but we would like to do a last test with a trial server licence. 


It seems the problem is the exact location of the trial licence for Wakanda Enterprise Server on Linux. 


Our application is developed with Angular 2.0 and NodeJS. 
As a websecure proxy we are using Nginx. 
 
Would like like do another test, but we would also like to order a commercial licence for one Linux server. 


https://10.10.1.18:4433/index.html

It would be nice if you could help us with this.
If you want more information you can call me directly.  

With kind regards, 


Bas









www.timbv.nl
toorenburgsj@timbv.nl
Powered by:  www.zorgserviceprovider.nl



Drs. ing. S.J. Toorenburg
De Kwartel 5
8251 MS DRONTEN


Mobile            +31 6 270 703 15



 Van:   hamzahik <notifications@github.com> 
 Aan:   Wakanda/wakanda-issues <wakanda-issues@noreply.github.com> 
 Cc:   Bas Toorenburg <toorenburgsj@timbv.nl>, Mention <mention@noreply.github.com> 
 Verzonden:   10-10-2017 10:49 
 Onderwerp:   Re: [Wakanda/wakanda-issues] can't open the Wakanda Server Administration page (#217) 


@btoorenburg can you post the full URL you are using to access the administration page ? 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread. 
 
       

Met vriendelijke groet, 
Bas Toorenburg



www.timbv.nl
toorenburgsj@timbv.nl

Drs. ing. SJ Toorenburg
De Kwartel 5
8251 MS DRONTEN
Telefoonnr    +31 321 382 816
Mobiel    + 31 6 270 703 15

  http://twitter.com/#!/bastoorenburg

 http://nl.linkedin.com/pub/bas-toorenburg/a/60/243

E-mail disclaimer:
_______________________________________________________________________________________________________

Dit e-mailbericht en enige bijlage is uitsluitend bestemd voor de geadresseerde(n) en strikt vertrouwelijk of anderszins wettelijk beschermd. In dit bericht vervatte opvattingen of meningen zijn uitsluitend die van de schrijver en niet per definitie die van TIM Bedrijfskundig Advies. Als dit bericht niet voor u bestemd is, wordt u vriendelijk verzocht dit aan de afzender te melden. Alleen de geadresseerde mag de informatie gebruiken. Het is niet toegestaan om de informatie openbaar te maken, te vermenigvuldigen, te verspreiden of te verstrekken aan derden.

TIM Bedrijfskundig Advies spant zich ervoor in dat u juiste, volledige en tijdige informatie ontvangt.
TIM Bedrijfskundig Advies kan op geen enkele wijze verantwoordelijk of aansprakelijk worden gehouden voor en/of in verband met de gevolgen van en/of schade ontstaan door het onjuist, onvolledig en/of niet-tijdig versturen en ontvangen van de inhoud van dit bericht. TIM Bedrijfskundig Advies is niet aansprakelijk voor virussen in dit e-mailbericht en/of enige bijlage.

Voor informatie over TIM Bedrijfskundig Advies raadpleegt u www.timbv.nl
_______________________________________________________________________________________________________

**Comment by hamzahik** [comment]
@btoorenburg You'll be contacted by Ricardo in order to help you with anything you need.

Best regards,

Hamza
