### ISSUE TITLE
[2.2.0][Bug] "/rest" missing in URL used by image upload()

### ISSUE THREAD

**Issue by liuxiang625** [Wakanda/wakanda-issues#218]
This issue is firstly reported in this StackOverflow post: https://stackoverflow.com/questions/46476978/uploading-an-image-for-an-entity-attribute-in-wakanda-server

**Versions used**: 2.2.0 Enterprise 
**OS**: Mac OS

**Steps to reproduce:**

1. Create a new solution in 2.2.0.
2. Following the docs of [upload()](https://wakanda.github.io/doc/#/guide?section=main-data-cs-upload) and implement an upload input element and a button to call upload().
3. Run Solution & app. 
4. In the app, choose an image to upload and click "Upload"

**Expected behavior:**
The image will be uploaded to database.

**Actual behavior:**
Receive a 404 error: Failed to load resource: the server responded 
Cannot POST /Employee(12)/profilePicture:  http://localhost:4201/Employee(12)/profilePicture?$rawPict=image/png
![screen shot 2017-10-12 at 4 17 36 pm](https://user-images.githubusercontent.com/1305420/31523533-ecb7eba0-af68-11e7-821c-f34ebdf2112d.png)

**Preliminary analysis:**
The URL is missing "/rest" between port number and dataclass name. The URL to send the POST request is generated by MediaBaseService._buildUri at line 3454 of "wakanda-client.no-primise.js" in web/node_modules/wakanda-client:
```
MediaBaseService._buildUri = function (dataClassName, entityKey, attributeName) {
        return '/' + dataClassName + '(' + entityKey + ')' + '/' + attributeName;
};
```

Adding "/rest" to the beginning of the return seems to fix the issue:
```
MediaBaseService._buildUri = function (dataClassName, entityKey, attributeName) {
        return '/rest/' + dataClassName + '(' + entityKey + ')' + '/' + attributeName;
};
```
This proves is is likely a bug where the "/rest" is missing in the URL. There might be other more appropirate fixes.
![screen shot 2017-10-12 at 1 24 40 pm](https://user-images.githubusercontent.com/1305420/31523539-f433a068-af68-11e7-806b-bf921d6f00f9.png)

Sample Test solution attached.

[ImageUpload.zip](https://github.com/Wakanda/wakanda-issues/files/1380972/ImageUpload.zip)

**Comment by hamzahik** [comment]
Fixed
