### ISSUE TITLE
Web Component is reopened in HTML editor instead of Prototyper (GUI designer)

### ISSUE THREAD

**Issue by liuxiang625** [Wakanda/wakanda-issues#22]
Wakanda Studio can not open Web Component in GUI designer after save and close.

Steps to reproduce:

1. Create a new Web Component under web/prototype.
2. Save and Close.
3. Double click to reopen the component.

Expected result:
Web Component will be reopened in prototyper (GUI designer)

Actual result:
Web Component is opened in HTML editor and there is no way to switch to prototyper.

Tested reproducible in  Wak 11.194922 and Wak 11.195328 in Mac 10.9.5 and Windows 7.

![screen shot](https://cloud.githubusercontent.com/assets/1305420/12178711/be4e3cd4-b527-11e5-986a-cc48e4df5301.png)

**Comment by cedricss** [comment]
@liuxiang625

- Double click on `test.waComponent` to open the component with the Prototyper:
![screen shot 2016-01-15 at 16 58 28](https://cloud.githubusercontent.com/assets/802010/12357622/3c4c60ca-bba9-11e5-9eab-cdc1fa3d2827.png)

- Double click on a file _inside_ `test.waComponent` to edit the source code.

**NOTE**: you can't open a component in the prototyper _and_ edit its html source at the same time. Close the html source file before opening the component with the prototyper.
