### ISSUE TITLE
Server update overwrites config

### ISSUE THREAD

**Issue by chriscurnow** [Wakanda/wakanda-issues#220]
I just updated my remote Linux server to 2.2.1. 

I found that it overwrote the config file at /etc/default/wakanda.

**Comment by liuxiang625** [comment]
I believe this is standard behavior if you use the installer. The deb package will replace all required files using its content. I would recommend backup this file before updating Wakanda Server.

This could be a feature request for adding an option to update Wakanda on Linux while keeping configurations.

**Comment by hamzahik** [comment]
We will consider this as a bug and enhance our install scripts on the next releases to avoid this problem.
