### ISSUE TITLE
[2.2.1][Bug] addRemoteStore() returns error "datastore's type wakanda is not available"

### ISSUE THREAD

**Issue by liuxiang625** [Wakanda/wakanda-issues#221]
This issue is firstly reported in this StackOverflow post: [https://stackoverflow.com/questions/47011257/new-parameter-on-addremotestore-datastores-type](https://stackoverflow.com/questions/46476978/uploading-an-image-for-an-entity-attribute-in-wakanda-server)

**Versions used**: 2.2.1 Enterprise
**OS**: Mac OS X

**Steps to reproduce:**

1. Create a 4D database with table Person, activate 4D Mobile service.
2. Create a new solution in 2.2.1.
3. Create a backend test.js file
4. Call addRemoteStore() using follow code:
`var extInfo = 
    {   hostname: "http://127.0.0.1:8090",
        user: "",
        password: "",
        timeout: 15,
	type: "4D"
    };
var extStore = addRemoteStore("Remote", extInfo);

Remote.Person.all()`

5. Start Backend Project, run test.js file.

**Expected behavior:**

All records of remote Person table will be returned.

**Actual behavior:**
An error "datastore's type wakanda is not available"  is returned:
![screen shot 2017-11-01 at 11 53 03 am](https://user-images.githubusercontent.com/1305420/32292784-65b65222-befe-11e7-84f0-2590f615eca9.png)

The same code works without issue in v1.1.5, see screenshot below:
![screen shot 2017-11-01 at 11 20 04 am](https://user-images.githubusercontent.com/1305420/32292773-5c107b62-befe-11e7-8741-8308ebf50c62.png)
 
I can not find any document on whether [addRemoteStore()](https://wakanda.github.io/wakanda-api-reference/docs/interfaces/application.html#addremotestore) has changed in V2. Is this a bug?

**Comment by JegoYann** [comment]
Hello @liuxiang625,

`addRemoteStore()` does not exist anymore in Wakanda `v2`. The documentation your are using is an old one; we've just removed to avoid misunderstanding. Please, use the Wakanda website to get the api-reference.

Now in `v2` to create a 4D remote store, you need to:
- Right click on the `model` folder
- Click `New` > `Model`
- Follow the wizard steps and select `4D` as `datastore type`

Here is some documentations about it: https://wakanda.github.io/doc/#/guide?section=main-data-external

Regards,
Yann

**Comment by liuxiang625** [comment]
Hi Yann, 

Thanks for your answer. I figured addRemoteStore() might not be supported in V2 anymore. But did not see this change documented and the error message seems a bit confusing.

Since addRemoteStore() is used to dynamically reference a remote datastore, is there an alternative way to do this programmatically in V2?

Are other remote store methods like mergeOutsideCatalog() and openRemoteStore() gone as well?

Thank you!

**Comment by franak** [comment]
Hi Yann,

> Since addRemoteStore() is used to dynamically reference a remote datastore, is there an alternative way to do this programmatically in V2?

In v 1.1.5 we are connecting with several 4d databases using dynamics references.

**Comment by JegoYann** [comment]
Hello @liuxiang625 @franak ,
My bad, `addRemoteStore()` and `openRemoteStore()` are still available in v2 (but removed from documentation... argh). I'm digging into your issue and will update the doc consequently.
I will get back to you when I have a clue.

Regards,
Yann

**Comment by JegoYann** [comment]
I try it again today and it's working correctly with Wakanda v2.2.1 and a 4D Nigthly build (v16 Rxxx).

In our example, a 4D server/solution is on a Windows and has one table with data, no user and a 4D mobile port of 80 (also tried with 8090 without issue). The Wakanda Enterprise Server v2.2.1 is on a MacOS 10.12 (Sierra).

Did I miss something ? Any other difference ?

**Comment by franak** [comment]
Hi.
4D server/solution is onMacOS 10.13 (Hight Sierra)
All my 4D Mobile ports on multiple 4D Server are publishing on port 8050

**Comment by liuxiang625** [comment]
Hi Yann,

I reproduced it with Wakanda v2.2.1 and 4D V16 both on Mac OS 10.13.

AddRemoteStore() works in Wakanda v1.1.5 connecting to the same 4D database on the same machine.

**Comment by JegoYann** [comment]
Tried again this morning with Wakanda Enterprise v2.2.1, 4D V16 R4 both on MacOS 10.13 High Sierra.
Still working correctly.

Are you using the Enterprise version ?
With the corresponding wakanda `license.key` file ?

**Comment by franak** [comment]
Hi Yann,
Wakanda Enterprise 2.2.1 with license.key
4D Sever 15.4 build 15.209796
MacOs 10.13 high Sierra.

**Comment by JegoYann** [comment]
@liuxiang625 Can you send me your Wakanda & 4D solution ?

**Comment by liuxiang625** [comment]
Hi Yann,

I have attached a simple test database and solution in V16R4 and Wakanda 2.2.1. Both on Mac 10.13.

They demonstrate the issue where a remote 4D model can be added in studio dialog. But receives "datastore's type wakanda is not available" error using the same configuration in addRemoteStore().
[addRemoteStoreTest.zip](https://github.com/Wakanda/wakanda-issues/files/1455031/addRemoteStoreTest.zip)

![screen shot 2017-11-08 at 10 46 41 am](https://user-images.githubusercontent.com/1305420/32568174-5629cf0e-c472-11e7-9257-67394cd91d58.png)
![screen shot 2017-11-08 at 10 46 57 am](https://user-images.githubusercontent.com/1305420/32568175-5640cfc4-c472-11e7-8384-b3405ab21f2e.png)

**Comment by JegoYann** [comment]
Thanks @liuxiang625 ,
Just try it and still working OK here. I could come from the 4D base configuration. Can you send me your 4D base ?
Can you send me your license.key on my email ? I would like to verify which modules are activated.

**Comment by liuxiang625** [comment]
Hi @JegoYann,

Does "4D base" refer to the database settings of 4D? That can be found in the AddRemoteStoreTest.4dbase included in the attached zip file.

I also attached the license key I downloaded from 4D store with 4D Mobile expansion. I believe this is the same license key most 4D Mobile customers possess. 
[license.key.zip](https://github.com/Wakanda/wakanda-issues/files/1456827/license.key.zip)

**Comment by JegoYann** [comment]
Thanks @liuxiang625 . I will take a look right now.

Please remove the `license.key` from your comment. This should stay private.

**Comment by liuxiang625** [comment]
key removed. Thanks!

**Comment by JegoYann** [comment]
@liuxiang625 Ok ! Got it. This is a license issue. I suspect it should have 'wakanda-connector` too. And it only have `4d-connector`.

**Comment by liuxiang625** [comment]
Hi Yann,

The new license with wakanda-connector works for me.
I will provide this to 4D Mobile customers until it is updated in 4D store.

Thanks for looking into this and fixing it so promptly. You are awesome!

-Xiang
