### ISSUE TITLE
http://doc.wakanda.org do not works.

### ISSUE THREAD

**Issue by marcobramucci** [Wakanda/wakanda-issues#226]
Sorry for the stupid question, but if I connect to the doc site a get this error:

504 Gateway Time-out

The server didn't respond in time.

**Comment by alcada** [comment]
I confirm this issue.
Please do not close the access to WAF/wakanda prototyper documentation.
I suppose this URL is still critical for a significant number of users

**Comment by hamzahik** [comment]
Fixed. Thanks for your report.

http://doc.wakanda.org/home2.en.html
