### ISSUE TITLE
Reload model doesn't always reload model

### ISSUE THREAD

**Issue by chriscurnow** [Wakanda/wakanda-issues#229]
Server & Studio versions 2.3.0

I have seen this before in earlier versions but today it bit me big time.

I just spent a couple of hours trying to work out why changes I made to the model (using the model API) weren't being reflected in the data I was getting back from the server.

Each time I made a change, Studio told me I needed to reload the model which I did. The indicator at the bottom of the screen said "Starting local Wakanda server" and then 'Server is now connected".

The change I made was reflected in the visual model designer but was not reflected in the data I was getting back from the server.

It turns out I had to physically stop the server (using Activity Monitor in my case) and THEN restart from Studio.

Once I did this, the changes were reflected in the data I got back from the server.

**Comment by liuxiang625** [comment]
I have had cases which reload model does not work until the server is restarted. My experience is that "reload model" usually works when existing table/attribute/method is changed. However, when it comes to adding new ones to model, reload model can be unpredictable. As far as I know, reload model button will send a request to server and request server to rebuild the model based on the updated definition. But will not necessarily update all data loaded into server memory.

I am used to reloading the entire solution after adding things to the model. Studio had a "reload solution" button in v1, in V2, the solution can be reloaded by running backend project again. In addition, v2 task tab allows you to close  server gracefully by clicking the "x" next to "Running Wakanda Server":
![screen shot 2017-12-14 at 1 50 56 pm](https://user-images.githubusercontent.com/1305420/34016250-09dbc938-e0d6-11e7-8f0b-821a132a754b.png)

This is my two cents about my practice with reloading model safely. If you have a reproducible case and can provide details on what changes are not being reloaded as expected. Please feel free to add them below so the team can proceed to address the issue and determine whether it is a bug.

**Comment by hamzahik** [comment]
We will investigate this.

Here is a little tip:

![image](https://user-images.githubusercontent.com/6703912/34980030-6ebf9be0-faa3-11e7-9576-07b611d03600.png)

If you click on the **Run** button, all the project with types "checked" in the Run menu will be closed and started once again.

For example if "Web" and "Backend" are checked in the menu and you click on the Run button, all web and backend projects are going to be closed and started (equivalent to closing thoses processes and re-running them). And if you have some projects of type "Mobile" running they won't be closed.
