### ISSUE TITLE
Can not reopen page designed in prototyper( WYSIWYG GUI designer)

### ISSUE THREAD

**Issue by liuxiang625** [Wakanda/wakanda-issues#23]
Can not reopen page designed in prototyper(GUI designer)

Steps to reproduce:

1. Create a new solution in Wak 11.
2. Open a index.html under web/prototype
3. Save and close index.
4. Reopen index in prototyper.

Expected results:
Page will be open in WYSIWYG GUI designer.

Actual results:
Page is opened in HTML editor and can not be switched to GUI designer.
![screen shot 2016-01-07 at 1 23 02 pm](https://cloud.githubusercontent.com/assets/1305420/12183652/0157665a-b545-11e5-8c81-2b71edf1ac3b.png)

Reproducible in 11.194922 and 11.195328
Test solution attached:
[Wakanda11GUITest.zip](https://github.com/Wakanda/wakanda-issues/files/81794/Wakanda11GUITest.zip)

Removing package.json helps to relaunch in in GUI designer, but all CSS and JS will be loaded with WAF loader at runtime. Test solution and screenshot attached:
![screen shot 2016-01-07 at 1 23 17 pm](https://cloud.githubusercontent.com/assets/1305420/12183685/42866310-b545-11e5-9c37-f600324797ca.png)

[testSolution.zip](https://github.com/Wakanda/wakanda-issues/files/81798/testSolution.zip)

**Comment by cedricss** [comment]
My answer about `.waComponent` also applies to `.waPage`:

- https://github.com/Wakanda/wakanda-issues/issues/22

I hope it helps.
