### ISSUE TITLE
HTTP Server SSL Rating

### ISSUE THREAD

**Issue by ronpfi** [Wakanda/wakanda-issues#231]
Testing my site with https://www.ssllabs.com/ I get only an overall rating of "B" because of:

"This server accepts RC4 cipher, but only with older protocols." and

"The server does not support Forward Secrecy with the reference browsers."

**Comment by hamzahik** [comment]
@ronpfi We will add support for Forward Secrecy in Wakanda Server asap. We will post updates on this page.

**Comment by JegoYann** [comment]
Hello @ronpfi,
Forward Secrecy and HSTS are supported with v2.5.0.

Regards,
Yann
