### ISSUE TITLE
[4D Mobile] Query() on Object Field returns incorrect result

### ISSUE THREAD

**Issue by liuxiang625** [Wakanda/wakanda-issues#237]
Wakanda Version: 2.3.0
4D Version: V16.2 and V16R5
OS: Mac 10.13.2

**Issue summary**: Querying object filed using query() against 4D Mobile returns incorrect results. While the same query against Wakanda native datastore works as expected.

**Steps to reproduce:**

1. Launch attached 4D database "4DObjFieldQuery" in 4D. Start Web Server.

2. Launch attached Wakanda Solution in Wakanda Enterprise Studio. Start Backend project.

3. Open WakandaObjQuery.js and query Wakanda native dataclass **WakPerson** using following code:
`ds.WakPerson.query('Pet.ID = 2');`

4. Open 4DMobileObjQuery.js and query 4D Mobile dataclass **Person** using following code:
`ds.Person.query('Pet.ID = 2');`

**Expected result**: both query returns the same correct result  as follows:
`[ { "__KEY": "2", "__STAMP": 1, "ID": 2, "Pet": { "ID": 2 } } ]`

**Actual result**: Wakanda native query works as expected. However, 4D Mobile query returns all records instead of desired matching record(s). The returned result from 4D V16.2 is as follows:
`[ { "__KEY": "1", "__STAMP": 1, "ID": 1, "Pet": { "ID": 1 } }, { "__KEY": "2", "__STAMP": 1, "ID": 2, "Pet": { "ID": 2 } }, { "__KEY": "3", "__STAMP": 1, "ID": 3, "Pet": { "Dog": { "ID": 2 } } } ]`
When tested in V16R5, the return is Null.

Both dataclasses have same fields and same records in storage:

![screen shot 2018-01-17 at 10 50 25 am](https://user-images.githubusercontent.com/1305420/35060847-61f73f5e-fb74-11e7-945c-192c3fc440f7.png)
![screen shot 2018-01-17 at 10 50 14 am](https://user-images.githubusercontent.com/1305420/35060848-620c5a42-fb74-11e7-802f-207976625336.png)

**Analysis by Tech Support**:

The captured REST request generated by Wakanda and sent 4D is as follows:
http://127.0.0.1:8090/rest/Person?$method=entityset&$query='{"model":"Person","queryItems":[{"tokenType":"simpleCompWithEm","attName":"Pet","emName":"Person","comparaison":13,"instance":0,"checkForNull":false,"objPath":"ID","value":2,"diacritical":false}]}'&$top=80
V16.2 returns:
`{
__ENTITYSET: "/rest/Person/$entityset/CF9FF3AD62CE4DC1805AEB5F6BFC770D",
__entityModel: "Person",
__COUNT: 3,
__SENT: 3,
__FIRST: 0,
__ENTITIES: [
{
__KEY: "1",
__STAMP: 1,
ID: 1,
Pet: {
ID: 1
}
},
{
__KEY: "2",
__STAMP: 1,
ID: 2,
Pet: {
ID: 2
}
},
{
__KEY: "3",
__STAMP: 1,
ID: 3,
Pet: {
Dog: {
ID: 2
}
}
}
]
}`
V16R5 returns:
`{
__ENTITYSET: "/rest/Person/$entityset/AFA08194B576460B995C88F760BFC160",
__entityModel: "Person",
__COUNT: 0,
__SENT: 0,
__FIRST: 0,
__ENTITIES: [ ]
}`

This request returns all records despite specified attrName, objPath and value.

On the other hand, using $filter options sending the query string directly to 4D Mobile works as expected:
http://127.0.0.1:8090/rest/Person/?$filter=%22Pet.ID=2%22 
returns
`{
__entityModel: "Person",
__COUNT: 1,
__SENT: 1,
__FIRST: 0,
__ENTITIES: [
{
__KEY: "2",
__STAMP: 1,
ID: 2,
Pet: {
ID: 2
}
}
]
}`

Testing database and solution attached:
[4DMobileObjFieldQuery.zip](https://github.com/Wakanda/wakanda-issues/files/1640325/4DMobileObjFieldQuery.zip)

**Comment by JegoYann** [comment]
@liuxiang625 I do reproduce the same with a wakanda-to-wakanda connection.

**Comment by liuxiang625** [comment]
Good to know you can confirm it, Thanks!

**Comment by liuxiang625** [comment]
This bug has been fixed in 4D build v16.3 >=219809. This issue is considered closed. 
Thanks @JegoYann for working on it!

**Comment by JegoYann** [comment]
Hello @liuxiang625 ,

Indeed ! Yet, there is a small fix for Wakanda-to-Wakanda queries; out with v2.4.0.

Regards,
Yann
