### ISSUE TITLE
Dataclass methods called via REST always in guest mode

### ISSUE THREAD

**Issue by Fuchssystems** [Wakanda/wakanda-issues#238]
Probably same problem as issue id 215.

v2.3
User is logged in successfull with wakanda client.
wakanda client .directory.getCurrentUser) correctly returns the logged in user.

However, on the server dataclass methods called via REST have:
directory.currentSession.user.ID is '0000...' which means "guest".

Use a custom log in method that obviously works correctly (returns a directory.user object).

In Issue id 215 a hack in file 'proxy.conf.json" is recommended.
This file seems to be part of an angular template.
I just use wakanda as database server (no angular, no template, not used as webserver).

Any ideas.
I consider behaviour as a bug.

**Comment by Fuchssystems** [comment]
Worked around by using wakanda client to execute a dataclass method.

Wonder if it is required to transmit the session ID in the cookie which each REST call in order to have the method not be run in guest mode. Could not find examples in the documentation.

How is a method to be called via REST in a way that the session of the logged in user is available in the method?

**Comment by hamzahik** [comment]
@Fuchssystems 
So you have a Wakanda Server running on port X and where do you host your static web files ? on a separate server ? can you give more info about your setup ?

**Comment by Fuchssystems** [comment]
@hamzahik 
> So you have a Wakanda Server running on port X
Yes.

> where do you host your static web files ? 
Web files are served by node development server (setup is 'create-react-app').
Means wakanda never serving weg pages.
Wakanda server only is used via wakanda-client and plain REST.

I think behaviour is not a bug.
After all I never send a session ID when wakanda runs a request in guest-mode.
Assumed wakanda would use the ip of prior successfull login via REST.

Solved by using wakanda-client and/or transmiting the session ID as a custom parameter and getting the session on the server from the custom parameter.

So question is:
What is the "official" way of logging in and have the session on the server using REST?
How does the session id has to be transmitted in REST calls in a way wakanda-server automatically loads the session and uses it?
Examples or is this documentated?

**Comment by Fuchssystems** [comment]
Issue closed.
Reason for behaviour was that session cookie was not transmitted because of missing parameter in my "fetch" call.
