### ISSUE TITLE
Debugger does not work in Safari

### ISSUE THREAD

**Issue by swelshh** [Wakanda/wakanda-issues#24]
Wak 11.195328
Safari 8.0.7
OS X 10.10.4

The debugger will open a window in Safari but the debugger does not show the source and seems non-functional.

![screen shot 2016-01-10 at 11 39 31 am](https://cloud.githubusercontent.com/assets/1295707/12222918/e6dda9fa-b78e-11e5-8da6-afa2978fe98f.png)

**Comment by JegoYann** [comment]
@swelshh The debugger is now back in Wakanda Studio. It also works in last Chrome version. Safari is not supported.
