### ISSUE TITLE
Problem of evaluation on file: index.js ; manifest.json does not exist on line 70

### ISSUE THREAD

**Issue by olegkonashkov** [Wakanda/wakanda-issues#241]
![wakanda](https://user-images.githubusercontent.com/36711221/36563602-59a08ee8-1823-11e8-872c-0fe062f9cdb6.JPG)
Hi !

Full path to the file: C:\Program Files (x86)\Wakanda\Community\Studio\Extensions\wakanda-extension-templates\index.js
All files exist in the folder.
I paid attention when the problem occurred the second time, when I tried to make a new solution with Login backend:  https://blog.wakanda.io/wakanda-login-templates-system/
Also I tried to add it to existing project, close the project, open it but the error appear.

But the first time I had this problem after studio update from 2.2.1 to 2.3.0, it occurred with already existing template project (template with Inspinia, bootstrap and Wakanda): https://blog.wakanda.io/nice-and-clean-template-with-inspinia-bootstrap-and-wakanda/

I did not bother about this problem, because I did not need this template for some time, but then it also happened with another template (Login backend).

Now I have 2.2.1 version, all templates work, except Login backand: https://blog.wakanda.io/wakanda-login-templates-system/
I uninstalled studio completely several times (cleaned register), reinstall, but it did not help.
I of course tried 2.4.0, updated to it or reinstall.
 
Regards.

**Comment by hamzahik** [comment]
Hi @olegkonashkov,

i've sent a pull request to @rmello4d  that should fix the issue. You can test it from my repository https://github.com/hamzahik/LoginTemplate

If you can confirm this fixes your issue it'll be nice ;)

**Comment by olegkonashkov** [comment]
Hi @hamzahik,

Thank you for the answer.
I have tried this fix, the previous problem on starting (creating) project disappeared.
But I started backend and Wakanda Server reported errors.
I tried to run (''play'') js files, but the same.
![default](https://user-images.githubusercontent.com/36711221/36600085-ff4087cc-18b9-11e8-95d4-d98fad834663.JPG)

Also it is one of these cases when Wakanda Server do not want to stop, like in this issue #228
![default](https://user-images.githubusercontent.com/36711221/36600093-06ec2dfa-18ba-11e8-94c8-7dd3afe4468f.JPG)

**Comment by hamzahik** [comment]
@olegkonashkov In the `bootstrap.js` file try replacing `/login/login` by `login/login`.

I've submitted the fix in my repo and sent a pull request to @rmello4d 

I think it should fix the issue even if I don't reproduce it on my machine but I've already received a report about a similar issue on another template.

**Comment by olegkonashkov** [comment]
Yeah, it helped !
Thank you very much ! )

**Comment by hamzahik** [comment]
You're welcome ! @olegkonashkov
