### ISSUE TITLE
Wakanda Server systemctl status not showing true status of server

### ISSUE THREAD

**Issue by AlistairBates** [Wakanda/wakanda-issues#244]
### Current Behaviour

When running the command:

<pre>
sudo systemctl status wakanda
</pre>

If the wakanda server failed to start due to an error the output of this command is showing the service as having been started.

### Expected Behaviour

If the wakanda server fails to start, the status command should show that.

### Environment

Ubuntu 17.10 x64, or Ubuntu 16.04 x64
Wakanda 2.4.0

**Comment by AlistairBates** [comment]
Any update on this. Seems not to be fixed in v2.5.0

**Comment by JegoYann** [comment]
Hello @AlistairBates ,

This is planned for the v2.6.0 release.
https://trello.com/b/RA1yHvUU/wakanda-roadmap

**Comment by JegoYann** [comment]
Wakanda v2.6.0 now integrates `systemd` and fixes all known issues on service start/stop.
Do not hesitate to reopen if something's wrong.
