### ISSUE TITLE
Studio 1.1.3 takes to long to start (MacOS High Sierra)

### ISSUE THREAD

**Issue by alcada** [Wakanda/wakanda-issues#251]
Suddenly, after an update of the operating system to MacOS high sierra, version 1.1.3 of wakanda studio began to take a lot of time to boot (2 to 5 minutes).
I've tried several macintosh computers with the same system and the behavior is the same.
Will the Wakanda team have plans to rectify this situation. In the meantime I went back to version 10 for prototype development.

Thanks
alcada

**Comment by kirkroyster** [comment]
I have experienced and reported this issue to  the Wakanda team.  2.x does
not have this issue fyi.  I see this across any machine running High Sierra
which is typically where developers are at I would expect.  Note that I do
not see this lag with starting the server.

Kirk

**Comment by JegoYann** [comment]
Hello @alcada ,

Cannot you try with the latest `v1.1.5` ?
Then if no success, remove the `Addons` extension from your `Documents/Wakanda/Extensions/Addons` folder (if any) and from `Wakanda Studio/Contents/Extensions/Addons`.
This should do the trick.

Regards,
Yann

**Comment by alcada** [comment]
Hello Yann
Thanks for tour support to prototype version of wakanda. It's a huge heartbreak that has ended....
When I referred to version 1.1.3 of the studio, this is actually the version that comes with the 1.1.5 installation package. Only the server has changed to version 1.1.5 in the package available at https://github.com/Wakanda/wakanda-digital-app-factory/releases.
After removing the addons folder instaled by default inside Wakanda Studio/Contents/Extensions/, now wakanda thakes only a couple of seconds to start. HoHowever, I deleted all content from addons (9 items) and I do not know if any files would be missing.
My problem was solved but still persists in the installer provided by wakanda team to all MacOS HighSierra users
Thanks again
alcada

**Comment by JegoYann** [comment]
Thanks for your feedback.

The `Addons` extension updates wakanda studio plugins. It sends a HTTP request to a server down since v2.0.0 is out. The Studio freezes at start up until the HTTP request times out.
So you won't be missing any files as Wakanda Studio v1.1.5 is already packaging last version of every plugins.

We will ship this fix in the next `v1` release but currently we are really busy with the v2 roadmap.
Until then, there is always the `v2` or this workaround.

Regards,
Yann
