### ISSUE TITLE
Unknown CPU load (Wakanda Server 2.4.0 and 2.5.0, Windows Server 2016 (VM))

### ISSUE THREAD

**Issue by ronpfi** [Wakanda/wakanda-issues#254]
Hi,

I have a dubious trouble with Wak Server (2.4.0 and 2.5.0) hosted on a VM with Windows Server 2016 (1 instance at AWS for test, 1 instance at Strato for production). Both with a qualified ssl cetrificate (shows "green" when connecting with https [and url]).

If I connect with Chrome using my domain (https://mydomain.de) CPU load of Wakanda Server reaches 60-100 % of load an remains there. If I connect using the pure IP-Address the CPU load  of Wakanda Server is nearly 0 (as expected).

Is there a known problem in conjunction with my trouble?

Regards Ronald

**Comment by erlicthemad** [comment]
Can you use the system proc command to see what process is taking up the load? Is if the front-end web server, or the actual Wakanda server? Is the DNS configured to be able to perform forward and reverse lookups on the server? I have seen a timeout for the DNS process cause an internet application to stall spinning its wheels while waiting for a DNS resolution.

**Comment by ronpfi** [comment]
I use HPPTS for both!

**Comment by ronpfi** [comment]
I am looking for a similar tool for Windows (I think proc is Linux/Unix?) and will try. Thank you.

**Comment by JegoYann** [comment]
@ronpfi We are investigating this issue.

**Comment by JegoYann** [comment]
Hello @ronpfi,
We did not reproduce it with a simple Wakanda solution using HTTPS on Windows Server 2016.

- Did you succeed monitoring the Wakanda server ? Is the load coming from Wakanda Server ? 
- Is the issue reproducible on the first request ?
- Does the request trigger a Request Handler or a static file ?
- Is it reproducible with every request type/payload or only a specific request ?
- Is CORS activated ?
- Do you have any special project settings ?
- Do you have an example of a failing request you send ?

**Comment by ronpfi** [comment]
This morning I made the latest tests: I rebuild and reinstalled everything and cannot reproduce this behavior any longer. Very strange. Thank you.

**Comment by JegoYann** [comment]
Understood ! Do not hesitate to reopen this issue if you its here again.
