### ISSUE TITLE
REST access cannot find $directory or $catalog

### ISSUE THREAD

**Issue by erlicthemad** [Wakanda/wakanda-issues#265]
In my current project, I could not get the REST interface for Wakanda to work.  Just to make sure I am not accused of having bad code I tried by making a brand new project and trying the REST actions. 
This is in Wakanda 2.6.0
Create a brand new project. 
Make sure dataSource is enabled. 
Start server with debug mode on.

use CURL to try to access the REST services. 

I had my services turned on for port 8086 So I use the following root.
curl 127.0.0.1:8086/rest/$directory/currentUser

the response I get sent back is.

 ```
curl 127.0.0.1:8086/rest/$directory/currentUser
{"__ERROR":[{"message":"Error code: 1800\nThe \"currentUser\" datastore class cannot be found\ncomponent: 'dbmg'\ntask 25859, name: 'HTTP connection handler'\n","componentSignature":"dbmg","errCode":1800}]} 
```
It would seem that the rest service is unable to connect and allow for authentication on a brand new project. I am using 127.0.0.1 with the default settings so I should not be having CORS issues. 

The response makes me think the dataSource service former REST service is unable to connect to the rest of the Wakanda solution. 

I discovered this by trying to test the rest authentication mechanism using the Restlet client to try to login to my now working authentication system. I was feeding the post values to the server and it would respond with a 500 error.

I am basing this off the v11 HTTP REST document from the Wakanda website. The v11 is the latest version available.

**Comment by JegoYann** [comment]
Hello @erlicthemad ,
Indeed, as  you are on a terminal, `$directory` will be interpreted as a variable, it will not work. You should do this instead:

```curl 'http://127.0.0.1:8081/rest/$directory/currentUser'```

Please, assume the errors are in your code before declaring a bug. A side note: 4D support contracts are limited to 4D.
Regards,
Yann
