### ISSUE TITLE
Debugger statement left in combobox widget source code

### ISSUE THREAD

**Issue by swelshh** [Wakanda/wakanda-issues#27]
Wak 11.195328

![screen shot 2016-01-10 at 6 08 35 pm](https://cloud.githubusercontent.com/assets/1295707/12225014/661e9d10-b7c5-11e5-853a-18d409502f42.png)

**Comment by jonathanargentiero** [comment]
Thanks for you report! We will remove it.

**Comment by hamzahik** [comment]
Fixed in https://github.com/Wakanda/wakanda-digital-app-factory/releases/tag/1.0.2
