### ISSUE TITLE
Wakanda Studio takes a really long time to come to the front when open

### ISSUE THREAD

**Issue by swelshh** [Wakanda/wakanda-issues#28]
Wakanda 11.195328
OS X 10.10.4

This was a problem with previous versions of Wakanda Studio that had been fixed.

When you load a Wakanda page in a web browser and then go back to Wakanda Studio
1. CPU usage spikes to over 100%
2. You get the spinning beach ball on and off for about 20 seconds
3. Finally you can work in Studio again

**Comment by cedricss** [comment]
@swelshh  we can't reproduce it.

- By _"load a page in the browser"_, do you mean clicking on "Run" from the Prototyper?
- Could-you share a Solution producing this bug?

**Comment by swelshh** [comment]
Sure,

I do not mean clicking "Run" from the Prototyper.  I mean opening Chrome, putting in the URL of the page, and loading the page.  I do have the Chrome developer tools open with cache disabled.

I can definitely send you the solution, will send you a private message.

**Comment by cedricss** [comment]
Thanks @swelshh for the details.

@rmello4d will contact you about this issue and your Solution.
