### ISSUE TITLE
New v2 Text Input widget events are not working correctly

### ISSUE THREAD

**Issue by swelshh** [Wakanda/wakanda-issues#29]
I suspect the entire event system isn't working for v2 widgets.  But here is an example...

When working inside a component.  If you add a v2 Text Input widget, bind a datasource attribute, and watch for onAttributeChange event.  When you start typing in the Text Input in the browser the onAttributeChange event will fire every time you press a key and it will not fire when you leave the field.

That is not the way it is supposed to work, and it is not how this has worked in Wakanda 1 - 10.  The onAttributeChange event should fire when leaving the field (if the value of the field has changed).  If you use a v1 Text Input widget in Wak11 you will see that it still works properly.

I'm noticing this with other v2 widgets.  The events are firing constantly, so much so that they become useless.  The v1 widgets still work correctly.

**Comment by jonathanargentiero** [comment]
Hi @swelshh. We developed v2 widget with a little different approach but if you don't like the new behaviour you can adapt the widgets to your specific needs changing only few lines of code.

For instance what triggers the change in v2 Text Input widget is this code line (`widget.js:243`) in the `init` method:

```javascript
$node.on('change autocompleteselect input', function(event, ui) {
```

You can clone/download-with-addons-extension/copy-paste the widget in your widgets folder and remove the `input` listener from that line. This will avoid the value to be refreshed each time a key is pressed.

```javascript
$node.on('change autocompleteselect', function(event, ui) {
```

Hope this helped!

**Comment by swelshh** [comment]
Hey @jonathanargentiero, that is awesome!  Thanks for your help.
