### ISSUE TITLE
Studio asking to reload files that aren't open in Studio

### ISSUE THREAD

**Issue by swelshh** [Wakanda/wakanda-issues#30]
11.195328

I've had Studio open and working for a while.  I usually edit js files in Webstorm.  I've been working on a particular js file for a web component in Webstorm, making changes and saving.  All good.

Now all of a sudden, every time I save the js file Studio pops a dialog about how it has been modified and if I want to reload.  The js file is not open in Studio (I've never opened it in Studio)...

![screen shot 2016-01-11 at 1 40 02 pm](https://cloud.githubusercontent.com/assets/1295707/12244401/1e7536f0-b869-11e5-81ae-1e02388e08dd.png)

**Comment by hamzahik** [comment]
Hi @swelshh,

Is the companies webcomponent inserted in one of the pages that are being edited on the prototyper ?

**Comment by swelshh** [comment]
No, I always have a blank component on parent pages and load the component through code using loadComponent().

Note that after restarting Studio this problem is gone.  I just tried a bit and can't reproduce it.  I'll keep watching for it to see if I can determine steps to make this happen again.

**Comment by hamzahik** [comment]
I'm closing this issue for now. We can re-open it if we have a scenario to reproduce it.

Thanks for the report @swelshh
