### ISSUE TITLE
$create() function without argument

### ISSUE THREAD

**Issue by Dupont-Matthieu** [Wakanda/wakanda-issues#32]
Wakanda : 11 build 11.194922
Angular-wakanda : 1.0.3

Hi,
I'm encountering a problem with the $create() function. I try to do like in the documentation with:
`var newQuote = ds.Quotes.$create();`
(My table come from 4D - 4DMobile) and i get an error :
![capture d ecran 2016-02-11 a 16 40 36](https://cloud.githubusercontent.com/assets/12332569/12981103/8aedabc6-d0df-11e5-8d3f-2884bcebd228.png)
At this line :
![capture d ecran 2016-02-11 a 16 41 05](https://cloud.githubusercontent.com/assets/12332569/12981142/aa9b4744-d0df-11e5-9aee-1d021482976b.png)
There is no control if pojo is undefined here. Can we create an entity without arg ?

Thanks !

**Comment by mrblackus** [comment]
Hi @Dupont-Matthieu,
Thanks for the report! Indeed a check is missing here, it's bug and it will be fixed really soon.

As a workaround for now, you can call `$create()` by passing an empty object, or directly passing an object with the property values if it's possible according to your code.

**Comment by Dupont-Matthieu** [comment]
This is what i'm doing at the moment. Thanks again :)
