### ISSUE TITLE
Model editor: permissions combobox size not growing.

### ISSUE THREAD

**Issue by InfoAdgrade** [Wakanda/wakanda-issues#35]
CONTEXT:

Systems or/and Wakanda versions or/and hardware where the bug happens:
I try it on OS X but I suspect that is also happens on the other platforms

SUMMARY:

STEPS TO REPRODUCE THE BUG:

  1 create some groups with long names (like 'myGroupAdministratorsJunior1' and 'myGroupAdministratorsJunior2' for example)
  2 go to model editor and assign the group to some dataclasses
  3 see that you can not distinguish the two group also resizing the properties pane because of the comboboxes remain the same size

ACTUAL RESULT: 
I can not read the complete group names
EXPECTED RESULT: 
I should be able to resize the comboboxes
NOTE:
This also happens with the dataclass names too at the left of the model editor into the datastore classes pane.

It would be considered as cosmetic bugs but it is very annoying in the real world: it is not beautiful to have names without limits but that you can not see it

**Comment by jonathanargentiero** [comment]
Thanks for your report,
We will investigate the problem and add a fix for long groups names in the Model editor.
I will inform you when it's production ready.

**Comment by jonathanargentiero** [comment]
Fixed in https://github.com/Wakanda/wakanda-digital-app-factory/releases/tag/1.0.3
