### ISSUE TITLE
CORS does not work if port 80 is specified in the domain list

### ISSUE THREAD

**Issue by tpenner** [Wakanda/wakanda-issues#42]
As seen here:
http://stackoverflow.com/q/35949515/5971390

The CORS configuration does not work when you specify port 80 in the domain list like in this screenshot:
![image1](https://i.stack.imgur.com/OaPgd.png)

The CORS configuration does work when omitting port 80 like in this screenshot:
![image2](https://i.stack.imgur.com/OMmET.png)

This can be easily reproduced by using the [Sample Solution from Issue#21](https://github.com/Wakanda/wakanda-issues/files/66402/aurelia.zip)

Steps to reproduce:
================
1) Take the [Sample Solution from Issue#21](https://github.com/Wakanda/wakanda-issues/files/66402/aurelia.zip)
2) change the Untitled solution to run on port 80.
3) Leave the Aurelia solution on port 8081
4) Add a CORS configuration to aurelia to allow 127.0.0.1:80
5) reload the solution
6) go to http://127.0.0.1 and watch that you get errors
7) change the CORS configuration on aurelia to allow 127.0.0.1 with no port specified.
8) reload the solutions
9) go to http://127.0.0.1 and now it works

I think that both configurations should work because:
a) when talking about HTTP traffic 127.0.0.1:80 is equivalent to 127.0.0.1 
b) the UI requests that you enter the port, so it should work with port 80.

**Comment by hamzahik** [comment]
@tpenner fixed in the community release 1.1.0

**Comment by hamzahik** [comment]
1.1.0 released with the fix
