### ISSUE TITLE
__STAMP not updated on entity.$_entity.serverRefresh()

### ISSUE THREAD

**Issue by JUX84** [Wakanda/wakanda-issues#43]
Hello,

I think the function serverRefresh is either buggy, or I didn't understand its purpose.

As I understand it, this function is to be used when the entity is modifed server-side but we need the changes (_and_ the latest stamp) client-side, so we can save it later.
If it's the case, I think a boolean might be inverted.

If you look at [the source](https://github.com/Wakanda/angular-wakanda/blob/master/angular-wakanda.debug.min.js#L2639), you can see that the boolean refreshOnly is forced to 'true', but when it's used in the [rest response handler](https://github.com/Wakanda/angular-wakanda/blob/master/angular-wakanda.debug.min.js#L2769) it checks if it's set to 'false', so neither the key nor the stamp are updated.

Regards.

**Comment by mrblackus** [comment]
Hello @JUX84,

`$serverRefresh()` is a deprecated feature since Angular-Wakanda 1.0.3 and will be definitely removed in the next 1.1.0 release.

If you have a specific need that only `$serverRefresh()` can address, don't hesitate to detail the use case and we'll be glad to add such a feature if there is no other way to do it.

**Comment by JUX84** [comment]
Hi mrblackus,

In my case, I load an entity (stamp 1), I modify and save it (stamp 2), then I have a 4D method modifying it (stamp 3, but only server-side). If I try to save my current entity, it'll will tell me that the stamp is wrong, so I have to refresh my entity be fore modifying and saving it again.

What would be the best way to achieve that ?

**Comment by mrblackus** [comment]
You could use `$fetch()` method on your entity, it will fetch it again and update all its attributes, its stamp to. Then apply your modifications and call `$save()`.

Let me know if it suits your need.

**Comment by JUX84** [comment]
Ok, so it seemed like a good idea but I think there is an other bug.
I replaced serverRefresh with $fetch, but the problem appeared again, so I digged a bit and I found out that using serverRefresh, I got the correct stamp on the network, but $fetch sent me an old one.

You can see what I mean on the attached screens.

The code (I made sure that serverRefresh was called _before_ $fetch):
![capture d ecran 2016-03-16 a 11 20 49](https://cloud.githubusercontent.com/assets/3422399/13809160/aa51d542-eb69-11e5-980a-fc8836551050.png)

The result:
![capture d ecran 2016-03-16 a 11 20 30](https://cloud.githubusercontent.com/assets/3422399/13809177/bd62d1cc-eb69-11e5-8122-2ade29f3f3d4.png)

**Comment by mrblackus** [comment]
You are calling `serverRefresh` and `$fetch` at the same time, your are supposed to only call `$fetch()`.
Then, you have to be sure that your server-side computation is finished when `$fetch()` is called.

**Comment by JUX84** [comment]
I actually call my methods after the server-side computation is finished as you can see in the screenshot below:
![capture d ecran 2016-03-16 a 11 41 21](https://cloud.githubusercontent.com/assets/3422399/13809698/43df1772-eb6c-11e5-8f08-b4ed5de680b7.png)

You'll see in the next screenshots that calling them at the same time changes nothing at all.
I did that just so you could see that serverRefresh (which was called before $fetch) had the good stamp while $fetch didn't.

Code for $fetch only:
![capture d ecran 2016-03-16 a 11 40 53](https://cloud.githubusercontent.com/assets/3422399/13809748/7e3bd2ca-eb6c-11e5-9580-bc6de711fcf4.png)

Response for $fetch only:
![capture d ecran 2016-03-16 a 11 40 37](https://cloud.githubusercontent.com/assets/3422399/13809755/84da7348-eb6c-11e5-917e-9629c59d236e.png)

Code for serverRefresh only:
![capture d ecran 2016-03-16 a 11 41 09](https://cloud.githubusercontent.com/assets/3422399/13809762/8db17610-eb6c-11e5-8efa-c04e6f14b892.png)

Response for serverRefresh only:
![capture d ecran 2016-03-16 a 11 39 18](https://cloud.githubusercontent.com/assets/3422399/13809770/96b63c28-eb6c-11e5-9bae-fbb5e33ca31b.png)

**Comment by mrblackus** [comment]
Forgetting `serverRefresh()` call and focusing on `$fetch()`, can you compare the stamp returned by `$fetch()` and the one actually stored on db with the data browser ? If the computing is finished server-side and the stamp has been updated, `$fetch()` will retrieve it.

I'm not totally sure about `serverRefresh` behavior, so I strongly discourage you to use it.

**Comment by mrblackus** [comment]
Forgetting about `serverRefresh()` call and focusing on `$fetch()` one, can you compare the stamp returned by `$fetch()` with the one returned by REST API (`/rest/DataClassName(entityID)`)? If it's the same, a `$save()` is not supposed to fail.

**Comment by JUX84** [comment]
I did what you said.

Since $fetch just calls the REST API you can guess that the stamp was the same, even if i called the REST API myself a few minutes after the server-side computation.

(Using the same code as above with $fetch only)
![capture d ecran 2016-03-16 a 12 14 58](https://cloud.githubusercontent.com/assets/3422399/13810581/efaf587e-eb70-11e5-80dd-c16c2ede2c8b.png)

![capture d ecran 2016-03-16 a 12 14 45](https://cloud.githubusercontent.com/assets/3422399/13810608/01400fc0-eb71-11e5-992b-8c185de458d6.png)

I think the problem comes from deeper, maybe because of caching or something like that.

What I noticed is that, to have the correct stamp when using the REST API, i had to either reload the wakanda solution, or to call serverRefresh. The latter works because it doesn't just call the REST API, and this behavior seems to work better in my case.

**Comment by mrblackus** [comment]
I checked with the team and you're right, there actually is a caching issue between the 4D Server and Wakanda Server.
Roughly, what happens is:

- you got a entities from 4D through 4D bridge
- the query is cached on Wakanda Server
- when the 4D method modifies your entity, Wakanda cache is not updated
- you try to save, it fails (stamp issue)
- you call `$fetch()`, but `$fetch()` relies on Wakanda cache (which is outdated)
- the old stamp is returned

@hamzahik will bring you more accurate details about this, as I'm not a expert on Server part. ;)

We will provide a fix for this issue soon.

As a side note : **do not rely on `WAF` methods when using Angular-Wakanda** (like `serverRefresh`). `WAF` will be removed from Angular-Wakanda and replaced by [Wakanda Client](https://github.com/Wakanda/wakanda-javascript-client) on the next release, in a couple of weeks.

**Comment by JUX84** [comment]
Great, thanks for your time.

Regards.

**Comment by hamzahik** [comment]
@JUX84 the description of the bug that @mrblackus gave is accurate.
The fix will be that when you do a save on the client side(Angular-Wakanda), Wakanda server will receive the HTTP request and will run the command on 4D ( or any other remote database ), if there is an optimistic locking problem ( STAMP in the case of Wakanda/4D), Wakanda Server will refresh its cache with the new entity values and send a normal STAMP error to the client side(Angular-Wakanda), this way if you do a fetch you'll have the latest version of the entity.
I'll post an update here as soon as the release with the fix is available.

**Comment by JUX84** [comment]
Hi @hamzahik,

Thanks for the update. I'll try your fix as soon as it's available.

**Comment by fredGandelot** [comment]
Hi @JUX84 ,

FYI, a fix has been developed and will soon be tested by our Q&A department. 
We'll keep you posted here.

**Comment by hamzahik** [comment]
1.1.0 released with the fix
