### ISSUE TITLE
Wakanda server 1.0.3 Dockerization KO

### ISSUE THREAD

**Issue by v-rossignol** [Wakanda/wakanda-issues#44]
I'm trying to deploy Wakanda community server 1.0.3 in a Docker container.

Dockerfile is quite simple:

```Dockerfile
FROM ubuntu:14.04
MAINTAINER Vincent ROSSIGNOL <XXXXXX@XXXX.fr>

ENV DEBIAN_FRONTEND noninteractive
ENV VERSION 1.0.3
ENV PACKAGE wakanda-server-community_1.0.3-197492_amd64.deb

RUN apt-get update \
 && apt-get install -y wget libcap-ng-utils \
 && apt-get clean

WORKDIR /tmp/

RUN wget -qL https://github.com/wakanda/wakanda-digital-app-factory/releases/download/${VERSION}/${PACKAGE} \
 && dpkg -i ${PACKAGE} \
 && rm ${PACKAGE}

EXPOSE 8080 4433
```

I can build and run the container from a Debian 8 VM on my local computer.

but when I try to build and to run the container from my production servers:

```shell
>  docker run -it --rm --user root wakanda-server:1.0.3 bash
root@c229492ac69c:/tmp# /opt/wakanda-server/bin/wakanda-server
bash: /opt/wakanda-server/bin/wakanda-server: Operation not permitted
root@c229492ac69c:/tmp#
```

I can reproduce this with docker 1.9.1 & 1.8.3 (both installed on Debian 8).

any idea of what is happening ?

**Comment by osamahf** [comment]
edit  the permission of wakanda-server: 
chwon wakanda:1001 /opt/wakanda-server/bin/wakanda-server

**Comment by v-rossignol** [comment]
this is the solution.

thank you

**Comment by osamahf** [comment]
hi, 
After further tests if you let the same permission you won't have this issue: `chown wakanda:root /opt/wakanda-server/bin/wakanda-server`  

In fact i tested in other machine ubuntu:14.04 with docker version 1.9.1 and it's working perfectly. Also even if you install wakanda in the host machine you won't have this problem.
