### ISSUE TITLE
application.SystemWorker.exec throw an error

### ISSUE THREAD

**Issue by vanwalj** [Wakanda/wakanda-issues#47]
Hello,

I can't find how to get application.SystemWorker.exec working on OSX, but it works perfectly on Windows .
This simply throw an: `new Error("TypeError: JSON.stringify cannot serialize cyclic structures.")`

Wakanda Studio  11 build 11.197492
OSX 10.11.4

Thanks !

**Comment by yboukhata** [comment]
Hi vanwalj,
Can you share the part of code where you are using `SystemWorker`?

**Comment by waktest** [comment]
Hi vanwalj,
try this sample of code : 

var gitVersion = SystemWorker.exec("git version",null);
gitVersion.output.toString();

it should work, and then share with us the part of code that throw the error.

**Comment by vanwalj** [comment]
Okay, it works, but not as expected,
I get `git version 2.6.4 (Apple Git-63)` which correspond to the git bin located in my `/usr/bin/` folder
The binary I want to get executed is located in `/usr/local/bin`.

So now, I just need to set a "custom" PATH, but I can't find how, any idea ?

And thanks by the way !

**Comment by WalidChafai** [comment]
Hi vanwalj, you're welcome,
To set a custom PATH, you'll need to create a json file called  systemWorkers.json at the solution level or at the project level, and then set the diferent Path your application will need to.
This part of documentation will be useful : [systemWorkersjson](http://doc.wakanda.org/home2.en.html#/System-Workers/Configuring-systemWorkersjson-file.200-1067718.en.html)

**Comment by yboukhata** [comment]
Hi @vanwalj 
You can wrap your command by changing environment variable $PATH like this :

        command = 'export "PATH=$PATH:' + YOUR_PATH + '" ;' + command;

In you case, your command will be 

        export "PATH=$PATH:/usr/local/bin"; git version

**Comment by vanwalj** [comment]
Thanks @WalidChafai and @yboukhata 

Now I get something else 
```

**Comment by yboukhata** [comment]
@vanwalj You are welcome.

**Comment by vanwalj** [comment]
Thanks @yboukhata and @WalidChafai 

Now I get something else
```javascript
var command = 'export "PATH=$PATH:/usr/local/bin"; git version';
var gitVersion = application.SystemWorker.exec(command);
console.log(gitVersion); // null
```
So the exec return is null

And if I modify the `systemWorkers.json`
```json
[{
  "name" : "git",
  "executable": [
    { "path": "/usr/local/bin/git" }
  ]
}]
```
I still get `git version 2.6.4 (Apple Git-63)`
which is not the git bin located in my `/usr/local/bin` folder

```bash
$> /usr/local/bin/git --version
git version 2.8.1
```

**Comment by WalidChafai** [comment]
Try using : 
var command =  'export "PATH=/usr/local/bin:$PATH"; git version';
var gitVersion = application.SystemWorker.exec(command);
console.log(gitVersion.output.toString());

**Comment by vanwalj** [comment]
gitVersion still null,
I get `Cannot read property 'output' of null`

**Comment by WalidChafai** [comment]
If you run command  "git version" on bash without being located in "$> /usr/local/bin/git" , it result with "git version 2.6.4" ? if it's the case you should just modify the PATH
Try this part of code : 
var command1 = "bash -c 'export PATH=/usr/local/bin:$PATH; echo $PATH; git version;'";
 SystemWorker.exec(command1);
var gitVersion = SystemWorker.exec(command1);
console.log(gitVersion.output.toString());

**Comment by vanwalj** [comment]
If I exec
```bash
$> echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
$> git --version
git version 2.8.1
```

And if I try 
```javascript
var command = 'export "PATH=/usr/local/bin:$PATH";echo $PATH; git --version';
console.log(command);
var gitVersion = application.SystemWorker.exec(command);
console.log(gitVersion.output.toString());
```

I still get `Cannot read property 'output' of null`

**Comment by WalidChafai** [comment]
you didn't use the bash -c , Built-in bash or cmd commands (such as "dir", "cd" as well as "|" or "~") cannot be called directly in a SystemWorker.
TRY  :  var command = "bash -c 'export PATH=/usr/local/bin:$PATH; echo $PATH; git version;'";

**Comment by vanwalj** [comment]
Okay, now I get the initial error
```
var command = "bash -c 'export PATH=/usr/local/bin:$PATH; echo $PATH; git --version;'";
var gitVersion = application.SystemWorker.exec(command);
console.log(gitVersion);
```
Which output `new Error("TypeError: JSON.stringify cannot serialize cyclic structures.")`

**Comment by yboukhata** [comment]
This example is working for me.
For more simplicity, I have used [shellWorker.js](https://github.com/Wakanda/shellWorker/blob/master/shellWorker.js).



        var shell = require('shellWorker');

        function wrapCommand(command) {
            return command = os.isMac ? 'export "PATH=/usr/local/bin:$PATH' + '" ;' + command : command;
        }
        
        function exec(command) {
            return shell.exec(wrapCommand(command.cmd), command.path);
        }

        // git version
        var output = exec({ command: 'git version' });

**Comment by WalidChafai** [comment]
you got new Error("TypeError: JSON.stringify cannot serialize cyclic structures.") because you didn't use "gitVersion.output.toString()"
Just copy/past this code : 
`var command1 = "bash -c 'export PATH=/usr/local/bin:$PATH; echo $PATH; git version;'";`
`var gitVersion = SystemWorker.exec(command1);`
`console.log(gitVersion.output.toString());`

**Comment by hamzahik** [comment]
Hello @vanwalj, 
Are you still experiencing the same issue ?

**Comment by hamzahik** [comment]
@vanwalj I close this for now. Do not hesitate to ask for help on stackoverflow and use the Wakanda tag.
