### ISSUE TITLE
Cannot remove breakpoints in Wakanda Studio

### ISSUE THREAD

**Issue by vanwalj** [Wakanda/wakanda-issues#48]
Hello,

Some breakpoints seems locked (Not all of them)
They appear in the debugger
![image](https://cloud.githubusercontent.com/assets/3532796/14383022/7bdbd1aa-fd92-11e5-8365-38980c846acf.png)
But not in Wakanda Studio
And even if I try to manually edit the `breakpoints.json` file, they still in the debugger and stop on execution.

Wakanda Studio  11 build 11.197492
Mac OS X Version 10.11.4

**Comment by issameljohri** [comment]
Hello,
I use the same build 'Wakanda Enterprise Studio  11 build 11.197492',  when i remove a breakpoint from the code in studio and  refresh the debugger's page the breakpoint is automatically removed from the debugger.
Maybe, you just need  to refresh the debugger's page.

**Comment by hamzahik** [comment]
@vanwalj thank you for your feedback. I'll close the issue for now. Feel free to re-open it if you're still experiencing the same problem.
