### ISSUE TITLE
Doc Bug in Example for $login(username, password)

### ISSUE THREAD

**Issue by tpenner** [Wakanda/wakanda-issues#52]
Page: [api-reference/wakanda-service](https://wakanda.github.io/angular-wakanda/#/doc/api-reference/wakanda-service)
Section: Authentication
Subsection: $login(username, password)

This example code...

	$wakanda.$login('user', 'strong-passord').$promise.then(function () {
	  if (e.result === true) {
		//User is logged in and have permission to manipulate the right dataclasses
	  }
	  else {
		//User is not logged in
	  }
	});

...is missing the `e` in `function(){`

It should be `function(e){` like this:

	$wakanda.$login('user', 'strong-passord').$promise.then(function (e) {
	  if (e.result === true) {
		//User is logged in and have permission to manipulate the right dataclasses
	  }
	  else {
		//User is not logged in
	  }
	});

**Comment by StephaneGarnier** [comment]
Hi, 

I've made a pull request to change this in the Angular-Wakanda connector documentation.

Thank's a lot,

**Comment by hamzahik** [comment]
@StephaneGarnier @tpenner merged ;)
