### ISSUE TITLE
.find() methode does not find entity inside transaction

### ISSUE THREAD

**Issue by steeu** [Wakanda/wakanda-issues#53]
Wakanda Studio for Windows  11 build 11.197492

The datastore find methode does not find an entity that is created in a transaction from within the same transaction.

**Bug**: `ds.Employee.find()` the result returns "null"
```
var result;

ds.Employee.remove();

// start transaction
ds.startTransaction();
// create new entity
new ds.Employee({firstName: "Joe"}).save();
// search entity
result = ds.Employee.find("firstName == Joe");
// commit transaction
ds.commit();

result;
```

**OK**: `ds.Employee.query()` the result returns the created entity
```
var result;

ds.Employee.remove();

// start transaction
ds.startTransaction();
// create new entity
new ds.Employee({firstName: "Joe"}).save();
// search entity
result = ds.Employee.query("firstName == Joe");
// commit transaction
ds.commit();

result;
```

**Comment by fredGandelot** [comment]
Hi @stefaneugster I check this asap and keep you posted here

**Comment by stefaneugster** [comment]
Thanks, I've used `ds.Employee.query("firstName == Joe")[0]` as a workaround ...

**Comment by fredGandelot** [comment]
@stefaneugster  The bug has been reproduced and will be fixed asap.
Of course meanwhile you can use your workaround.

**Comment by fredGandelot** [comment]
Hi @stefaneugster A fix has been developed and is currently under testing. 
However you can already test it on Main.
if tests are green, I 'll keep you posted about its futur integration on Wak11

_Hope you're doing well btw ;) _

**Comment by alcada** [comment]
Hello everyone
I used to test the fixes in versions available in:
http://download.wakanda.org/DevChannel/Main/Wakanda/ (MAC+WIN+LINUX)
but, since March 2016, there are no news at this URL.
The address for access to the Main channel changed?
Tanks

**Comment by fredGandelot** [comment]
@alcada Actually that's my bad. Dev versions are no longer available. 
The fix has been developed and will be  integrated integrated in the next wak version

**Comment by hamzahik** [comment]
1.1.0 released with the fix
