### ISSUE TITLE
Prototyper : The event is not created in the js file when we try to add an event for the button widget

### ISSUE THREAD

**Issue by Ganbin** [Wakanda/wakanda-issues#58]
With the 1.1.0 I have tried to add a button to my interface and add an onClick event. The js file is open but the appropriate code is not created.

I didn't try more but with the 1.0.3 it work so it must be a bug.

**Comment by hamzahik** [comment]
@Ganbin thanks for the feedback. This was actually the reason why we rollbacked the version as explained in #57. It affected both the model and widgets.
A pre-release for Mac is now available on the [website](https://wakanda.github.io) it should fix this bug. It would be great if you can confirm that. 
You can read the [changelog](https://github.com/Wakanda/wakanda-digital-app-factory/releases/tag/1.1.0) for more information.

**Comment by kirkroyster** [comment]
Absolutely, that is great to hear - I will test and reply yet today.

**Comment by Ganbin** [comment]
Ok I have tested the pre release and the event are well created in the js file

**Comment by hamzahik** [comment]
@kirkroyster @Ganbin great !
