### ISSUE TITLE
$wakanda.$login fails after using $wakandaConfigProvider.setHostname(hostname) 

### ISSUE THREAD

**Issue by tpenner** [Wakanda/wakanda-issues#61]
I am using the $login(username, password) described [here](https://wakanda.github.io/angular-wakanda/#/doc/api-reference/wakanda-service), which works fine under normal use.

	$wakanda.$login('user', 'strong-passord').$promise.then(function (e) {
	  if (e.result === true) {
		//User is logged in and have permission to manipulate the right dataclasses
	  }
	  else {
		//User is not logged in
	  }
	});

However I am trying to use setHostname(hostname) as described [here](https://wakanda.github.io/angular-wakanda/#/doc/api-reference/wakanda-config-provider)

	angular.module('application', ['wakanda'])
	  .config(function ($wakandaConfigProvider) {
		$wakandaConfigProvider.setHostname('http://webserver.com:1136');
	  });
 
What i am seeing is that once i use `setHostname` then the `$login(username, password)` no longer works.

What happens is that I get a 401 error for the XHR request and it shows the following errors in the web inspector:

> angular-wakanda.min.js:1 OPTIONS http://10.96.0.99:8081/rest/$directory/login/?$top=40&$method=entityset&$timeout=300 go @ angular-wakanda.min.js:1g.DataStore.funcCaller @ angular-wakanda.min.js:1c @ angular-wakanda.min.js:1e @ angular-wakanda.min.js:2m.$loginByPassword.m.$login @ angular-wakanda.min.js:2$scope.login @ controllers.js:6fn @ VM690:4(anonymous function) @ ionic.bundle.js:62386Scope.$eval @ ionic.bundle.js:29158Scope.$apply @ ionic.bundle.js:29257(anonymous function) @ ionic.bundle.js:62385eventHandler @ ionic.bundle.js:16583triggerMouseEvent @ ionic.bundle.js:2948tapClick @ ionic.bundle.js:2937tapMouseUp @ ionic.bundle.js:3013

>:8100/?ionicplatform=android#/page6:1 XMLHttpRequest cannot load http://10.96.0.99:8081/rest/$directory/login/?$top=40&$method=entityset&$timeout=300. Response for preflight has invalid HTTP status code 401

Here is a screencast demonstrating the issue:

http://screencast.com/t/I45jmBDkjF

**Comment by mrblackus** [comment]
Hi Tim,

It seems to be a CORS issue. Is you CORS well set server-side ?

**Comment by tpenner** [comment]
What is the wildcard address to use allowing all adresses.  Is that 0.0.0.0
or just *?

**Comment by tpenner** [comment]
Wait a second.

If it's due to cors then why does only the $login fail but other requests
work fine.

If it is due to cors then the bug is that the other requests (besides
$login) continue working without cors.

**Comment by tpenner** [comment]
I added the following CORS configuration:
![image](https://cloud.githubusercontent.com/assets/1653635/15222818/44205642-1826-11e6-82c9-ad9b4479cd54.png)

However it still fails with the same error when attempting to login from my DEV machine using the Production address in the SetHostname.

Is it working for you?

**Comment by tpenner** [comment]
I checked the web inspector a bit closer and realized the request method that was failing was OPTIONS:

> Request URL:http://10.96.0.99:8081/rest/$directory/login/?$top=40&$method=entityset&$timeout=300
>Request Method:OPTIONS
>Status Code:401 Unauthorized
>Remote Address:10.96.0.99:8081

Here is a screenshot of the inspector for the failed request after using SetHostname:
![image](https://cloud.githubusercontent.com/assets/1653635/15224335/975152ce-182d-11e6-8643-98a44df84b6a.png)

This is odd though because local request (not using SetHostname) do not appear to be using the OPTIONS request type... Here is a screenshot of the working request when i comment out SetHostname:
![image](https://cloud.githubusercontent.com/assets/1653635/15224360/bfb8ae6a-182d-11e6-9bf6-7d0202712ec9.png)

So i tried adding that to the Wakanda CORS for 0.0.0.0:* and it seems that OPTIONS cannot be added, it is being ignored by the UI.

**Comment by tpenner** [comment]
Is there any update on this?

Does using `$Login` and `SetHosname` in the same application work for you?

**Comment by hamzahik** [comment]
@tpenner we are trying to reproduce and analyse the issue. We will get back to you asap.
Sorry for the delay.

**Comment by tpenner** [comment]
Thanks for checking on this. I really appreciate your time and help on this. 

Perhaps I am using the wrong address for SetHostname.

My interpretation of SetHostname was that it is used to specify the Wakanda Server that REST requests should be sent towards; as the documentation states “Set the hostname to the provided value. All REST calls from Angular-Wakanda will now be sent to this server. Be careful about CORS (Cross-Origin Resource Sharing) issues”. So naturally I used http://myWakandaServer:8081 because the Wakanda project runs on port 8081; but I now think this may be wrong. 

On my development machine, using `SetHostname` for `http://127.0.0.1:8081` or the actual IP causes the same error, even though the Wakanda solution is running on port 8081. 
>angular-wakanda.min.js:1 OPTIONS http://127.0.0.1:8081/rest/$directory/login/?$top=40&$method=entityset&$timeout=300 go @ angular-wakanda.min.js:1g.DataStore.funcCaller @ angular-wakanda.min.js:1c @ angular-wakanda.min.js:1e @ angular-wakanda.min.js:2m.$loginByPassword.m.$login @ angular-wakanda.min.js:2$scope.login @ controllers.js:7fn @ VM1760:4(anonymous function) @ ionic.bundle.js:62386Scope.$eval @ ionic.bundle.js:29158Scope.$apply @ ionic.bundle.js:29257(anonymous function) @ ionic.bundle.js:62385eventHandler @ ionic.bundle.js:16583
:8100/?ionicplatform=android#/page6:1 XMLHttpRequest cannot load http://127.0.0.1:8081/rest/$directory/login/?$top=40&$method=entityset&$timeout=300. Response for preflight has invalid HTTP status code 401

Same error when using port 8081 with the actual IP address of my development machine:
>angular-wakanda.min.js:1 OPTIONS http://10.96.0.74:8081/rest/$directory/login/?$top=40&$method=entityset&$timeout=300 go @ angular-wakanda.min.js:1g.DataStore.funcCaller @ angular-wakanda.min.js:1c @ angular-wakanda.min.js:1e @ angular-wakanda.min.js:2m.$loginByPassword.m.$login @ angular-wakanda.min.js:2$scope.login @ controllers.js:7fn @ VM1608:4(anonymous function) @ ionic.bundle.js:62386Scope.$eval @ ionic.bundle.js:29158Scope.$apply @ ionic.bundle.js:29257(anonymous function) @ ionic.bundle.js:62385eventHandler @ ionic.bundle.js:16583
:8100/?ionicplatform=android#/page6:1 XMLHttpRequest cannot load http://10.96.0.74:8081/rest/$directory/login/?$top=40&$method=entityset&$timeout=300. Response for preflight has invalid HTTP status code 401

So I looked closer into the requests and noticed _without_ using `SetHostname` the requests were being sent to `http://127.0.0.1:8100` – so I tried using `SetHostname` for `http://127.0.0.1:8100` and this actually **worked**. 

Then I tried to use my public IP of `http://10.96.0.74:8100` and I get `NET::ERR_CONNECTION_REFUSED`
>angular-wakanda.min.js:1 OPTIONS http://10.96.0.74:8100/rest/$directory/login/?$top=40&$method=entityset&$timeout=300 net::ERR_CONNECTION_REFUSED

Trying the production machines IP with port `8100` also fails with `NET::ERR_CONNECTION_REFUSED` as if port 8100 only allows local connections…

I looked at my production server and noticed that the Wakanda Console reported that the Ionic Dev Server was at 127.0.0.1:8100 and that the live reload server was at 127.0.0.1:35729 so I tried using SetHostname with port 35729 and got the following error:
>angular-wakanda.min.js:1 OPTIONS http://10.96.0.99:35729/rest/$directory/login/?$top=40&$method=entityset&$timeout=300 go @ angular-wakanda.min.js:1g.DataStore.funcCaller @ angular-wakanda.min.js:1c @ angular-wakanda.min.js:1e @ angular-wakanda.min.js:2m.$loginByPassword.m.$login @ angular-wakanda.min.js:2$scope.login @ controllers.js:7fn @ VM1912:4(anonymous function) @ ionic.bundle.js:62386Scope.$eval @ ionic.bundle.js:29158Scope.$apply @ ionic.bundle.js:29257(anonymous function) @ ionic.bundle.js:62385eventHandler @ ionic.bundle.js:16583triggerMouseEvent @ ionic.bundle.js:2948tapClick @ ionic.bundle.js:2937tapMouseUp @ ionic.bundle.js:3013
:8100/?ionicplatform=android#/page6:1 XMLHttpRequest cannot load http://10.96.0.99:35729/rest/$directory/login/?$top=40&$method=entityset&$timeout=300. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:8100' is therefore not allowed access. The response had HTTP status code 404.

So obviously the SetHostname is working to some extent, but it isn’t clear what server/port you are actually supposed to enter into this. 

I checked the docs again and the example uses port 1136 :
>$wakandaConfigProvider.setHostname('http://webserver.com:1136');

so I checked my machines and this port isn’t listening…

This question should be super simple - **What IP/Port are you supposed to enter in to SetHostname?**

**Comment by tpenner** [comment]
New Clues:

Using `SetHostname` still breaks $`Login` from the Ionic Previewer (running on port 8100 of the localhost's browser).

However I have gotten it work in very specific situations.

First, i have to Run the Ionic app in the Android Emulator
* $login always fails when using Preview mode from Wakanda

Second, i have to point the SetHostname to the Ionic (Preview?) Server port 8100 
* It must be the Ionic Server
* Using the Wakanda Server (port 8081) doesn't work

Third, you have to make sure the Ionic (Preview?) Server is running on the remote machine
* this may seem obvious, but i dont see how to do this without hitting Preview from Studio
 * this seems problematic for installations where there is no Studio, such as on Linux
   * How can I run Ionic Server when Wakanda Server starts this solution?
   * Which server is actually required, Wakanda Server or Ionic Server or both?

Fourth, Ionic (preview?) Server needs to be listening on an actual IP and allow connections from remote hosts
* This seems to be the default for my two Mac OS X installations
* This is **not** the default on my Windows installation which is what i had been testing against in all of my previous attempts
 * How can I make Ionic Server allow remote connections on Windows? (i think i found my answer [here](http://stackoverflow.com/a/30066701/5971390)

Is this expected? 

Why would using the Ionic Server port 8100 work but not using the Wakanda port 8081?
* it seems that underneath the hood Ionic:8100/rest is just proxied to 127.0.0.1:8081

Why does it always fail from the Preview mode?

What is the expected steps to follow for deploying an app where the Wakanda Server will reside on a Windows VM or a Linux VM?

**Comment by mrblackus** [comment]
Hi Tim,

Can you test again with the attached version of Angular-Wakanda here?

[angular-wakanda.js.zip](https://github.com/Wakanda/wakanda-issues/files/299948/angular-wakanda.js.zip)

Thanks

**Comment by tpenner** [comment]
Thank you @mrblackus 

It appears to be working with the updated library you supplied.

**Comment by mrblackus** [comment]
Nice, @hamzahik would be able to give you more details about the fix, he's the one who found what happened.

Roughly, it was an issue with our XHR calls that didn't make `withCredentials()` call on the `xhr` object, causing issue when CORS was involved.

I'll make a fix on WakandaClient soon and keep you updated here.

**Comment by mrblackus** [comment]
Issue is now fixed with Angular-Wakanda 1.1.2 release.
