### ISSUE TITLE
Angular-Wakanda 1.1.0 Bug when query with a date in params

### ISSUE THREAD

**Issue by Ganbin** [Wakanda/wakanda-issues#64]
I have upgrade my angular-wakanda 1.0.3 to the 1.1.0 and I get an error when I do a query with date in the params.

I get this error in the 1.1.0 : {"__ERROR":[{"message":"The query placeholder :1 is missing or null.","componentSignature":"dbmg","errCode":1279},{"message":"Query cannot be analyzed","componentSignature":"dbmg","errCode":1201}]}

In the 1.0.3 the query is doing well.

I passe a simple date object as a param of my query.

**Comment by Ganbin** [comment]
For now I have downgrade to 1.0.3 until it will be fixed

**Comment by mrblackus** [comment]
Hi @Ganbin,

Thanks for the report. Can you give me an example of the query you made? I will check that and keep it touch soon.

**Comment by Ganbin** [comment]
Here is my query : `{filter:'start > :1 && end < :2',params:[self.from,self.to]}`

`self.from` and `self.to` are linked to an input of the date type. The start and end attribute are date attribute.

```
<label for="from">From</label>
<input type="date" id="from" class="form-control" ng-model="filterCtrl.from" required />

<label for="to">To</label>
<input type="date" id="to" class="form-control" ng-model="filterCtrl.to" required />
```

**Comment by hamzahik** [comment]
Fixed in https://github.com/Wakanda/angular-wakanda/releases/tag/v1.1.1
