### ISSUE TITLE
ng-wak: Updating an entity which has a related entity set to null leads to error

### ISSUE THREAD

**Issue by JUX84** [Wakanda/wakanda-issues#65]
Hey it's me again :D 

I have an entity from dataclass 'Devis' which has a field 'DEV_Bundle_Promo' linked to the ID of another entity from another dataclass.

In my case, the field 'DEV_Bundle_Promo' is set to null which means the relation leads to nothing.
![capture d ecran 2016-05-12 a 14 24 08](https://cloud.githubusercontent.com/assets/3422399/15214626/609b5e98-184e-11e6-9b3e-b09d2de5b241.png)

And so, the link to this related entity is the ID '0'.
![capture d ecran 2016-05-12 a 14 24 36](https://cloud.githubusercontent.com/assets/3422399/15214634/6a849334-184e-11e6-888b-5842cb8f0535.png)

When i query my entity, there is no problem, but when I try to update it, i get an error.
![capture d ecran 2016-05-12 a 14 35 23](https://cloud.githubusercontent.com/assets/3422399/15214696/d6c23790-184e-11e6-9ea7-20f38d246f23.png)
![capture d ecran 2016-05-12 a 14 25 30](https://cloud.githubusercontent.com/assets/3422399/15214635/6d11d9d6-184e-11e6-87c2-7de1b9a938ea.png)

Regards.

**Comment by hamzahik** [comment]
Hello @JUX84  !

Can you please post the payload of the request and the types for the attributes  `DEV_Bundle_Promo` and `Lien_59`

**Comment by JUX84** [comment]
Here are the attributes of DEV_Bundle_Promo, Lien_59, and the target of the link:
![capture d ecran 2016-05-18 a 10 04 55](https://cloud.githubusercontent.com/assets/3422399/15351686/c7345d9e-1ce0-11e6-81f5-b8dfab26ba84.png)
![capture d ecran 2016-05-18 a 10 04 44](https://cloud.githubusercontent.com/assets/3422399/15351682/c15cc0e6-1ce0-11e6-9ede-4b2ea01bd551.png)
![capture d ecran 2016-05-18 a 10 05 06](https://cloud.githubusercontent.com/assets/3422399/15351688/c97d5fb0-1ce0-11e6-87f0-71db01eb601d.png)

Screenshots of the payload:
![capture d ecran 2016-05-18 a 10 06 18](https://cloud.githubusercontent.com/assets/3422399/15351690/cd8d3bb6-1ce0-11e6-8e7a-164cda6adfe6.png)
![capture d ecran 2016-05-18 a 10 06 22](https://cloud.githubusercontent.com/assets/3422399/15351699/d8dfd794-1ce0-11e6-8b32-aa5543f2ac47.png)

The error in the response:
![capture d ecran 2016-05-18 a 10 08 34](https://cloud.githubusercontent.com/assets/3422399/15351704/dddf801e-1ce0-11e6-953b-5d3f502050d5.png)

As you can see, there are other links and those are working.

Regards.

**Comment by fredGandelot** [comment]
Hi @JUX84 ,

I'm new on your issue, so sorry I misunderstand something. 
If I get well , DEV_Bundle_promo is a related attribute from Devis Dataclass (table 8 ) to REI_CLE attribute (table REMISE_IMPORT n°58) This link is called Lien 59

One thing I must not properly understand is why Link_59 would be equal to 0 if DEV_BUNDLE_Promo is `null`
If no relation exists bewteen this 2 tables , link59 should be null too.

**Comment by JUX84** [comment]
Hi @fredGandelot ,

So if I understand correctly what you're saying, the related entity doesn't exist, I should have gotten null instead of "0" when fetching my primary entity. I haven't tried again since then, so maybe with the updates (from both 4D and Wakanda) the issue doesn't exist anymore.

Anyway, I completely changed the way I work with Wakanda since then so I will not be able to try again right now.

If the issue cannot be reproduced, I guess it can be closed.

**Comment by fredGandelot** [comment]
Hi @jux84

If anyhow you face this issue again don t hesitate to reopen an issue. I ll follow up it closely
Thanks
Fred
