### ISSUE TITLE
I installed Cordova and android sdk, but Wakanda Studio has not found it

### ISSUE THREAD

**Issue by khalilmaster** [Wakanda/wakanda-issues#69]
I installed Cordova and android sdk, but Wakanda Studio has not found it
Can i have a little help here please? I am on mac osx

**Comment by bea2701** [comment]
Correct

**Comment by khalilmaster** [comment]
@bea2701  ????

**Comment by jonathanargentiero** [comment]
Hello @khalilmaster, I may need some additional details.

1. I would like you to start Wakanda Studio.
2. Open **Help -> Wakanda Mobile Troubleshooting** on the application menu.
3. The Troubleshooting window should be now open. Click on the **Android** button.
4. Share with us the results of the dependency checks you can find on the left part of the troubleshooting. (I would like to know each result)

Additionally you can try the suggestions proposed by the troubleshooting.
A solution to your problem may be already available.

Please note that it's necessary to restart the Studio when environment variables changes are made.

**Comment by Ganbin** [comment]
I have the same problem with cordova. It is installed but the studio show like it is not. I have set up the environment variable, restart the studio, still the same.

**Comment by yboukhata** [comment]
Hi @Ganbin,

If you have not resolved your problem about installing **cordova module**, Can you tell us where npm modules are installed ?

You can get this information by executing this command : `which npm`.

**Comment by Ganbin** [comment]
According to this issue : (https://github.com/Wakanda/wakanda-issues/issues/73) it is solved. Thanks

**Comment by ccrica** [comment]
Should it helps, I could solve this on Windows by running the npm command under my simple user session (instead of the previous adminstrator's one I initially did).
Path of files is now found by Wakanda...

**Comment by hamzahik** [comment]
@khalilmaster I'll close the issue for now. Please re-open it if you're still reproducing the same problem.
