### ISSUE TITLE
Ionic/Crodova 1.1.0 can't run the app on simulator or ios device

### ISSUE THREAD

**Issue by Ganbin** [Wakanda/wakanda-issues#73]
When I run my mobile app, I have a white screen. I see that this issue can be there because of the live reload. So I have launch my app manually (with ionic emulate ios) without live reload. Then I can see my app. But when a controller is executed and I have a $wakanda.init(), I get this error  : "Failed to load resource: The requested URL was not found on this server. --> file:///rest/$catalog/$all"

**Comment by jonathanargentiero** [comment]
Hello @Ganbin, can you check if you have a **proxies** parameter defined in your `ionic.project` JSON file? It should be similar to this:

```
"proxies" : [
    {
        "path": "/rest",
        "proxyUrl": "http://127.0.0.1:8081/rest"
    }
  ]
```

This creates a proxy from your local Wakanda Server to the device emulated.

**Comment by Ganbin** [comment]
This is my ionic.project : 

```
{
  "name": "Presentation",
  "app_id": "",
  "proxies" : [
    {
        "path": "/rest",
        "proxyUrl": "http://127.0.0.1:8081/rest"
    }
  ]
}

```

**Comment by Ganbin** [comment]
I think I have mess up my cordova. Because the console always show `Cordova: Not found - ` I even put the PATH in the environment variable like said in the help `/usr/local/lib/node_modules/corodva/bin` but still I the check show that cordova is not installed. I have remove and installed again but still the same. When I try to run I get many error : 'Error: EACCES: permission denied, open '/Users/Gabriel/.config/configstore/insight-cordova.json'
You don't have access to this file.'

**Comment by jonathanargentiero** [comment]
The `ionic.project` is fine. First I would like you to double check `/usr/local/lib/node_modules/corodva/bin` since it has a typo in `corodva` -> `cordova`, then the second error your reported is due to permissions, try to run this in your terminal:

```
chmod g+rwx /Users/Gabriel/.config/configstore/
```

as suggested [here](https://github.com/yeoman/yeoman.github.io/issues/282)

**Comment by Ganbin** [comment]
The mistake on the cordova spelling doesn't change anything and to give the permission neither. I have now no more error about EACCES but the simulator is never open and the text "Launching our application on IOS Simulator" never end

**Comment by Ganbin** [comment]
I still have this error : `shell.js: internal error Error: EPERM: operation not permitted, chmod  /Users/Gabriel/Documents/Wakanda/solutions/Presentation/Presentation/mobile/platforms/ios/Presentation/config.xml' ` even after running `sudo chmod g+rwx '/Users/Gabriel/Documents/Wakanda/solutions/Presentation/Presentation/mobile/platforms/ios/Presentation/config.xml'`

**Comment by Ganbin** [comment]
But the good news, is that now cordova is marked as installed.

**Comment by jonathanargentiero** [comment]
Ok, it seems that the `shell.js` module used by Cordova is not able to write on the `config.xml` file.
I suggest you to further investigate your permissions. You can try 
```
sudo chown -R $(whoami) "/Users/Gabriel/Documents/Wakanda/solutions/Presentation"
```
or
```
sudo chmod -R 777 "/Users/Gabriel/Documents/Wakanda/solutions/Presentation"
```
but I suspect the reason of the issue can be a different global issue of permissions.
Please inform us updated if you find the root of the problem.

**Comment by Ganbin** [comment]
Ok thanks a lot.

The `sudo chown -R $(whoami) "/Users/Gabriel/Documents/Wakanda/solutions/Presentation"` command fix the problem.

But now I am back with the other problem with the `Failed to load resource: The requested URL was not found on this server. : file:///rest/$catalog/$all` which was the first reason of the issue here ^^

**Comment by jonathanargentiero** [comment]
That's because running `ionic emulate ios` is not enough to connect with a local Wakanda Server.
Run in your terminal:
```
ionic emulate ios --address 127.0.0.1 --port 8100 --livereload --livereload-port 35729
```
In the terminal output you should see `Proxy added: /rest => http://127.0.0.1:8081/rest` which is the proxy created to communicate with the rest interface of Wakanda Server.

That's an example of the code generated by Wakanda Studio to achieve this result.

**Comment by Ganbin** [comment]
Yes I have actually copy the command shown in the wakanda console : `ionic emulate ios --livereload --address 127.0.0.1 --port 8101 --livereload-port 35730` I have removed the livereload options so that I can be able to remove the whitescreen problem. And then I have open the debugger via safari to see this error about the `file:///rest/$catalog/$all`

**Comment by Ganbin** [comment]
I suspect the angular-wakanda to not initialize the right address to access the rest server.

**Comment by jonathanargentiero** [comment]
Ok, another round. Check your server is correctly running and open `config.xml` and look for this options:
```
<content src="index.html"/>
<access origin="*"/>
<allow-navigation href="*"/>
<allow-intent href="*"/>
```

If none of these works try running [this mobile part of a project I just made](https://drive.google.com/a/wakanda.io/file/d/0B69VEGbLLHa0MjZDblFxeHJXUTQ/view?usp=sharing).

You can also debug your ionic application at [http://localhost:8100](http://localhost:8100).

**Comment by Ganbin** [comment]
Yes I always debug until I have 0 error in the browser before to test on a simulator or a device.

Thanks a lot to add those line in the config.xml made the things to work even with the live reload. 

I only add those two line : 
`<allow-navigation href="*"/>
  <allow-intent href="*"/>` 
Because I had already 
`<content src="index.html"/>
<access origin="*"/>`

**Comment by Ganbin** [comment]
During the process of the "Run" Button the file is changed to `<content src="http://127.0.0.1:8101" original-src="index.html"/>` and when the process is finish, it come back to `<content src="index.html"/>`

**Comment by Ganbin** [comment]
Anyway the problem is fix. Thanks

**Comment by jonathanargentiero** [comment]
You are welcome :)
Remember to remove those two lines before sending the application to production.
