### ISSUE TITLE
[1.1.0] Angular 2 / Ionic 2 Project doesn't launch

### ISSUE THREAD

**Issue by Ganbin** [Wakanda/wakanda-issues#74]
Hi,

I am trying to test the angular 2 and ionic 2 template with the ionic blank and tutorial template and with angular Lite Server and webpack template. So here is my feedback.

**Angular Lite Server** : I can run the page but I only see `loading...` With the `Angular 2 QuickStart` title. I get all those errors : 

```
127.0.0.1/:1 GET http://127.0.0.1:8084/node_modules/es6-shim/es6-shim.min.js 
2016-05-26 15:25:18.521 127.0.0.1/:1 GET http://127.0.0.1:8084/node_modules/systemjs/dist/system-polyfills.js 
2016-05-26 15:25:18.521 127.0.0.1/:1 GET http://127.0.0.1:8084/node_modules/angular2/bundles/angular2-polyfills.js 
2016-05-26 15:25:18.521 127.0.0.1/:1 GET http://127.0.0.1:8084/node_modules/systemjs/dist/system.src.js 
2016-05-26 15:25:18.522 127.0.0.1/:1 GET http://127.0.0.1:8084/node_modules/rxjs/bundles/Rx.js 
2016-05-26 15:25:18.522 127.0.0.1/:1 GET http://127.0.0.1:8084/node_modules/angular2/es6/dev/src/testing/shims_for_IE.js 
2016-05-26 15:25:18.522 (index):1 GET http://127.0.0.1:8084/node_modules/angular2/bundles/angular2.dev.js 
2016-05-26 15:25:18.523 (index):3 Uncaught ReferenceError: System is not defined(anonymous function) @ (index):3
```

**Angular Webpack** : When I run the page, I get a `404 Not Found` Error.

**Ionic blank and tutorial templates** : When I click on the "Preview" button, the studio tell me : `Your Project is not a mobile project, please select a mobile project`.

I see in the debugger that nothing happen when we click "Run Page", it should run gulp and also run the npm to install the dependencies the first time. But with the angular 2 template, I only see : `open http://127.0.0.1:8083`

**Comment by yboukhata** [comment]
Hi @Ganbin,

 >  Your Project is not a mobile project, please select a mobile project

You are using ionic 2 template. Have you installed ionic 2 (`npm install -g ionic@beta`) ?

**Comment by Ganbin** [comment]
Hi, Thanks for the answer.

That's what I was suspecting, that I don't have those library. But I have add `ionic@beta` and `angular2` with `npm install -g` but still I get the same errors.

There is no help for the angular 2 and ionic 2 so what I have to install exactly to make it run?

**Comment by yboukhata** [comment]
@Ganbin 
Can you check studio console if ionic2 is installed ?
If ionic2 is not installed, you will get a warn in the console.

**Comment by Ganbin** [comment]
The console only show me Ionic but not Ionic 2. And Ionic is marked as `Found`

**Comment by Ganbin** [comment]
Sorry I have this 

```
[Environment] Node: Found - v4.4.5
[Environment] Android SDK: Found - Android Debug Bridge version 1.0.32 Revision 09a0d98bebce-android
[Environment] Gulp: Found - [16:08:58] CLI version 3.9.1
[Environment] Xcode: Found - Xcode 7.2.1 Build version 7C1002
[Environment] Ionic: Found - 2.0.0-beta.25 
[Environment] Cordova: Found - 6.2.0
```

**Comment by yboukhata** [comment]
@Ganbin 
As I see, you have installed correctly ionic2.
Can you tell me what you have in your **mobile folder** ? (like using `ls -l`, I suspect that you have not ionic project configuration file).

**Comment by Ganbin** [comment]
Here is what I have in the mobile app for the tutorial template

````
app			hooks			package.json
config.xml		ionic.config.json	resources
gulpfile.js		node_modules		www
````

**Comment by Ganbin** [comment]
And here is the content of the `ionic.config.json`

````
{
  "name": "IonicAngular2",
  "app_id": "",
  "v2": true
}

````

**Comment by yboukhata** [comment]
Can you share the right of `ionic.config.json` file ?

**Comment by Ganbin** [comment]
`-rwx------@  1 Gabriel  staff    60 24 mai 09:00 ionic.config.json`

**Comment by yboukhata** [comment]
@Ganbin 
It seem odd to have this right.
To fix this problem, you should set the correct right to `ionic.config.json`file.
You can use this command to fix this issue `chmod 644 ionic.config.json`.

**Comment by Ganbin** [comment]
Now I have `-rw-r--r--@  1 Gabriel  staff    60 24 mai 09:00 ionic.config.json` but still the project is not recognize.

**Comment by yboukhata** [comment]
Do you have the same error message **Your Project is not a mobile project, please select a mobile project** ?

**Comment by Ganbin** [comment]
yep still the same

**Comment by yboukhata** [comment]
I think that it is a right issues.

I suggest you, if possible, to zip and send me your mobile folder to check it.

**Comment by Ganbin** [comment]
Ok I do that. But I have only create a new project by choosing the ionic 2 tutorial template. I didn't touch any file.

**Comment by Ganbin** [comment]
The file is  120Mo and is to big to be shared here. How Can I send it to you?

**Comment by yboukhata** [comment]
You can remove **node_modules** folder before zipping **mobile**. 

You can create a new repot in github and I will clone it, or you can send it to me.

**Comment by Ganbin** [comment]
Ok here it is without node-modules folder : 
[mobile.zip](https://github.com/Wakanda/wakanda-issues/files/284674/mobile.zip)

**Comment by yboukhata** [comment]
Thank you. I will check it.

**Comment by Ganbin** [comment]
Thanks for the support.

**Comment by yboukhata** [comment]
@Ganbin 

I have checked without any change, and it is working for me.

Are you using the **pre-release of Wakanda (**, which support `ionic2` and `angular2` ?

If not, you can get it [here](https://wakanda.github.io/#).

**Comment by Ganbin** [comment]
I donwload it again and try but still the same problem. I even create a new project from scratch and I have the same message.

Are you sure you don't use an internal version of Wakanda? Have you tried with the one we download in your link? I can add that I am on a mac with el capitan.

**Comment by Ganbin** [comment]
I have to get out of the office for tonight I will be back tomorrow.

**Comment by yboukhata** [comment]
I am using the same version as you (download from the shared link). And I am using a Mac with **El Capitan**.

Have you extensions in **~/Documents/Wakanda/Extensions** Folder ?

Can you send me the content of this file "_your_studio_path/Wakanda\ Studio.app/Contents/Extensions/wakanda-extension-mobile-core/index.js" ?

**Comment by Ganbin** [comment]
Hi

In my **~/Documents/Wakanda/Extensions** I have those extensions : 

````
git
JSLint
wakanda-extension-mobile-core
wakanda-extension-mobile-test
wakanda-extension-trouble-shooting
WakandaIonicCreatorExtension-master
````

And here it is the `_your_studio_path/Wakanda\ Studio.app/Contents/Extensions/wakanda-extension-mobile-core/index.js` file [index.js.zip](https://github.com/Wakanda/wakanda-issues/files/285879/index.js.zip)

**Comment by yboukhata** [comment]
Hi @Ganbin,

Can you remove these extensions (by deleting their folder) in your  **~/Documents/Wakanda/Extensions** folder, and then, restart the Studio.

      git
      wakanda-extension-mobile-core
      wakanda-extension-mobile-test
      wakanda-extension-trouble-shooting

**Comment by Ganbin** [comment]
Haaa voila...

Now It works. It was those old version of those extensions who mess up.

Thanks a lot for the time to investigate for my problem. Maybe we should have a warning when old extensions are still installed.

For the _angular2 webpack_ template, when we run the app, we get that in the browser : `Cannot GET /app/index.html` because the url is `http://127.0.0.1:8000/app/index.html` but when we change to `http://127.0.0.1:8000` we get the app loaded correctly.

The _Angular2 Lite Server template_ work but I only see **Angular2 App** in the browser. So I'm not sure what this template provide as an example.

**Comment by yboukhata** [comment]
@Ganbin,

You are welcome.

> For the angular2 webpack template, when we run the app, we get that in the browser : Cannot GET /app/index.html because the url is http://127.0.0.1:8000/app/index.html but when we change to http://127.0.0.1:8000 we get the app loaded correctly.

This is a known issue. We will fix later in the next releases.


> The Angular2 Lite Server template work but I only see Angular2 App in the browser. So I'm not sure what this template provide as an example.

You are right, it is an example. But, we have integrate `wakanda-client` connector to access data.

**Comment by Ganbin** [comment]
Ok great. Looking forward for a Aurelia template :D

But I see that we gonna be able to set up our own scaffolding for our new project. Sounds great.
