### ISSUE TITLE
504 Gateway Time-out error

### ISSUE THREAD

**Issue by darrellhpl** [Wakanda/wakanda-issues#79]
HI Support

Documentation suddenly gone offline for Wakanda getting a 504 error, I now cannot read the online documentation. Is there another link or offline version I can access or download.

Kind Regards

Darrell H

**Comment by tpenner** [comment]
The main doc site was down a bit last week but it is _up now_

Regarding alternative links you could try:
* http://doc.wakanda.org
* http://doc2.wakanda.org
* http://livedoc.wakanda.org

Regarding offline access you can download the PDF docs from here:
* http://download.wakanda.org/Documentation/current/

The following github.io sites are also helpful: 
* https://wakanda.github.io/
* https://wakanda.github.io/wakanda-studio/
* https://wakanda.github.io/angular-wakanda/#/doc/quickstart
* https://wakanda.github.io/angular-wakanda/#/doc/developer-guide
