### ISSUE TITLE
Error stoping processes-Wakanda 11.201628 (v1.1.0.b)

### ISSUE THREAD

**Issue by alcada** [Wakanda/wakanda-issues#80]
Hello
I just create a new fresh solution in wakanda 11 v1.1.0.b and, when I quit the studio, I got this 2 error messages presented in the 2 attached png files.
Then, every time I open and closed the new solution (or an old solution converted from 11 v1.0.3 197492) I got the same 2 error messages, but, sometimes, entering in an infinite loop, and I have to force quit the studio.

Best regards
Luís Alçada
Coimbra University

![Uploading a.png…]()
![Uploading b.png…]()

**Comment by alcada** [comment]
![a](https://cloud.githubusercontent.com/assets/329435/16313065/717ebfa6-396f-11e6-96b4-4bb9b2b951a8.png)
![b](https://cloud.githubusercontent.com/assets/329435/16313068/75006922-396f-11e6-9fcc-5f5f6057618f.png)

**Comment by hamzahik** [comment]
Hello @alcada and thank you  for your feedback.
The team will reproduce and fix this issue. We will contact you if we need help reproducing the problem.
/cc @yboukhata @jonathanargentiero

**Comment by yboukhata** [comment]
Hello @alcada,

The issue should be in the extensions version.

Can you remove your local **Wakanda extensions**, and then restart the Studio ?

For information, you can remove your local extensions by deleting the folder `~/Documents/Wakanda/Extensions`.

**Comment by alcada** [comment]
I just completely remove the wakanda extension folder from my home Mac account folder, restart the computer, and start wakanda studio 1.1.0.b.
Now Studio tells me to update 3 extensions and I did it. Next I restart the studio, and create a new untitled solution. Now I can start and stop the solution from the upper left button without errors, but if I quit the studio (either with the solution started or stopped) the 2 mentioned error messages still exists (stopping projectIonic Services and NpmServe Services)

**Comment by yboukhata** [comment]
Hi @alcada 
We have an issue in the version of extensions.
To avoid getting this error message, I suggest you to remove your local Wakanda extensions, and then restart the Studio without updating the extensions.

**Comment by alcada** [comment]
OK. If I do not upgrade the extensions after erasing the oldest in my home folder, both subjects (80 and 81) cease to exist.
Thank you.
