### ISSUE TITLE
JDK missing.

### ISSUE THREAD

**Issue by Natanael1234** [Wakanda/wakanda-issues#82]
I'm testing Wakanda Studio 1.0.3.

In Wakanda Studio Mobile Troubleshoot, for Android, it says JDK is missing. But I have JDK installed and set on the PATH variable like in the JDK configuration tips.

OS.: Windows 10.
Wakanda Studio: 1.0.3 64 bits.
JDK: 1.8.0_92.

**Comment by jonathanargentiero** [comment]
Thanks for your report. We will investigate the issue.
If the JDK is correctly installed you can still run Android on the Studio, even if it fails detecting it.

**Comment by Natanael1234** [comment]
Thanks for reply, I tried the same thing In my personal computer and it worked well. In my job was not able to put it to work.

**Comment by jonathanargentiero** [comment]
Thanks to you! I was also able to reproduce it on a Windows 10 machine.

**Comment by Natanael1234** [comment]
My home computer also have Windows 10, but worked well.

**Comment by FrancoisMarchal** [comment]
sounds like a proxy issue?

**Comment by Natanael1234** [comment]
FrancoisMarchal, where and how could I configure this proxy?

**Comment by Natanael1234** [comment]
In the Console, Wakanda says:
[Environment] wakanda-extension-mobile-console 1.0.0
[Environment] If you need help click here to open the troubleshooting!
[Environment] Environment variable JAVA_HOME: Found - C:\Program Files\Java\jdk1.8.0_91
[Environment] Android SDK: Not found - Install Android SDK »
[Environment] Environment variable ANDROID_HOME: Not found - Install Android SDK »
[Environment] Node: Found - v6.2.2
[Environment] Gulp: Found - [08:43:36] CLI version 3.9.1
[Environment] Cordova: Found - You have been opted out of telemetry. To change this, run: cordova telemetry on.
6.2.0
[Environment] Ionic: Found - 2.0.0-beta.32 

But in Wakanda Mobile Troubleshoot it says "Install JDK" is missing.

**Comment by yboukhata** [comment]
Hi @Natanael1234,

Have you setted correctly the environment variable `ANDROID_HOME`.

In command line, can you tell what do you have when running this command : `echo %ANDROID_HOME%` ?

**Comment by Natanael1234** [comment]
I don't made the installation of Android SDK and the setup of Android Home yet.

**Comment by yboukhata** [comment]
@Natanael1234 
To fix it, you should install **java JDK** , **Android SDK** and configure all the environment variables as described in the **Troubleshooting app**.

**Comment by Natanael1234** [comment]
I mean JDK and ANT are missing according to  Wakanda's Mobile Troubleshoot. 

They are installed and configurated according.

**Comment by Natanael1234** [comment]
Here is my configuration:
https://s31.postimg.org/qok2s7pnf/enviroment_variables.png

**Comment by Natanael1234** [comment]
The ANT problem is solved now. It was lacking a "\bin" at the end.

JDK problem still not solved.

**Comment by Natanael1234** [comment]
Solved. There was a PATH in System Variables and another in User Variables. The PATH in System variables had some outdated path to JDK and seems it was overriding the PATH in user variables.

All I needed was to remove the PATH in System Variables and restart the system.

**Comment by LeonidProkopets** [comment]
Same story on my side. 
Windows 10
Wakanda Studio  2.6.0
JDK 12.0.1

JAVA_HOME = 'C:\Program Files\Java\jdk_12.0.1'
Path = '%JAVA_HOME%\bin; .... '

Wakanda does not find JDK. I shuffled JAVA_HOME and Path many times, put it to user and system variables and to both, changed backslash to frontslash and tried everything I could think of. Still - no result.
