### ISSUE TITLE
Sending a file with a PUT request will result in a POST request

### ISSUE THREAD

**Issue by steeu** [Wakanda/wakanda-issues#84]
Sending a file with a PUT request will automatically result in a POST request. Using a webservice like Tika, which requires a PUT request is therefore not possible.

Tested with Wakanda version 11.197492 on Windows 7

Code Example:

```
var error, file, url, xhr;

file = new File("/PROJECT/web/pdf.pdf");
url = "http://localhost:9998/tika";

// send data
try {
    xhr = new XMLHttpRequest();
    xhr.open("PUT", url);
    xhr.setRequestHeader('Accept', 'text/plain');
    xhr.send(file);
} catch (e) {
    error = e.stack;
}

({
    response: xhr.responseText,
    status: xhr.statusText,
    error: error,
    type: xhr.responseType
});
```
Network Protocol:
![error-send-as-put](https://cloud.githubusercontent.com/assets/3204827/16725590/3f41e2a6-4758-11e6-9f9b-0da2f2fa95fa.png)

**Comment by hamzahik** [comment]
1.1.0 released with the fix
