### ISSUE TITLE
Error Building sources-angular-wakanda and (Filename too long) on Windows 7 32bit

### ISSUE THREAD

**Issue by sanyaade-mobiledev** [Wakanda/wakanda-issues#85]
Hi All,  

While I was trying to build on Windows7 I got the following errors below:

> $ npm install
npm WARN package.json sources-angular-wakanda@1.1.4 No repository field.

> sources-angular-wakanda@1.1.4 postinstall F:\wkdir4\Wakanda\wkda
> bower install

bower wakanda-client#^0.3.5 not-cached https://github.com/Wakanda/wakanda-javascript-client.git#^0.3.5
bower wakanda-client#^0.3.5    resolve https://github.com/Wakanda/wakanda-javascript-client.git#^0.3.5
bower angular#1.3.*             cached https://github.com/angular/bower-angular.git#1.3.20
bower angular#1.3.*           validate 1.3.20 against https://github.com/angular/bower-angular.git#1.3.*
bower angular-mocks#~1.3.0      cached https://github.com/angular/bower-angular-mocks.git#1.3.20
bower angular-mocks#~1.3.0    validate 1.3.20 against https://github.com/angular/bower-angular-mocks.git#~1.3.0
bower wakanda-client#^0.3.5   checkout v0.3.5
bower wakanda-client#^0.3.5    ECMDERR Failed to execute "git clone https://github.com/Wakanda/wakanda-javascript-client.git -b v0.3.5 --progress . --depth 1", exit code of #128 Cloning into '.'... remote: Counting objects: 275, done.         remote: ComprResolving deltas: 100% (63/63), done. remote: Total 275 (delta 63), reused 119 (delta 21), pack-reused 0         Checking connectivity... done. Note: checking out 'f4c8fac731643318cc1b507e345903845d1afcb5'.  You are in 'detached HEAD' state. You can look around, make experimental changes and commit them, and you can discard any commits you make in this state without impacting any branches by performing another checkout.  If you want to create a new branch to retain commits you create, you may do so (now or later) by using -b with the checkout command again. Example:    git checkout -b <new-branch-name>  error: unable to create file test/connect/mocks/rest/_rest_Company(2728)_staff__expand=staff&_limit=10&_method=subentityset_WASID__2b5916c58f7b5ccdfbca97982865181bf07ca922.json (Filename too long) error: unable to create file test/connect/mocks/rest/_rest_Company(2728)_staff__expand=staff&_limit=40&_method=subentityset_WASID__ee176b26022a37c587f5a6cd57b4048eaacf9f8e.json (Filename too long) error: unable to create file test/connect/mocks/rest/_rest_Company(2728)_staff__expand=staff&_limit=40&_skip=10&_method=subentityset_WASID__d8ba400e0d134ddc226e09cae335e8081d81a6e5.json (Filename too long) error: unable to create file test/connect/mocks/rest/_rest_Company(2728)_staff__expand=staff&_method=subentityset&_emMethod=firstOfCollection_WASID__3affeb947a5024fb0ff4780c3f90cb31b90a8214.json (Filename too long) error: unable to create file test/connect/mocks/rest/_rest_Company(2728)_staff__expand=staff&_method=subentityset&_emMethod=myCollectionMethod_WASID__fd01ba1552f047302ff5fb89414f66ed2beba904.json (Filename too long) error: unable to create file test/connect/mocks/rest/_rest_Company(2728)_staff__expand=staff&_method=subentityset&_emMethod=someCompanies_WASID__0f79a313630ac516dbb45ae42d40d75734340637.json (Filename too long) error: unable to create file test/connect/mocks/rest/_rest_Company__entityset_BDEB464DB5CF4CAA902E8097810BD6BF__limit=5&_skip=5&_method=subentityset_WASID__052b6716ace6f3a052485ce4c8adaa8d2c467561.json (Filename too long) error: unable to create file test/connect/mocks/rest/_rest_Company__entityset_E222A5253A644D91812EDD733EEB6A58__limit=15&_method=subentityset_WASID__5c01a2fc78e09f0aea5f744c739b2c429ecff9ef.json (Filename too long) error: unable to create file test/connect/mocks/rest/_rest_Company__entityset_E222A5253A644D91812EDD733EEB6A58__limit=5&_method=subentityset_WASID__1ac84fb4a862fee4a9f9f0410bd56a55c4cab29f.json (Filename too long) error: unable to create file test/connect/mocks/rest/_rest_Company__entityset_E222A5253A644D91812EDD733EEB6A58__limit=5&_skip=5&_method=subentityset_WASID__914c30788e1bd23fa1c98c4d033fef372603149c.json (Filename too long) error: unable to create file test/connect/mocks/rest/_rest_Company__entityset_E222A5253A644D91812EDD733EEB6A58_firstOfCollection_WASID__c294bf85a15d3161f610e3d4961fdc58980248c9.json (Filename too long) error: unable to create file test/connect/mocks/rest/_rest_Company__entityset_E222A5253A644D91812EDD733EEB6A58_myCollectionMethod_WASID__0a288e90e684a5f318226efe33e1ec5cfc3bd5e6.json (Filename too long) error: unable to create file test/connect/mocks/rest/_rest_Company__entityset_E222A5253A644D91812EDD733EEB6A58_returnSelf_WASID__7489af91718a3dfb64092d0332905e63ac728b56.json (Filename too long) error: unable to create file test/connect/mocks/rest/_rest_Employee__entityset_4FD3E764207C42A8A6CD955F5DFACAD8_firstOfCollection_WASID__e5c8f584cc4bb5084062bd14d538d27a2e109df2.json (Filename too long) error: unable to create file test/connect/mocks/rest/_rest_Employee__entityset_4FD3E764207C42A8A6CD955F5DFACAD8_myCollectionMethod_WASID__6b9e3dca4d4dd1f32c70c4b2e1a223fdc8738f82.json (Filename too long) error: unable to create file test/connect/mocks/rest/_rest_Employee__entityset_4FD3E764207C42A8A6CD955F5DFACAD8_someCompanies_WASID__123c2790303b0fad8bb247750e2cbd3779c70f2e.json (Filename too long) error: unable to create file test/connect/mocks/rest/_rest_Employee__expand=employer.staff&_limit=3&_method=entityset_WASID__b71cab1c50c7bc00a976ac6708697c409dcafd68.json (Filename too long) error: unable to create file test/connect/mocks/rest/_rest_Employee__filter=%22ID%20%3E%200%22&_limit=40&_method=entityset_WASID__ce8ac77811f87d3c695e8737f8a9b8ab9d5c94ce.json (Filename too long) error: unable to create file test/connect/mocks/rest/_rest_Employee__filter=%22employer.ID%20%3E%200%22&_limit=1&_method=entityset_WASID__b0238ff2fcc89974f8dc17d4511dbb58ccfa43f3.json (Filename too long) error: unable to create file test/connect/mocks/rest/_rest_Employee__filter=%22firstName%20=%20_1%22&_params=%27[%22ARON%22]%27&_limit=40&_method=entityset_WASID__a874ec86c98d1b51aedc670c94799a79aab4f870.json (Filename too long) error: unable to create file test/connect/mocks/rest/_rest_Employee__filter=%22firstName%20=%20_1%22&_params='%5B%22ARON%22%5D'&_limit=40&_method=entityset_WASID__48659ae43a3f30a1bc0e346d5f0e83c3309e055d.json (Filename too long) error: unable to create file test/connect/mocks/rest/_rest_Employee__orderby=salary%20desc&_limit=20&_method=entityset_WASID__d1ef574ba456d798f3a25013a5221f01415767cc.json (Filename too long) error: unable to create file test/connect/mocks/rest/_rest_Product__filter=%22born%20%3C%20_1%22&_params=%27[%222016-05-16T13_00_00.447Z%22]%27&_limit=40&_method=entityset_WASID__5d211e5be36ef7e9b38fbd3911d93323570704f2.json (Filename too long) error: unable to create file test/connect/mocks/rest/_rest_Product__filter=%22born%20%3C%20_1%22&_params='%5B%222016-05-16T13_00_00.447Z%22%5D'&_limit=40&_method=entityset_WASID__b285312d9ff4692a69da7c1f752e29258dc31953.json (Filename too long) error: unable to create file test/connect/mocks/rest/_rest__directory_currentUserBelongsTo_WASID_WASID=86937589ED4942A1BAEA15EB5B554158_690bd5f648a319c6d12843e60f74aaa970fe3d42.json (Filename too long) error: unable to create file test/connect/mocks/rest/_rest__directory_currentUserBelongsTo_WASID_WASID=86937589ED4942A1BAEA15EB5B554158_ccb771641d8f023e816a980f27be21a213e9fa01.json (Filename too long) error: unable to create file test/connect/mocks/rest/_rest__directory_currentUserBelongsTo_WASID_WASID=898DE192E44846B790B268DB73D326ED_1020d7274bf2b2f06a5242a759fffdc2a23c91ac.json (Filename too long) error: unable to create file test/connect/mocks/rest/_rest__directory_currentUser_WASID_WASID=86937589ED4942A1BAEA15EB5B554158_47df797578d162c82ca07922536f8576f90db3e9.json (Filename too long) error: unable to create file test/connect/mocks/rest/_rest__directory_currentUser_WASID_WASID=898DE192E44846B790B268DB73D326ED_400700f2a17b9bda9a2df0ed8f4ca1e59f7503b6.json (Filename too long) fatal: unable to checkout working tree warning: Clone succeeded, but checkout failed. You can inspect what was checked out with 'git status' and retry the checkout with 'git checkout -f HEAD'

Additional error details:
Cloning into '.'...
remote: Counting objects: 275, done.
remote: Compressing objects: 100% (241/241), done.
Receiving objects: 100% (275/275), 421.00 KiB | 633.00 KiB/s, done.
Resolving deltas: 100% (63/63), done.
remote: Total 275 (delta 63), reused 119 (delta 21), pack-reused 0
Checking connectivity... done.
Note: checking out 'f4c8fac731643318cc1b507e345903845d1afcb5'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

error: unable to create file test/connect/mocks/rest/_rest_Company(2728)_staff__expand=staff&_limit=10&_method=subentityset_WASID__2b5916c58f7b5ccdfbca97982865181bf07ca922.json (Filename too long)
error: unable to create file test/connect/mocks/rest/_rest_Company(2728)_staff__expand=staff&_limit=40&_method=subentityset_WASID__ee176b26022a37c587f5a6cd57b4048eaacf9f8e.json (Filename too long)
error: unable to create file test/connect/mocks/rest/_rest_Company(2728)_staff__expand=staff&_limit=40&_skip=10&_method=subentityset_WASID__d8ba400e0d134ddc226e09cae335e8081d81a6e5.json (Filename too long)
error: unable to create file test/connect/mocks/rest/_rest_Company(2728)_staff__expand=staff&_method=subentityset&_emMethod=firstOfCollection_WASID__3affeb947a5024fb0ff4780c3f90cb31b90a8214.json (Filename too long)
error: unable to create file test/connect/mocks/rest/_rest_Company(2728)_staff__expand=staff&_method=subentityset&_emMethod=myCollectionMethod_WASID__fd01ba1552f047302ff5fb89414f66ed2beba904.json (Filename too long)
error: unable to create file test/connect/mocks/rest/_rest_Company(2728)_staff__expand=staff&_method=subentityset&_emMethod=someCompanies_WASID__0f79a313630ac516dbb45ae42d40d75734340637.json (Filename too long)
error: unable to create file test/connect/mocks/rest/_rest_Company__entityset_BDEB464DB5CF4CAA902E8097810BD6BF__limit=5&_skip=5&_method=subentityset_WASID__052b6716ace6f3a052485ce4c8adaa8d2c467561.json (Filename too long)
error: unable to create file test/connect/mocks/rest/_rest_Company__entityset_E222A5253A644D91812EDD733EEB6A58__limit=15&_method=subentityset_WASID__5c01a2fc78e09f0aea5f744c739b2c429ecff9ef.json (Filename too long)
error: unable to create file test/connect/mocks/rest/_rest_Company__entityset_E222A5253A644D91812EDD733EEB6A58__limit=5&_method=subentityset_WASID__1ac84fb4a862fee4a9f9f0410bd56a55c4cab29f.json (Filename too long)
error: unable to create file test/connect/mocks/rest/_rest_Company__entityset_E222A5253A644D91812EDD733EEB6A58__limit=5&_skip=5&_method=subentityset_WASID__914c30788e1bd23fa1c98c4d033fef372603149c.json (Filename too long)
error: unable to create file test/connect/mocks/rest/_rest_Company__entityset_E222A5253A644D91812EDD733EEB6A58_firstOfCollection_WASID__c294bf85a15d3161f610e3d4961fdc58980248c9.json (Filename too long)
error: unable to create file test/connect/mocks/rest/_rest_Company__entityset_E222A5253A644D91812EDD733EEB6A58_myCollectionMethod_WASID__0a288e90e684a5f318226efe33e1ec5cfc3bd5e6.json (Filename too long)
error: unable to create file test/connect/mocks/rest/_rest_Company__entityset_E222A5253A644D91812EDD733EEB6A58_returnSelf_WASID__7489af91718a3dfb64092d0332905e63ac728b56.json (Filename too long)
error: unable to create file test/connect/mocks/rest/_rest_Employee__entityset_4FD3E764207C42A8A6CD955F5DFACAD8_firstOfCollection_WASID__e5c8f584cc4bb5084062bd14d538d27a2e109df2.json (Filename too long)
error: unable to create file test/connect/mocks/rest/_rest_Employee__entityset_4FD3E764207C42A8A6CD955F5DFACAD8_myCollectionMethod_WASID__6b9e3dca4d4dd1f32c70c4b2e1a223fdc8738f82.json (Filename too long)
error: unable to create file test/connect/mocks/rest/_rest_Employee__entityset_4FD3E764207C42A8A6CD955F5DFACAD8_someCompanies_WASID__123c2790303b0fad8bb247750e2cbd3779c70f2e.json (Filename too long)
error: unable to create file test/connect/mocks/rest/_rest_Employee__expand=employer.staff&_limit=3&_method=entityset_WASID__b71cab1c50c7bc00a976ac6708697c409dcafd68.json (Filename too long)
error: unable to create file test/connect/mocks/rest/_rest_Employee__filter=%22ID%20%3E%200%22&_limit=40&_method=entityset_WASID__ce8ac77811f87d3c695e8737f8a9b8ab9d5c94ce.json (Filename too long)
error: unable to create file test/connect/mocks/rest/_rest_Employee__filter=%22employer.ID%20%3E%200%22&_limit=1&_method=entityset_WASID__b0238ff2fcc89974f8dc17d4511dbb58ccfa43f3.json (Filename too long)
error: unable to create file test/connect/mocks/rest/_rest_Employee__filter=%22firstName%20=%20_1%22&_params=%27[%22ARON%22]%27&_limit=40&_method=entityset_WASID__a874ec86c98d1b51aedc670c94799a79aab4f870.json (Filename too long)
error: unable to create file test/connect/mocks/rest/_rest_Employee__filter=%22firstName%20=%20_1%22&_params='%5B%22ARON%22%5D'&_limit=40&_method=entityset_WASID__48659ae43a3f30a1bc0e346d5f0e83c3309e055d.json (Filename too long)
error: unable to create file test/connect/mocks/rest/_rest_Employee__orderby=salary%20desc&_limit=20&_method=entityset_WASID__d1ef574ba456d798f3a25013a5221f01415767cc.json (Filename too long)
error: unable to create file test/connect/mocks/rest/_rest_Product__filter=%22born%20%3C%20_1%22&_params=%27[%222016-05-16T13_00_00.447Z%22]%27&_limit=40&_method=entityset_WASID__5d211e5be36ef7e9b38fbd3911d93323570704f2.json (Filename too long)
error: unable to create file test/connect/mocks/rest/_rest_Product__filter=%22born%20%3C%20_1%22&_params='%5B%222016-05-16T13_00_00.447Z%22%5D'&_limit=40&_method=entityset_WASID__b285312d9ff4692a69da7c1f752e29258dc31953.json (Filename too long)
error: unable to create file test/connect/mocks/rest/_rest__directory_currentUserBelongsTo_WASID_WASID=86937589ED4942A1BAEA15EB5B554158_690bd5f648a319c6d12843e60f74aaa970fe3d42.json (Filename too long)
error: unable to create file test/connect/mocks/rest/_rest__directory_currentUserBelongsTo_WASID_WASID=86937589ED4942A1BAEA15EB5B554158_ccb771641d8f023e816a980f27be21a213e9fa01.json (Filename too long)
error: unable to create file test/connect/mocks/rest/_rest__directory_currentUserBelongsTo_WASID_WASID=898DE192E44846B790B268DB73D326ED_1020d7274bf2b2f06a5242a759fffdc2a23c91ac.json (Filename too long)
error: unable to create file test/connect/mocks/rest/_rest__directory_currentUser_WASID_WASID=86937589ED4942A1BAEA15EB5B554158_47df797578d162c82ca07922536f8576f90db3e9.json (Filename too long)
error: unable to create file test/connect/mocks/rest/_rest__directory_currentUser_WASID_WASID=898DE192E44846B790B268DB73D326ED_400700f2a17b9bda9a2df0ed8f4ca1e59f7503b6.json (Filename too long)
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "E:\\COMPILERS\\nodejs\\node.exe" "E:\\COMPILERS\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE
npm ERR! sources-angular-wakanda@1.1.4 postinstall: `bower install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sources-angular-wakanda@1.1.4 postinstall script 'bower install'.
npm ERR! This is most likely a problem with the sources-angular-wakanda package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sources-angular-wakanda
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls sources-angular-wakanda
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\wkdir4\Wakanda\wkda\npm-debug.log

Administrator@sanyaade-PC MINGW32 /f/wkdir4/Wakanda/wkda (master)
$

Please help!

God blesses!!!

Best regards,
Sanyaade

**Comment by jonathanargentiero** [comment]
Hello @sanyaade-mobiledev,

Git should have a limit of 4096 characters for a filename and not trigger that error. I found a similar issue when git is compiled with msys which uses an older version of the windows api (with a limit of 260 characters for a filename).

I suggest you to apply the fix proposed here http://stackoverflow.com/questions/21123415/git-pull-aborted-with-error-filename-too-long which consist in manually settings the `longpaths` option of Git to `true` with:

```
git config --system core.longpaths true
```

Tell me if this solves your issue.

**Comment by sanyaade-mobiledev** [comment]
@jonathanargentiero: 

Many thanks for the pointer. Following your direction, I was able to build it on Windows 7 64bit. First run the console as administrator, next issue the command:-> git config --system core.longpaths true followed by npm install. Its build without error. I then issue the command:-> npm run serve, it loads up at port 9092. Navigating to localhost:9092 display Home Profile text on browser.

I will check for other run options late and let you know.

Once again, many thanks!

God blesses!!!

**Comment by luisa123456** [comment]
Long Path Tool can help you to remove blocked files or too long path files. You can easily fix file errors with this software.
