### ISSUE TITLE
V1.1.0 pre-release – how to use Angular 2

### ISSUE THREAD

**Issue by chriscurnow** [Wakanda/wakanda-issues#88]
I downloaded the v1.1.0 pre-release with Angular 2 & Ionic 2 support. What do I do now? How is Angular2 supported? How do I find out how to use the Angular 2 support in this pre-release?

I tried cloning the javascript-client and running it as the Readme suggested. All I go on the screen were two buttons – A 'Choose File" button and a "Send" button. So what do I do now?

There is no indication in any of this what entry points I could use.

**Comment by hamzahik** [comment]
I'll close this one since we are already discussing this on #87
