### ISSUE TITLE
gitter channel

### ISSUE THREAD

**Issue by vegarringdal** [Wakanda/wakanda-issues#98]
Would be great if you guys considered a gitter channel so its easier to communicate with other users of the software.

**Comment by hamzahik** [comment]
We are already working on that :)

**Comment by vegarringdal** [comment]
great, any eta?

**Comment by bea2701** [comment]
this would be great have Wakanda community back online

**Comment by hamzahik** [comment]
The gitter channel should be created this week.

**Comment by vegarringdal** [comment]
:+1:

**Comment by AaronLavers** [comment]
We should set up an IRC channel :P

**Comment by hamzahik** [comment]
@vegarringdal @bea2701 @AaronLavers Here you go https://gitter.im/wakandasoft/Lobby
